### ISSUE TITLE
Add numbering

### ISSUE THREAD

**Issue by JingJang** [ccloli/E-Hentai-Downloader#1]
Please consider adding numbers to it. 
<a href ="https://github.com/JingJang/E-Hentai-Downloader/blob/ec84734908f4962d2335f615a84144276b04edb8/e-hentai-downloader.user.js">Example of code changes</a>

**Comment by ccloli** [comment]
Thanks for your contribution, I'll think about it.

**Comment by ccloli** [comment]
Added, but needs to be enabled in setting page.
