### ISSUE TITLE
Script doesn't work on some pages

### ISSUE THREAD

**Issue by typhoon71** [ccloli/E-Hentai-Downloader#10]
I noticed I can't download from "http://exhentai.org/g/354095/7148834893/".
Happens on Azasuke Wind Coll. 13, 14, 15, 16 too. I can download normally any other page.
I did not hit any limit, it's just that when I click the download "button" nothing happens.
Happens on win7 x64, ffox 40.0.3, ffox 41.0, greasemonkey 3.4.1.
Any idea how to solve this?

**Comment by ccloli** [comment]
This bug has been fixed just now, please update it. 

If the bug is still exist, please press F12 and switch to "Console", copy all the logs and paste them here, then comment and reopen this issue.

**Comment by typhoon71** [comment]
I confirm it's fixed, I only had to upgrade manually (usually it's updated automatically).
Thanks.
