### ISSUE TITLE
Pre-calculated counter is broken

### ISSUE THREAD

**Issue by momoe** [ccloli/E-Hentai-Downloader#101]
Looks like e-hentai made some changes to their site. GP exchange now requires something called "Hath"???

**Comment by ccloli** [comment]
Hi, I checked E-Hentai & ExHentai, both of them are working fine. If you have some other E-Hentai scripts, make sure E-Hentai Downloader runs before the other scripts run.

GP can be exchanged by credit, and credit can be exchanged by both GP and Hath. Hath is a bonus for hosting Hentai@Home.
