### ISSUE TITLE
Part of the pictures fail to load/download

### ISSUE THREAD

**Issue by stevenxqs** [ccloli/E-Hentai-Downloader#105]
大佬您好，
近一个月左右ex的几乎所有作品在下载大图时总会有部分持续fail，通过正常方式打开时左上角会显示一个裂了的图标（缩略图显示没问题，持续尝试"Click here if the image fails loading"无果），虽然我感觉和您的插件并无直接关系，但还是想请求您帮助我分析一下问题原因。
浏览器：火狐和chrome都试过了，网络环境也进行了少量的更换测试。
如果有什么测试的方法，方便的话请您告诉我。
非常感谢！

attachment:
![baidu ime_2018-5-9_1-37-26](https://user-images.githubusercontent.com/19363634/39773195-dec70912-5329-11e8-8c27-215b92a2aed8.jpg)

**Comment by ccloli** [comment]
如果您更换过了多个浏览器，那么有可能是你的网络有问题。可以试试看以下步骤进行排查：

1. 尝试清理 Cookies，并确认浏览器 Cookies 策略已允许 Cookies 和第三方 Cookies，或者已将 E-Hentai 加入白名单，然后重新登录再试一次。最近有很多 issue 都是与 Cookies 有关的，建议您先试试重置 E-Hentai 的 Cookies 并重新登录；
2. 尝试使用代理访问，若经过代理服务器能正常访问，那么这很有可能是您的运营商存在问题，否则则是 E-Hentai 的问题；
3. 按下 F12 切换到 Network/网络 选项卡，然后勾选 Preserve log/保留网络日志，然后在当前页打开图片下载链接，在网络面板内可以看到 HTTP 请求，找到图片最终访问的请求，检查连接是否成功收到了服务器的响应，并检查 HTTP Headers/首部，通过首部返回的数据来猜测是运营商的问题还是 E-Hentai 的问题。

希望对您有用。

**Comment by ccloli** [comment]
哦，刚刚才看到图片，上面的是根据邮件内的正文回复的。

这个情况多半是与 Hentai@Home 节点连接不佳，至于为何不佳，那就只能说是网络问题了。亚洲区多半连接的是在亚洲的节点，但是这些节点不一定能够被访问到（你懂的）。遇到这种情况只能等待下载脚本重试下载获取新的图片链接，如果是在浏览的话，可以点击底部的 _Click here if the image fails loading_ 来从 E-Hentai 的原始服务器加载文件。
