### ISSUE TITLE
在下载列表内没法点重新获取链接

### ISSUE THREAD

**Issue by operammm** [ccloli/E-Hentai-Downloader#108]
火狐60 
Tampermonkey 
E-Hentai Downloader | 1.30.1
记得原先可以的。

现在一直卡下载中或下载失败，被动也不弹出重新下载的提示。
能加个主动控制的重新下载全部失败链接的功能吗？谢谢了。

**Comment by Feketerigo** [comment]
Same problem here.
opera 53.0
