### ISSUE TITLE
脚本不能打包下载了.

### ISSUE THREAD

**Issue by Hdjw1504** [ccloli/E-Hentai-Downloader#109]
暴力猴版本v2.9.4
脚本版本v1.30.2
浏览器版本 360极速浏览器
几十MB的图包可以下载,一两百的就不行了,但脚本设定是上限500+MB.之前可以下载,重装系统后就不行了.
打包进度条到90%左右就暂停不动了,求大佬给个建议.

**Comment by ccloli** [comment]
Hi，这应该是您的系统内存不足。根据您的描述，您可能在使用 4GB RAM 的计算机，所以可能会出现内存不足的情况。您可以尝试启用通过 File System 存储文件，同时将下限值调小，按照您的情况可以试试设置成 50MB，然后再试试。
