### ISSUE TITLE
Picture download become sadpanda

### ISSUE THREAD

**Issue by santose22** [ccloli/E-Hentai-Downloader#110]
近期下載的圖檔皆為sadpanda ， 是否有哪裡可以調整?
![100](https://user-images.githubusercontent.com/40137465/41199803-55ac7644-6cd3-11e8-8ad6-0e90a16303c5.png)

**Comment by ccloli** [comment]
Hi，這應該是您的 Cookies 存在一些問題，請嘗試清理 Cookies 后重新登錄試試。如果以上操作沒有效果，您可以試試按照 https://github.com/ccloli/E-Hentai-Downloader/issues/92#issuecomment-359184675 的方法，確認您已允許 Cookies 並且允許第三方 Cookies。

**Comment by santose22** [comment]
看起來跟我開啟無痕模式有關，謝謝解答
