### ISSUE TITLE
Spurious image viewing limit reached error

### ISSUE THREAD

**Issue by seadra** [ccloli/E-Hentai-Downloader#111]
Despite having only used of ~5000 out of 50000 image viewing limits (as reported on the gallery page like "E-Hentai Downloader | Image Limits: 4992/50000  | Estimated Limits Cost: 952"), the downloader is telling me that I reached my image viewing limits.

**Comment by ccloli** [comment]
Hi, as [an issue from GreasyFork](https://greasyfork.org/zh-CN/forum/discussion/27042/x) says, it's a bug of E-Hentai itself. His solution is disabling loading from Hentai@Home, you can have a try, but noticed that this will use your image limits more than loading from H@H network. Also you can consider sending a feedback to E-Hentai Forums if needed.

**Comment by seadra** [comment]
Disabling H@H loading did work as a workaround, thanks!
