### ISSUE TITLE
Script paused when Tab not active

### ISSUE THREAD

**Issue by dinemuatta** [ccloli/E-Hentai-Downloader#115]
Hiho :)

First of all, I fucking love this script. I think it needs a lot of work and time so thanks!

But does someone else have this problem, that the download pauses when i switch to another tab or minimize chrome? I always have to stay on the active tab to keep the script downloading.

Thx!

**Comment by ccloli** [comment]
See #65 .

> ...... you can try enabling playing silent audio to prevent Chrome's optimization. To enable it , check out _Settings -> Advanced -> Play silent music during the process to avoid downloading freeze_.

**Comment by dinemuatta** [comment]
omg sry dont know why i didnt saw this. thanks works sooo fine!!!
