### ISSUE TITLE
[suggestion]add use zip save file"No path save" / "root save"

### ISSUE THREAD

**Issue by sunyink** [ccloli/E-Hentai-Downloader#116]
[建议]将zip文件 增选 用 “无路径保存” / “根目录 保存”
[suggestion]add use zip save file "No path save" / "root save"

我们的软件运作的那么好，谢谢作者。我注意到一个问题，软件保存的.zip文件的目录是包含一个文件夹的(“#/编号/文件")，这导致很多图像管理软件(能读压缩包的那种)无法读取出压缩文件的缩略图。
Our software works so well, thanks to the author. One problem I noticed was that the directory of the.Zip file saved by the software contained a folder ("#/ number / file"), which caused many image management software (like the one that reads compression packages) to fail to read the thumbnail of the compressed file.
然而如果压缩档案目录是("#/文件")就不会有问题。
However, if you compress the file directory is ("zip / file"), there will be no problem.
建议能在设置页面增添复选框：保存的压缩档案使用无路径保存。
It is recommended to add check boxes to the settings page: save compressed files using no path save.

Thank you~

**Comment by ccloli** [comment]
Hi, if you mean you want to store the images without being contained by a folder, you can go to _Settings_ -> _Basic_ and set `Set folder name as ...` to `/`.

![image](https://user-images.githubusercontent.com/8115912/47311173-9b4a9080-d66b-11e8-8621-846e6dae04d9.png)

**Comment by sunyink** [comment]
唉...我几乎不会英文，web翻译也效果差。问了笨问题呢。谢谢你抽出时间解决了我的问题！
Sigh. I can hardly speak English. Web translation is also bad. I asked stupid questions. Thank you for taking the time to solve my problem!

**Comment by ccloli** [comment]
Pleased to solve your question, and feel free to create a new issue if you have a new problem. 😄
