### ISSUE TITLE
Suggestion of function `getSafeName`

### ISSUE THREAD

**Issue by mo-han** [ccloli/E-Hentai-Downloader#119]
```javascript
function getSafeName(str, ignoreSlash) {
	var replaceList = {
		':': '：',
		'"': '″',  // DOUBLE PRIME, U+2033
		'*': '∗',  // ASTERISK OPERATOR, U+2217
		'?': '？',
		'|': '￨',  // halfwidth forms light vertical, U+FFE8
		'<': '﹤',  // SMALL LESS-THAN SIGN, U+FE64
		'>': '﹥',  // SMALL GREATER-THAN SIGN, U+FE65
		'/': '⁄',  // FRACTION SLASH, U+2044
		'\\': '⧹',  // BIG REVERSE SOLIDUS, U+29F9
		'\n': '-'
	};
```

**Comment by ccloli** [comment]
Looks like some letters are not working on some device?

![screenshot_2018-11-01-20-25-12](https://user-images.githubusercontent.com/8115912/47851842-d5244100-dda7-11e8-8630-ff03b9c481f1.png)

**Comment by ccloli** [comment]
Looks like some letters are not working on some device?

![screenshot_2018-11-01-20-23-50](https://user-images.githubusercontent.com/8115912/47851886-f71dc380-dda7-11e8-86e6-9bdd95b21291.png)

**Comment by mo-han** [comment]
Ah, I see, it's just a suggestion. Those uncommon chars work well on desktop OS, though.
I'm just tired of editing the script every time after updating.
