### ISSUE TITLE
当ip出现流量限制509的时候，报账号限额错误

### ISSUE THREAD

**Issue by lukemin** [ccloli/E-Hentai-Downloader#125]
当ip出现流量限制509的时候，报账号限额错误
实际解决方法是使用代理及vpn，而不是重置限额！

**Comment by ccloli** [comment]
[脚本的 wiki 页](https://github.com/ccloli/E-Hentai-Downloader/wiki/E%E2%88%92Hentai-Image-Viewing-Limits-(Chinese)) 已经提到 image viewing limits 是根据 IP 计算的，[EH 的捐赠功能的 wiki 页](https://ehwiki.org/wiki/Donation#Stars) 也提到了 image limit 是根据 IP 地址计算的（但如果捐赠到 Brozen 则会根据账号计算）。

对于网站本身来说，使用 GP 或者 credit 来重置 image limit 是 **标准和正常** 的做法。当然你完全可以利用这个计算规则的漏洞，通过更换访问的 IP 地址（重新 PPPoE 拨号或者走代理等）来获得一份新的 image limit，但是这毕竟不是标准做法。

**Comment by lukemin** [comment]
最主要的是 我开着H@H server 下载本子根本不会出现账号流量限制的情况啊！
