### ISSUE TITLE
[bug] New Update Kills E-Hentai Downloader :( March 19

### ISSUE THREAD

**Issue by reihunter360** [ccloli/E-Hentai-Downloader#131]
I try clicking on download, it doesn't work anymore. Oh wells.

**Comment by ccloli** [comment]
The `@version` is not updated in `e-hentai-downloader.meta.js` and  `e-hentai-downloader.user.js`, so you will not get the update. And I checked the diff parts, it's just fixed a HTML tag which is not closed. 

As I haven't got off work yet, so I cannot check if it's working or not. You can press `F12` and switch to `Console` tab, and refresh the page, then click the download link. If the script gets some error, you can copy them from `Console` and paste them here. Thanks.

**Comment by Unoven454** [comment]
[EHD] E-Hentai Downloader is running.
userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:41 [EHD] Bugs Report > https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback
userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:42 [EHD] To report a bug, it's recommended to provide the logs started with "[EHD]", thanks. =w=
userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:12308 [EHD] UserAgent > Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:12309 [EHD] Script Handler > Tampermonkey
userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:12310 [EHD] Script Handler Version > 4.8
userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:12311 [EHD] E-Hentai Downloader Version > 1.31.2
userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:12312 [EHD] Current URL > https://exhentai.org/g/1379179/f2dde11617/
userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:12313 [EHD] Is Logged In > true
userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:12275 [EHD] E-Hentai Downloader Setting > {"save-info-list":["title","metas","uploader-comment","page-links"],"auto-download-cancel":true}
userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:14260 [EHD] Request Image Limits From e-hentai.org
userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:12404 Uncaught TypeError: Cannot read property 'getAttribute' of null
    at getReplacedName (userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:12404)
    at initEHDownload (userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:13650)
    at HTMLDivElement.eval (userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:14393)
getReplacedName @ userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:12404
initEHDownload @ userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:13650
(anonymous) @ userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:14393
3userscript.html?id=9e828a7b-8a98-4975-9da6-f5eca027210d:14260 [EHD] Request Image Limits From e-hentai.org

**Comment by ccloli** [comment]
Looks like E-Hentai just changes the layout so that E-Hentai Downloader cannot find the HTML node. Will check it when I get off work.

Label: bug

**Comment by ccloli** [comment]
Should be fixed in v1.31.1, you can update the script manually in your userscript extension (GreaseMonkey, Tampermonkey, ViolentMonkey).
