### ISSUE TITLE
New site update seems to have broken the script

### ISSUE THREAD

**Issue by Hecatom** [ccloli/E-Hentai-Downloader#132]
Yesterday there was a new site update that seems that it has broken the script, since it no longer starts downloading the galleries.

**Comment by ccloli** [comment]
Is v1.31.3 still have the problem? If so, please press `F12` and switch to `Console` tab, and refresh the page, then click the download link. If the script gets some error, you can copy them from Console and paste them here. Thanks.

**Comment by serenad3x** [comment]
v1.31.3 worked perfectly for me. Manually updating it solved it.
