### ISSUE TITLE
点击后无法下载

### ISSUE THREAD

**Issue by Mackel123** [ccloli/E-Hentai-Downloader#134]
点击之后没有反应，并不能下载漫画

**Comment by ccloli** [comment]
请按下 F12，在开发工具中切换至 Console / 控制台，然后刷新页面并进行下载操作，如果出现无法下载的情况，请将控制台中所有以 `[EHD]` 开头的日志复制至此

**Comment by LiHua33** [comment]
-[EHD] UserAgent > Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
-[EHD] Script Handler > Tampermonkey
-[EHD] Script Handler Version > 4.8.41
-[EHD] E-Hentai Downloader Version > 1.31.3
-[EHD] Current URL > https://exhentai.org/g/1395518/4b234cdcc7/
-[EHD] Is Logged In > true
-[EHD] E-Hentai Downloader Setting > {"speed-detect":false,"number-images":false,"number-real-index":false,"number-auto-retry":true,"auto-download-cancel":true,"recheck-file-name":true,"ignore-torrent":true,"status-in-title":"always","hide-image-limits":true,"hide-estimated-cost":true,"file-descriptor":false,"force-resized":false,"never-new-url":false,"never-send-nl":false,"store-in-fs":false,"play-silent-music":false,"save-info":"file","save-info-list":["title","metas","uploader-comment","page-links"],"save-info-list[]":false,"replace-with-full-width":false,"force-pause":false,"save-as-cbz":false}
-Uncaught TypeError: Cannot read property 'split' of undefined
 at getFileSizeAndLength (userscript.html?id=1…-78eb1e6ad84c:14290)
 at initEHDownload (userscript.html?id=1…-78eb1e6ad84c:13657)
 at HTMLDivElement.eval (userscript.html?id=1…-78eb1e6ad84c:14390)

**Comment by ccloli** [comment]
此问题暂时无法复现，如果在同页面内亦加载了其他用户脚本，请尝试参考 https://github.com/ccloli/E-Hentai-Downloader/issues/50#issuecomment-254703671 调整脚本执行顺序，然后再次重试。如果还是存在问题，请提供在当前页面内还运行了哪些用户脚本以及相关的扩展程序

**Comment by LiHua33** [comment]
@ccloli 
问题已解决。
原因是同时运行了脚本[Ehentai翻译注入器]并先于本脚本运行，
现已通过调整脚本运行次序得到解决。

抱歉事先没看之前的issue。

**Comment by Mackel123** [comment]
非常感谢，周末我测试下是否还有这个问题，这几天比较繁忙

**Comment by Mackel123** [comment]
原因是e-hentai chinese function脚本冲突，这个启动他就不能在启动了，关闭就可以

是在google chrome 75.0.3770.27 (Official Build) beta (64-bit)

问题是tampermonkey不清楚怎么调整顺序

**Comment by ccloli** [comment]
> 问题是tampermonkey不清楚怎么调整顺序

请参考 https://github.com/ccloli/E-Hentai-Downloader/issues/50#issuecomment-254703671 的最后一张截图
