### ISSUE TITLE
The script is not downloading any image

### ISSUE THREAD

**Issue by Hecatom** [ccloli/E-Hentai-Downloader#136]
Hello, there seems to be  an issue with the script since some 12 hours ago, where it doesnt download any image and just keeps trying in a loop without getting an error.

It also doesnt seem to be unable to get the current status on the image limit.

At the beginning i thought it was because sadpanda was getting somne 503 errors and giving some back end errors, but now that everything seems normal again, i am not sure if they maybe made some changes that broke the script.

Also yesterday tamper monkey updated for me, so there is also that

https://i.imgur.com/3lFlfr5.png
https://i.imgur.com/ShiDWhS.png

**Comment by ccloli** [comment]
I downloaded some galleries 10 hours ago before you posting the issue, so I didn't see the bug. And I tested the gallery on your screenshot, and it works fine now.

I'm not sure if it's related to site error or network error, if you've any updates, please let me know.

BTW next time when you get the error, you can press F12 and switch to Console and try again, then copy the logs that prefixed with `[EHD]`.

![image](https://user-images.githubusercontent.com/8115912/57591006-c6da8d00-7561-11e9-880b-3df60bc39592.png)
