### ISSUE TITLE
Can't resume last file after reaching limit

### ISSUE THREAD

**Issue by knismaps** [ccloli/E-Hentai-Downloader#138]
I think if you hit the image limit on the last file of a gallery, continuing is broken.  If you wait and then hit "continue download," it doesn't actually try to download the last image (no lines at all show up in the console logs).  The buttons in the status window do change to the "pause" button, though.

Logs look like this:
```
... (bunch of files finish)
02:34:47.976 [EHD] Index > 23  | RealIndex > 23  | Name > 023.jpg  | RetryCount > 0  | DownloadedCount > 21  | FetchCount > 5  | FailedCount > 0
02:34:48.294 [EHD] #26: Exceed Image Viewing Limits / 509 Bandwidth Exceeded
02:34:48.294 [EHD] #26: RealIndex > 26  | ReadyState > 4  | Status > 200  | StatusText > OK
... (removed the request/header info for the failure)
02:34:52.495 [EHD] Index > 24  | RealIndex > 24  | Name > 024.jpg  | RetryCount > 0  | DownloadedCount > 22  | FetchCount > 4  | FailedCount > 1
... (the last few files finish)
02:40:12.569 [EHD] Request Image Limits From e-hentai.org
... (previous line repeats a lot while I wait)
```

Those logs include hitting the button to wait for my limit, then hitting continue.  And also pause/resume a few times.

**Comment by ccloli** [comment]
Thanks for your feedback, at this time you can try to click the download link at the top of the status box, it should give you a zip file with downloaded images, then download the failed images directly and move it into the zip file.
