### ISSUE TITLE
能不能单单将下载的图片提取出来，而不是进行压缩

### ISSUE THREAD

**Issue by dodying** [ccloli/E-Hentai-Downloader#14]
有时图片太多，下载完了就停在”Finish downloading at XXXX“
希望可以将图片提取到一个文件夹，然后文件夹里有图片+info+打包成压缩文件的批处理

**Comment by ccloli** [comment]
纯浏览器 JavaScript 环境不能做到写入本地磁盘的功能，所以无法直接写入一个文件夹。

如果是卡在“Finish downloading at”后就不再弹出下载窗口，多半是由于内存不足或者没有剩余的 Blob Storage 空间来创建新的 Blob 对象，导致无法继续操作。这一点暂时没有很好的解决办法，对于 Google Chrome 用户可以在设置中启用“Request File System to handle large Zip file”（请求 File System API 以存储较大的 Zip 文件），这样可以生成并存储较大的 Zip 文件，即便无法成功生成也会将已下载的文件存储在 File System 内，可以使用[特定的扩展程序](https://chrome.google.com/webstore/detail/nhnjmpbdkieehidddbaeajffijockaea)获取它们。不过很可惜，HTML5 草案已经移除了 File System API，所以 Firefox 等浏览器以后应该也不会支持它。

后期可能会考虑从 JSZip 过渡到 zip.js，不过目前没太大心思考虑。

**Comment by dodying** [comment]
额，好可惜
感谢作者大大的耐心回复

**Comment by ccloli** [comment]
如果图片太多的话可以考虑指定页码 (Pages Range) 来分成几个压缩包进行下载

**Comment by dodying** [comment]
嗯，现在基本这样下单行本
话说秒回，心情好激动

**Comment by ccloli** [comment]
GitHub 有邮件提醒，除非我当时比较忙（或者比较懒），基本上还是能马上看到的

**Comment by zzz6519003** [comment]
JSZip 过渡到 zip.js 有啥好处

**Comment by ccloli** [comment]
zip.js 性能要比 JSZip 好，而且使用官方的 demo 测试在 Firefox 内可以稳定压缩 1GB 内的文件，但是 zip.js 是各种回调，感觉以我的水平很容易出问题，之前支持 File System 时也是各种回调弄得够呛 = = JSZip 的性能虽然不及 zip.js，但是使用起来非常方便
