### ISSUE TITLE
The extension takes more image quotas than it should

### ISSUE THREAD

**Issue by Timurama** [ccloli/E-Hentai-Downloader#141]
I just downloaded a gallery consisting of 7 pic and in my account records tell that it was 13, almost twice as many, why's that?I thought it's because this thing pulls down 5 pictures at once, but I limited simultaneous image downloading to just one, and the issue is still present, do I do something in the setting or is it just how your program works, and can't function differently?

**Comment by knismaps** [comment]
An image can cost more than one point.

**Comment by ekhsannpanda** [comment]
even if its costs more than a point, i think taking 600 off my quota for downloading a gallery of 15 images is a serious concern

**Comment by ccloli** [comment]
For the rule of image limits, I've made a summary here: https://github.com/ccloli/E-Hentai-Downloader/wiki/E%E2%88%92Hentai-Image-Viewing-Limits

Or EHWiki: https://ehwiki.org/wiki/My_Home#Overview

In short, if you don't care about downloading original images, uncheck _Force download resized image (never download original image)_ at _Settings -> Advanced_.

**Comment by ccloli** [comment]
Just now I tested it again, seems that the image limits will be counted as 1 point per 0.1 MB (less than 0.1 MB will ALSO be counted), before that it's 1 point per 0.2 MB (less than 0.2 MB will NOT be counted).

For example, if an original image is 550 KB, it'll take 6 points now, before that it's 2 points (the extra 150 KB is not counted).

I've updated the wiki page, a newer version with new image limits rule will be released soon.

**Comment by ccloli** [comment]
v1.31.5 is released just now, using the new rule to estimate the cost of image limits, and it'll also count by your resolution setting at https://e-hentai.org/uconfig.php .

For example, this gallery https://e-hentai.org/g/1471479/f62faaddae/ has 32 pages and 203.5 MB in total. With default E-Hentai setting (load from Hentai@Home, 1280x) and default download script setting (download original images), the estimated cost is `2100` points now,but you can get original images, the zip file should be around 203.5 MB.

If you enabled _Force download resized image (never download original image)_ at _Settings_ -> _Advanced_, the estimated cost will be `32` points, but all the image you downloaded will be resized to 1280x, for my test the zip file is 11.2 MB. If you change your resolution setting, set it to 2400x, it'll be `160` points, and disable loading from H@H, it'll be `320` points.

**Comment by ccloli** [comment]
> 2019-08-22
> 
> - The "cost" for downloading the original image for a page with the "download original" link when the image limit reset function is used has been adjusted to match the cost of including it in an archive. This is because people were using scripts to download full galleries with this link instead of using the archivers, which causes a lot more strain on the servers.
>
> _-- Site Update Log, https://e-hentai.org/news.php_

So, if you don't care about the "original images", as I said, download the resized images. And if you really want to grab the "original images", use torrent first, and if it's a new gallery, the torrent speed should be more stable.
