### ISSUE TITLE
Small archives aren't saving correctly

### ISSUE THREAD

**Issue by HamSpam404** [ccloli/E-Hentai-Downloader#143]
I'm using Firefox with Greasemonkey. I've tried downloading multiple small galleries around 10 MB or less, and they all will not save correctly. It will download and cost image limits, but after saving to disk it outputs a 0 byte zip file.

**Comment by ccloli** [comment]
![image](https://user-images.githubusercontent.com/8115912/62426205-6dbf6700-b714-11e9-867e-d0881ab9969a.png)
![image](https://user-images.githubusercontent.com/8115912/62426231-8891db80-b714-11e9-9055-fc73c0f2b103.png)

**Comment by HamSpam404** [comment]
Oh... thank you very much. It must be a dumb Firefox quirk I guess.

**Comment by HamSpam404** [comment]
Also, for anyone else looking into this issue I just found out it can be permanently disabled in
Options > Privacy & Security > Security
Untick "Warn you about unwanted and uncommon software" and you won't have to manually to downloads and open it every time.
