### ISSUE TITLE
点击后无法下载

### ISSUE THREAD

**Issue by bcfdkl** [ccloli/E-Hentai-Downloader#144]
ccloli你好，不知道是不是里站复活后版本的原因，现在无法通过downloader进行下载。
点击download achieve 键会提示存在种子文件是否继续使用downloader,但是选择继续使用downloader时则没有反应，若资源无种子文件则点击无反应。根据网站之前的bug试过了，不是脚本先后顺序的问题。还请大佬帮帮忙，很感谢您的付出XD

**Comment by ccloli** [comment]
表站里站均测试正常，请按下 F12 切换至 Console，刷新然后再次执行下载，并将 `[EHD]` 开头的日志输出粘贴至此

**Comment by bcfdkl** [comment]
[EHD] E-Hentai Downloader is running.
userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:35 
[EHD] Bugs Report > https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback
userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:36 
[EHD] To report a bug, it's recommended to provide the logs started with "[EHD]", thanks. =w=
userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:12004 
[EHD] UserAgent > Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:12005 
[EHD] Script Handler > Tampermonkey
userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:12006 
[EHD] Script Handler Version > 4.8.41
userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:12007 
[EHD] E-Hentai Downloader Version > 1.27
userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:12008 
[EHD] E-Hentai Downloader Setting > {"save-info-list":["title","metas","uploader-comment","page-links"]}
userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:12009 
[EHD] Current URL > https://exhentai.org/g/1253726/611625ca66/
userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:12010 
[EHD] Is Logged In > true
userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:13718 
[EHD] Request Image Limits From e-hentai.org
userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:12107 Uncaught TypeError: Cannot read property 'getAttribute' of null
    at getReplacedName (userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:12107)
    at initEHDownload (userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:13163)
    at HTMLDivElement.eval (userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:13851)
getReplacedName @ userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:12107
initEHDownload @ userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:13163
(anonymous) @ userscript.html?id=3ac776fa-14dd-45e2-bba8-7a7cd83a1d25:13851

**Comment by ccloli** [comment]
> `E-Hentai Downloader Version > 1.27`

`1.27` 是一个两年前的版本，发布于 2017 年 8 月 14 日，目前最新版本为 `1.31.3`。请尝试在 Tampermonkey 中手动更新脚本，如果无法手动升级请尝试重新安装脚本，然后再确认是否还存在该问题

**Comment by bcfdkl** [comment]
问题已解决，原因是tampermonkey无法自动更新脚本，多谢ccloli
