### ISSUE TITLE
how to save Zip by different name

### ISSUE THREAD

**Issue by mochipon21** [ccloli/E-Hentai-Downloader#146]
question.

I want to save Zip that name Japanese, so I can get Japanese name value for "document.getElementById("gj").childNodes[0].nodeValue".
But I can't understand where I can change variable.
please tell me.

**Comment by ccloli** [comment]
You can do it by changing _Settings_ -> Basic -> _Set Zip file name as ..._ to `{subtitle}`.

Yes the field name is a bit confused, will add an alias `{title_jpn}` in next version.

**Comment by mochipon21** [comment]
I don't look settings,so I don't know what useful settings! thank you for telling.
