### ISSUE TITLE
Retry a download will request image URL again and cost more image limits on Tampermonkey

### ISSUE THREAD

**Issue by ccloli** [ccloli/E-Hentai-Downloader#147]
Since the image limit only cost when requesting image URL (see [wiki](https://github.com/ccloli/E-Hentai-Downloader/wiki/E%E2%88%92Hentai-Image-Viewing-Limits)), the script will use `finalUrl` field to get the real image URL which is provided by `GM_xmlHttpRequest`, this should save your image limits when re-downloading. 

However, in latest Tampermonkey, it only assigns `finalUrl` when the request is loaded, and before that the `finalUrl` is the request URL. That means when re-downloading, the script will request image URL again, and cost your image limits again.

![QQ截图20190907162225](https://user-images.githubusercontent.com/8115912/64472168-daeb6f80-d18c-11e9-8a41-5ed25d8ed1b2.png)

_The `finalUrl` is the requesting image URL when the file is not fully downloaded_

![QQ截图20190907162507](https://user-images.githubusercontent.com/8115912/64472177-04a49680-d18d-11e9-8493-68674ff434b8.png)

_The `finalUrl` only updates when the file is fully downloaded_

It works fine on GreaseMonkey, once GreaseMonkey get the headers of request, it updates `finalUrl`.

![QQ截图20190907162030](https://user-images.githubusercontent.com/8115912/64472183-2867dc80-d18d-11e9-8f3a-44391f34e512.png)

Before Tampermonkey fix the bug, maybe we can extract the final URL from `tm-finalurlgcal` header.

![QQ截图20190907162300](https://user-images.githubusercontent.com/8115912/64472192-55b48a80-d18d-11e9-89a8-cd341c8d623e.png)

For the script user, if you usually needs to restart a download (often request fails or needs to abort if speed is too low), it's better to use GreaseMonkey for now.

**Comment by derjanb** [comment]
> The finalUrl only updates when the file is fully downloaded

Will be fixed at the next BETA release. :)
