### ISSUE TITLE
exhentai issues

### ISSUE THREAD

**Issue by HyperScorpio** [ccloli/E-Hentai-Downloader#149]
I can´t even download only the pages i want it, not the images.
It will goes downloading the first page. 
I need help about Page Range.
How i need to download only page 40 to 48 and not 48 pictures?
Thanks.

**Comment by ccloli** [comment]
If you mean the 40<sup>th</sup>-48<sup>th</sup> images, you can set _Pages Range_ as `40-48`.

If you mean all the images on page 40-48 of the gallery view, you can switch to page 40 and page 48, got the first image number `x` and the last image number `y`, then set _Pages Range_ as `x-y`.

**Comment by HyperScorpio** [comment]
Maybe because i put -40, 48 and it doesn´t work, if i put as you said 40-48 it will works. I will check it soon.

**Comment by HyperScorpio** [comment]
Okay i got it, if i put the number of images it will work good. So i download 1-1000 and then tomorow i will go 1000-2000 and so on... Thank you!

**Comment by ccloli** [comment]
...unless you used up your image limits. Take a look at https://e-hentai.org/home.php to check out your current image limit usage, normally download an image will cost around `10 * file_size_in_MB +1`, you can get estimated cost at the top of the download box.
