### ISSUE TITLE
能不能弄个在其他网站搜索相同本子的脚本

### ISSUE THREAD

**Issue by dodying** [ccloli/E-Hentai-Downloader#15]
我一般都会先收藏一大堆，在之后找个时间下载
但是E-Hentai有时会删资源，那么只好去其他绅士网站找资源，比如这个：hitomi.la
能不能在Favorites的界面每一本本子那里弄个按钮，快速的在其他绅士站搜索，或是用google搜索本子封面

**Comment by ccloli** [comment]
这不是脚本的核心功能，所以不会考虑。
