### ISSUE TITLE
Failed! (Wrong MIME)

### ISSUE THREAD

**Issue by kanachi00** [ccloli/E-Hentai-Downloader#154]
when I try to download images it keeps giving this problem , it's not on all images it seems..
![ScreenShot_20200302165615](https://user-images.githubusercontent.com/48189939/75693194-e84e6600-5ca6-11ea-9d2c-cd311fc1e131.png)

**Comment by ccloli** [comment]
See #153 for detail.

TL;DR: Update to v1.31.6.
