### ISSUE TITLE
下载完成后，压缩包内文件损坏，大小只有1KB

### ISSUE THREAD

**Issue by zhx79513** [ccloli/E-Hentai-Downloader#158]
下载完成后，压缩包内的文件有些只有1KB，而且打开后显示已损坏。
---
![图片](https://user-images.githubusercontent.com/5063357/79778140-de71e680-836a-11ea-8ef1-765827fa1acd.png)
---
### 操作系统：
Win10 1909 企业版 64位
### 浏览器：
Firefox 75.0 64位
### 插件：
Tampermonkey 4.10.6112
### 脚本版本：
1.31.8

**Comment by ccloli** [comment]
Hi，可否上传一个 1KB 的文件副本？有可能是服务器或代理服务器返回了非预期的内容

**Comment by zhx79513** [comment]
> 
> 
> Hi，可否上传一个 1KB 的文件副本？有可能是服务器或代理服务器返回了非预期的内容

---
[错误文件.zip](https://github.com/ccloli/E-Hentai-Downloader/files/4505971/default.zip)

**Comment by ccloli** [comment]
> The file does not exit on this server, but has been requested to download. 有点迷惑，看起来是文件不存在，晚上再排查下------------------ Original ------------------

**Comment by ccloli** [comment]
已尝试在 v1.31.9 中修复，错误地在内层的 `return` 后外层接 `else if` 导致这种特殊情况没走后面的判断
