### ISSUE TITLE
Any change this week? also wrong mime

### ISSUE THREAD

**Issue by Hyoros** [ccloli/E-Hentai-Downloader#159]
I’ve been using you script for a over 3 years to download galleries in 980/780p and sometimes modify things inside it. I usually encounter more image downloading error in when going for 980p and 1280p than 720p but nothing major. This month I start getting wrong MIME error for 2-4 pictures, still nothing big. Yesterday night I still can download a gallery without hitch in 780p.  I wanted to download in full resolution by unchecking the Force box, then 2 things happened (I don’t remember which one happen first)
1. the check mark on Force Download Original option won’t disappear even after save and refresh. I don’t know why so I try change 	sup>(2)</sup> in line 14158 into sup>(1)</sup> because that is the only difference I could find. It didn’t work and the check box change sill revert to normal after unchecking, save and refresh. But I don’t believe this is the culprit.
2. I get MIME error for everything. In any resolution. 
For this MIME error I found https://github.com/ccloli/E-Hentai-Downloader/issues/104
You suspected that “user cookie is not sync”. I don’t believe this is not a problem since I don’t change my cookie setting for a while and this only happen yesterday. And I don't want to risk clearing up e-h cookies (but console check do return my UID).

So now I check back the script main page, which states this need GreaseMonkey 3.2*. I’m using 3. 1 all the time. Before attempting that, I backup the modified script , install the most recent version of E-Hentai-Downloader then everything works. Force Download box behave normally, no more MIME error in any resolution or native image resolution. Then just to make sure, I uninstall your new script again, reinstall my backup and the problem is back. 
So I conclude it is easier if I just apply my edit to your recent one. Which bring us back  to my first question: do you make any change this week that might cause this? I can provide Console  log if you are curious

:* in the script you mention "GreaseMonkey 3.2 beta 1 and older version can't load content of GM_xhr.response". When did GM 3.2 was released?

I don't know which version of your script that I used as base, I think I deleted the version number. Additional question: Will this script if I can't access E-H? I only use computer to browse EX/EH. My government block EH but not EX. I use proxy to visit E-H but this proxy doesn't work if I use my phone internet as modem (which I use yesterday when Image Resize problem started).

**Comment by ccloli** [comment]
Which version are you using? I pinned some issues that related to `Wrong MIME` (#153, #154, #155), which related to 2 reasons. #153 and #154 are due to E-Hentai's server update that returns incorrect `Content-Type` header (maybe on 1 Mar, you can check it on E-Hentai News page). Thought it's not a bug of script properly, a specific "bugfix" (v1.31.6) is released on 2 Mar. #155 is related to suspended account, if your account is banned, it may shows `Wrong MIME`. To make it clear, v1.31.7 adds a new status `Suspended` which released on 11 Mar. Which version are you using? Is your account blocked? A log would helps me to find the problem. If you've modified the script, you may need some diff tools to compare changes. ------------------ Original ------------------

**Comment by ccloli** [comment]
> the check mark on Force Download Original option won’t disappear even after save and refresh.

Did you mean "Force download resized images"? If yes it should be a bug, will check it later this day.

> Will this script if I can't access E-H?

Nope, the script needs a mostly stable connection to E-Hentai and most of H@H nodes.

**Comment by Hyoros** [comment]
Thank you for quick response. Making some log files now., this will take a while.
And that Force download resized only apply to my modified version. No problem with the latest

**Comment by Hyoros** [comment]
* recent script, untouched
eh-search-multiple is active eh-search-multiple.user.js:221:1
[EHD] E-Hentai Downloader is running. e-hentai-downloader.user.js:34:1
[EHD] Bugs Report > "https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback" e-hentai-downloader.user.js:35:1
[EHD] To report a bug, it's recommended to provide the logs started with "[EHD]", thanks. =w= e-hentai-downloader.user.js:36:1
[EHD] UserAgent > Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0 e-hentai-downloader.user.js:12304:1
[EHD] Script Handler > GreaseMonkey e-hentai-downloader.user.js:12305:1
[EHD] Script Handler Version > 3.11 e-hentai-downloader.user.js:12306:1
[EHD] E-Hentai Downloader Version > 1.31.9 e-hentai-downloader.user.js:12307:1
[EHD] Current URL > "https://e-hentai.org/g/1489090/03607b2909/" e-hentai-downloader.user.js:12308:1
[EHD] Is Logged In > true e-hentai-downloader.user.js:12309:1
[EHD] E-Hentai Downloader Setting > {"thread-count":4,"timeout":26,"speed-detect":false,"speed-min":30,"speed-expired":30,"retry-count":2,"number-images":true,"number-real-index":true,"number-auto-retry":false,"auto-download-cancel":true,"dir-name":"/","file-name":"{gid}","recheck-file-name":false,"ignore-torrent":true,"status-in-title":"always","hide-image-limits":false,"hide-estimated-cost":false,"file-descriptor":false,"force-resized":false,"never-new-url":false,"store-in-fs":false,"play-silent-music":false,"save-info":"none","save-info-list":["title","metas","uploader-comment","page-links"],"save-info-list[]":false,"replace-with-full-width":false,"force-pause":false} e-hentai-downloader.user.js:12270:1
[EHD] Request Resolution Setting e-hentai-downloader.user.js:14417:2
[EHD] Request Image Limits From e-hentai.org e-hentai-downloader.user.js:14307:2
[EHD] Resolution Setting > {"withoutHentaiAtHome":0,"resolution":1,"timestamp":1587882666847} e-hentai-downloader.user.js:14427:1
[EHD] Index > 4  | RealIndex > 4  | Name > 75067257_p3_.jpg  | RetryCount > 0  | DownloadedCount > 1  | FetchCount > 4  | FailedCount > 0 e-hentai-downloader.user.js:12439:2
[EHD] Index > 2  | RealIndex > 2  | Name > 75067257_p1_.jpg  | RetryCount > 0  | DownloadedCount > 2  | FetchCount > 3  | FailedCount > 0 e-hentai-downloader.user.js:12439:2
[EHD] Index > 1  | RealIndex > 1  | Name > 75067257_p0_.jpg  | RetryCount > 0  | DownloadedCount > 3  | FetchCount > 2  | FailedCount > 0 e-hentai-downloader.user.js:12439:2
[EHD] Index > 3  | RealIndex > 3  | Name > 75067257_p2_.jpg  | RetryCount > 0  | DownloadedCount > 4  | FetchCount > 1  | FailedCount > 0 e-hentai-downloader.user.js:12439:2
[EHD] Request Image Limits From e-hentai.org e-hentai-downloader.user.js:14307:2
* recent script, Force download resized checked 
eh-search-multiple is active eh-search-multiple.user.js:221:1
[EHD] E-Hentai Downloader is running. e-hentai-downloader.user.js:34:1
[EHD] Bugs Report > "https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback" e-hentai-downloader.user.js:35:1
[EHD] To report a bug, it's recommended to provide the logs started with "[EHD]", thanks. =w= e-hentai-downloader.user.js:36:1
[EHD] UserAgent > Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0 e-hentai-downloader.user.js:12304:1
[EHD] Script Handler > GreaseMonkey e-hentai-downloader.user.js:12305:1
[EHD] Script Handler Version > 3.11 e-hentai-downloader.user.js:12306:1
[EHD] E-Hentai Downloader Version > 1.31.9 e-hentai-downloader.user.js:12307:1
[EHD] Current URL > "https://e-hentai.org/g/1489090/03607b2909/" e-hentai-downloader.user.js:12308:1
[EHD] Is Logged In > true e-hentai-downloader.user.js:12309:1
[EHD] E-Hentai Downloader Setting > {"thread-count":4,"timeout":26,"speed-detect":false,"speed-min":30,"speed-expired":30,"retry-count":2,"number-images":true,"number-real-index":true,"number-auto-retry":false,"auto-download-cancel":true,"dir-name":"/","file-name":"{gid}","recheck-file-name":false,"ignore-torrent":true,"status-in-title":"always","hide-image-limits":false,"hide-estimated-cost":false,"file-descriptor":false,"force-resized":true,"never-new-url":false,"never-send-nl":false,"store-in-fs":false,"play-silent-music":false,"save-info":"none","save-info-list":["title","metas","uploader-comment","page-links"],"save-info-list[]":false,"replace-with-full-width":false,"force-pause":false,"save-as-cbz":false} e-hentai-downloader.user.js:12270:1
[EHD] Request Resolution Setting e-hentai-downloader.user.js:14417:2
[EHD] Request Image Limits From e-hentai.org e-hentai-downloader.user.js:14307:2
[EHD] Resolution Setting > {"withoutHentaiAtHome":0,"resolution":1,"timestamp":1587882923359} e-hentai-downloader.user.js:14427:1
[EHD] Index > 3  | RealIndex > 3  | Name > 75067257_p2_.jpg  | RetryCount > 0  | DownloadedCount > 1  | FetchCount > 4  | FailedCount > 0 e-hentai-downloader.user.js:12439:2
[EHD] Index > 2  | RealIndex > 2  | Name > 75067257_p1_.jpg  | RetryCount > 0  | DownloadedCount > 2  | FetchCount > 3  | FailedCount > 0 e-hentai-downloader.user.js:12439:2
[EHD] Index > 1  | RealIndex > 1  | Name > 75067257_p0_.jpg  | RetryCount > 0  | DownloadedCount > 3  | FetchCount > 2  | FailedCount > 0 e-hentai-downloader.user.js:12439:2
[EHD] Index > 4  | RealIndex > 4  | Name > 75067257_p3_.jpg  | RetryCount > 0  | DownloadedCount > 4  | FetchCount > 1  | FailedCount > 0 e-hentai-downloader.user.js:12439:2
[EHD] Request Image Limits From e-hentai.org e-hentai-downloader.user.js:14307:2

**Comment by Hyoros** [comment]
Who there is lots of line
* modified script, “Force download resized” checked
https://pastebin.com/ZE7qCmnk

**Comment by Hyoros** [comment]
* modified script, attempting to uncheck “Force download resized” box,  saved result and the check mark is back
eh-search-multiple is active eh-search-multiple.user.js:221:1
[EHD] E-Hentai Downloader is running. e-hentai-downloader.user.js:40:1
[EHD] Bugs Report > "https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback" e-hentai-downloader.user.js:41:1
[EHD] To report a bug, it's recommended to provide the logs started with "[EHD]", thanks. =w= e-hentai-downloader.user.js:42:1
[EHD] UserAgent > Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0 e-hentai-downloader.user.js:12308:1
[EHD] Script Handler > GreaseMonkey e-hentai-downloader.user.js:12309:1
[EHD] Script Handler Version > 3.11 e-hentai-downloader.user.js:12310:1
[EHD] E-Hentai Downloader Version > 1 e-hentai-downloader.user.js:12311:1
[EHD] Current URL > "https://e-hentai.org/g/1489090/03607b2909/" e-hentai-downloader.user.js:12312:1
[EHD] Is Logged In > true e-hentai-downloader.user.js:12313:1
[EHD] E-Hentai Downloader Setting > {"save-info-list":["title","metas","uploader-comment","page-links"],"auto-download-cancel":true} e-hentai-downloader.user.js:12275:1
[EHD] Request Image Limits From e-hentai.org e-hentai-downloader.user.js:14254:2

**Comment by ccloli** [comment]
```
[EHD] Index > 1  | RealIndex > 1  | Name > 75067257_p0_.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 4  | FailedCount > 0 e-hentai-downloader.user.js:12711:2
[EHD] #1: Wrong Content-Type e-hentai-downloader.user.js:13224:6
[EHD] #1: RealIndex > 1  | ReadyState > 4  | Status > 200  | StatusText > OK
```

Well, your modified script doesn't print response header, which should be print and that helps debug. Here is the latest source code around that log outputs (formatted):

```js
console.log('[EHD] #' + (index + 1) + ': Wrong Content-Type');
console.log(
    '[EHD] #' + (index + 1) + ': RealIndex >', imageList[index]['realIndex'],
    ' | ReadyState >', res.readyState,
    ' | Status >', res.status,
    ' | StatusText >', res.statusText +
    '\nRequest URL >', requestURL,
    '\nFinal URL >', res.finalUrl,
    '\nResposeHeaders >' + res.responseHeaders
);
```

And I use `git blame` to track when I added this line and determine which version you're using, finally stopped at `v1.18.6` and cannot track anymore. So looks like you're using a very old version, which must be older than `v1.18.6` which released on 10 Dec 2015.

How many changes did you make? It may be a big tough to migrate the changes.

**Comment by ccloli** [comment]
Well... Looks like your GreaseMonkey doesn't print the next line, maybe needs some time to check which version you're using.

Anyway, if you modified your script before Mar 2020 and doesn't update it, it may related to #153. If you've made some changes, you need to find a most-like version, and use `git` or something else to migrate your changes.

**Comment by Hyoros** [comment]
>How many changes did you make? It may be a big tough to migrate the changes.
Just some text placeholder, colors and position of "Download Archive" box and "number images". Nothing big, I will just modify the latest version. Thank your for answering.

**Comment by Hyoros** [comment]
> ```
> [EHD] Index > 1  | RealIndex > 1  | Name > 75067257_p0_.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 4  | FailedCount > 0 e-hentai-downloader.user.js:12711:2
> [EHD] #1: Wrong Content-Type e-hentai-downloader.user.js:13224:6
> [EHD] #1: RealIndex > 1  | ReadyState > 4  | Status > 200  | StatusText > OK
> ```
> 
> Well, your modified script doesn't print response header, which should be print and that helps debug. Here is the latest source code around that log outputs (formatted):
> 
> ```js
> console.log('[EHD] #' + (index + 1) + ': Wrong Content-Type');
> console.log(
>     '[EHD] #' + (index + 1) + ': RealIndex >', imageList[index]['realIndex'],
>     ' | ReadyState >', res.readyState,
>     ' | Status >', res.status,
>     ' | StatusText >', res.statusText +
>     '\nRequest URL >', requestURL,
>     '\nFinal URL >', res.finalUrl,
>     '\nResposeHeaders >' + res.responseHeaders
> );
> ```
> 
> ~And I use `git blame` to track when I added this line and determine which version you're using, finally stopped at `v1.18.6` and cannot track anymore. So looks like you're using a very old version, which must be older than [`v1.18.4`](https://github.com/ccloli/E-Hentai-Downloader/commit/fdc70679f8c8cb3e981941fa8dab24d39d6119d2#diff-5f4b64ad9e9de6ad6996cc07b15c61daL10283) which released on 21 Oct 2015.~
> 
> Well... Looks like your GreaseMonkey doesn't print the next line, maybe needs some time to check which version you're using.
> 
> How many changes did you make? It may be a big tough to migrate the changes.

**Comment by Hyoros** [comment]
I just apply response header now
 ```
[EHD] E-Hentai   Downloader is running. e-hentai-downloader.user.js:40:1
--
[EHD] Bugs Report >   "https://github.com/ccloli/E-Hentai-Downloader/issues \|   https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback"   e-hentai-downloader.user.js:41:1
[EHD] To report a bug, it's recommended   to provide the logs started with "[EHD]", thanks. =w=   e-hentai-downloader.user.js:42:1
[EHD] UserAgent > Mozilla/5.0 (Windows   NT 10.0; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0   e-hentai-downloader.user.js:12308:1
[EHD] Script Handler > GreaseMonkey   e-hentai-downloader.user.js:12309:1
[EHD] Script Handler Version > 3.11   e-hentai-downloader.user.js:12310:1
[EHD] E-Hentai Downloader Version > 1   e-hentai-downloader.user.js:12311:1
[EHD] Current URL >   "https://e-hentai.org/g/1489090/03607b2909/"   e-hentai-downloader.user.js:12312:1
[EHD] Is Logged In > true   e-hentai-downloader.user.js:12313:1
[EHD] E-Hentai Downloader Setting >   {"thread-count":4,"timeout":26,"speed-detect":false,"speed-min":30,"speed-expired":30,"retry-count":2,"number-images":true,"number-real-index":true,"number-auto-retry":false,"auto-download-cancel":true,"dir-name":"/","file-name":"{gid}","recheck-file-name":false,"ignore-torrent":true,"status-in-title":"always","hide-image-limits":false,"hide-estimated-cost":false,"file-descriptor":false,"force-resized":false,"never-new-url":false,"store-in-fs":false,"play-silent-music":false,"save-info":"none","save-info-list":["title","metas","uploader-comment","page-links"],"save-info-list[]":false,"replace-with-full-width":false,"force-pause":false}   e-hentai-downloader.user.js:12275:1
[EHD] Request Image Limits From   e-hentai.org e-hentai-downloader.user.js:14254:2
[EHD] #4: Wrong Content-Type   e-hentai-downloader.user.js:13224:6
[EHD] #4: RealIndex > 4  \| ReadyState > 4  \| Status > 200  \| StatusText > OK
[EHD] Index > 4  \| RealIndex > 4  \| Name > 75067257_p3_.jpg  \| RetryCount > 0  \| DownloadedCount > 0  \| FetchCount > 4  \| FailedCount > 0   e-hentai-downloader.user.js:12711:2
[EHD] #4: Wrong Content-Type   e-hentai-downloader.user.js:13224:6
[EHD] #4: RealIndex > 4  \| ReadyState > 4  \| Status > 200  \| StatusText > OK
[EHD] Index > 4  \| RealIndex > 4  \| Name > 75067257_p3_.jpg  \| RetryCount > 1  \| DownloadedCount > 0  \| FetchCount > 4  \| FailedCount > 0   e-hentai-downloader.user.js:12711:2
 ``` 
Then this  Wrong Content-Type paragraph repeat again for each picture. Did I do this right?

**Comment by ccloli** [comment]
Well, if you just modified your old version, then no, maybe you should copy your changes to the latest version (you can use `git` to determine what has been changed). For example, you can `git clone` the repo and open the folder with Visual Studio Code, then open `e-hentai-dowloader.user.js` and select all, paste your modified version, save. Then you can see a helpful diff map that helps you to migrate.

If you still prefer to modified based on your modified version, make sure you've add [this change](https://github.com/ccloli/E-Hentai-Downloader/commit/9b80154a31c5e5aaa15bea7ac4eb5d7371b18516#diff-1c90ff38a08209f9ebd4d05d1e43358eR1230).

**Comment by Hyoros** [comment]
I will do the first suggestion. This might take few hours.

**Comment by ccloli** [comment]
Yeah, it may take some time to do it manually, here are some tips, HTH:

1. You need to download and install Git from https://git-scm.com , and VSCode from https://code.visualstudio.com/;

2. Run `git clone https://github.com/ccloli/E-Hentai-Downloader.git`, once it's done, you can see an `E-Hentai-Downloader` folder;

3. Open VSCode, and drag `E-Hentai-Downloader` folder on to the window;

4. Select `e-hentai-downloader.user.js` from the file list panel on the left;

5. Select all, paste your modified script, then save;

5. Switch to Git tab, if everything fines, you can see a modified file `e-hentai-downloader.user.js`, click the file name;

6. You'll see a diff map side-by-side, so that you can check what's change (left panel is the lastest version code, right panel is your modified code, red line means deleted, green line means added). You can copy the source code from left panel to right panel to update your version.  
    
    BTW you can safely copy the first ~12,000 lines from left to right (determine `var zip;` is on which line), those are just libraries.
    > Note: VSCode may format your source code, if you see A LOT changes before first ~12,000 lines are about coding style, the code might be formatted. You should click right panel, select all source code, paste your modified script again, and press `Ctrl + Z` to revert the prettify, then save, so that the first ~12,000 should be no changes or much lesser than before. If it's not working, open `e-hentai-downloader.user.js` with Notepad (`notepad.exe`), then select all, paste and save.
    
    ![image](https://user-images.githubusercontent.com/8115912/80303782-f28f6b00-87e4-11ea-9b9a-af448f00956f.png)

8. Once everything is done, type some commit message on the left top and click the mark (√) icon to commit your changes. Next time when a new version release, you can run `git pull` on that folder, git will automatic merge the changes (if you see `CONFLICT` message, open it with VSCode and solve them, save and commit for the next update).

**Comment by ccloli** [comment]
Well, VSCode has integrated Git, and it helps you to use Git easily, however you still needs to clone the repo with Git.

**Comment by Hyoros** [comment]
```
					<div class="g2"><label><input type="checkbox" checked data-ehd-setting="force-resized"> Force download resized image (never download original image) </label><sup>(2)</sup></div>\
```
Look that checked ? I believe I found our culprit. I hard put these checks into the script so I don't have to readjust if I need to move to another computer. Gonna have dinner now.

**Comment by ccloli** [comment]
Hmm, if you hard-encoded `checked` in template, then it's always be `checked`, since the script only set `checked` attribute if the option is enabled, but won't remove it if it's disabled. Also hard-encoded `checked` in template doesn't means the script will "read" it, so the value should still be `false` by default until once you save the setting (sorry the script doesn't have a default setting).

**Comment by Hyoros** [comment]
>so the value should still be false by default until once you save the setting (sorry the script doesn't have a default setting).
Oh.  Okay, I just need to remove these checked.
