### ISSUE TITLE
How to disable "This archive is too large" warning?

### ISSUE THREAD

**Issue by gin9980** [ccloli/E-Hentai-Downloader#162]
Got lots of RAM on Firefox, is there an option to disable this popup warning? When downloading many 300mb+ galleries especially anthologies, clicking the confirm button slows me down.

**Comment by ccloli** [comment]
There is a tricky way to disable it by enabling _Request File System to handle large Zip file_ on _Settings_ -> _Advanced_, though this feature won't work on Firefox, it'll hide the popup.

**Comment by gin9980** [comment]
Is there a work around for Firefox? Its the browser that I use mainly.

**Comment by ccloli** [comment]
As I said, enabling _Request File System to handle large Zip file_ on _Settings_ -> _Advanced_ will remove the popup, even on Firefox. The option is transparency (Firefox doesn't support File System), but it can be activated and you can enable it to disable the popup.

**Comment by gin9980** [comment]
thanks, didn't realize it was clickable while greyed out
