### ISSUE TITLE
Slow background archiving in Firefox

### ISSUE THREAD

**Issue by zatsuna** [ccloli/E-Hentai-Downloader#164]
After updating to 1.31.10 I've got a problem that I didn't have before. I open, let's say, 4 tabs and download 4 galleries simultaneously and all works fine until archiving process starts. Only the active tab compression makes notable progress. For the background tabs (those not currently being displayed on the screen) archiving takes forever. I need to click on each individual tab to make it active to speed up the process and get the zip file. 
If no tab with archiving going on is active, the CPU usage is close to none. 
I'm using the latest Firefox and Geasemonkey. 

I can confirm that falling back to 1.31.9 fixes the issue.

**Comment by ccloli** [comment]
v1.31.10 just updates its dependency JSZip to 3.5.0. The script works, but it's clear to see that the speed is reduced on Firefox. So a new version v1.31.11 is released, it's just revert what's change on v1.31.10, downgrade JSZip to 3.1.5.

**Comment by zatsuna** [comment]
Thank you very much. The script works perfectly again.
