### ISSUE TITLE
can't install script, "IDBDatabase.transaction: 'user-scripts' is not a known object store name"

### ISSUE THREAD

**Issue by gahara31** [ccloli/E-Hentai-Downloader#167]
hello, I can't install the script from github nor greasyfork. error message :
`IDBDatabase.transaction: 'user-scripts' is not a known object store name`

**Comment by ccloli** [comment]
Make sure you've installed one of these extensions first.

https://github.com/ccloli/E-Hentai-Downloader#required-environment

If you've installed one of these, it may be a bug of the extension, you may need to try another one.

**Comment by gahara31** [comment]
yeah, it seems to be a bug on the extension. It was greasemonkey, It used to run fine before I reinstalled my pc. tried on tamper monkey and it works.
