### ISSUE TITLE
有几个问题想询问您，具体展开表述

### ISSUE THREAD

**Issue by baibai92** [ccloli/E-Hentai-Downloader#176]
1.这个下载器是否会汉化（看不懂，英文不够好），我用chrome自带翻译会出现按钮点不动，翻译不通顺，表达不清
2.我看了readme.md，里面提到不会扣除积分，我没有e站账号，是否意味着我不需要登录就可以下载（未登录我试了下，跳出几个弹窗，并且下载的图片也很少）。或者不登录下载的是压缩图片。
3.倘若需要登录才能下载，是否会出一个不需要登录就能下载压缩图的功能，我打开画廊，一个一个右键图片另存为真麻烦

**Comment by ccloli** [comment]
1. 现阶段不会考虑 i18n，因为文本是硬编码的，不方便改造，所以现阶段不会处理，一般情况下默认足够使用，最多在设置里自定义 zip 文件名与目录名即可
2. 下载会扣除 image limits，默认账户目前是 5000，未登录账户的浏览限制不太清楚，因为 image limits 需要登录后才可见，具体情况可以参考下官方 wiki
3. 一般来说未登录账户可以浏览，所以可以下载缩放后的压缩图片，但是不能下载原始图片，所以你还需要在设置里勾选 _Advanced ->  Force download resized image (never download original image)_ 强制下载缩放后的图片

**Comment by baibai92** [comment]
1.好的，我只是想知道每个设置所代表的功能，因为翻译表达不清，readme.md中又没有详细说明，导致我自己设置困难。如果大大能给出一份详细设置说明，汉不汉化都无所谓
2.未登录能下载压缩图就行。不追求画质极限

**Comment by ccloli** [comment]
1. 汉化的话之前有同学提交过 PR，可以参考 https://github.com/ccloli/E-Hentai-Downloader/pull/157/commits/4c128a8f12dc3606a6f530390bd868153ff98764 这里的 diff 对照配置设置项
2. 未登录理论上可以下载，不过由于未登录会有不少受限，所以可能会有非预期的问题
