### ISSUE TITLE
在exhentai上，即使已经登录也会显示未登录

### ISSUE THREAD

**Issue by nukewarrior** [ccloli/E-Hentai-Downloader#181]
![image](https://user-images.githubusercontent.com/10683831/103418588-52d37980-4bca-11eb-8a60-f1aa85b6d29d.png)

**Comment by ccloli** [comment]
登录检测是基于页面里提供的 `apiuid` 来检测的，如果页面返回的 `apiuid` 为 `-1` 则视为未登录，并限制为只能下载压缩后的图片，这种情况多半可以靠重新登录刷新 cookie 来解决。

如果不方便重新登录，可以按下 F12，然后选择 Application，并在左侧选择 Cookies，找到所属域名，理论上应该会有一个字段叫 `ipb_member_id`，右键删除后刷新页面（以防登录失败可以将字段和值记录下来或借助  EditThisCookie 等扩展备份 Cookie，在失败后可以重新填入该 Cookie 恢复之前状态），此时应该会刷新出新的 Cookie，并解决该问题。

![image](https://user-images.githubusercontent.com/8115912/103422881-a223a500-4bde-11eb-9b2d-62cb652e17ba.png)

如果仍存在问题，请考虑删除所有 Cookie 然后重新登录 e-hentai.org。

**Comment by ccloli** [comment]
v1.33 在设置里增加了一个选项来强制设置为已登录状态，可以在 _Settings_ -> _Advanced_ -> _Force as logged in_ 开启，同时可以在这里看到脚本当前获取到的登录状态。

![image](https://user-images.githubusercontent.com/8115912/104108049-6a161380-52fc-11eb-872c-3b8a57af402e.png)

**Comment by nukewarrior** [comment]
> 登录状态是基于页面里提供的 `apiuid` 来检测的，如果页面返回的 `apiuid` 为 `-1` 则视为未登录，并限制为只能下载压缩后的图片，这种情况多半可以靠重新登录刷新 cookie 来解决。
> 
> 如果不方便重新登录，可以按下 F12，然后选择 Application，并在左侧选择 Cookies，找到所属域名，理论上应该会有一个字段叫 `ipb_member_id`，右键删除后刷新页面（以防登录失败可以将字段和值记录下来或借助 EditThisCookie 等扩展备份 Cookie，在失败后可以重新填入该 Cookie 恢复之前状态），此时应该会刷新出新的 Cookie，并解决该问题。
> 
> ![image](https://user-images.githubusercontent.com/8115912/103422881-a223a500-4bde-11eb-9b2d-62cb652e17ba.png)
> 
> 如果仍存在问题，请考虑删除所有 Cookie 然后重新登录 e-hentai.org。

尝试使用这个方法，脚本的登录状态正常了，谢谢🙏
