### ISSUE TITLE
我今天試用暴力猴(violentmonkey) 但是好像沒正常運作

### ISSUE THREAD

**Issue by cmcmcmcm2** [ccloli/E-Hentai-Downloader#183]
我確定腳本有啟動 只是tampermonkey按下載會正常出現右下進度條
但是換暴力猴按下載都沒動靜  不知道是我的設定有問題還是是暴力猴的問題 (皆用最新stable版本)

**Comment by ccloli** [comment]
已測試在最新版本的 Chrome + Violentmonkey 下均無問題，請考慮在下載頁面按下 F12，然後切換至 Console / 控制台 標籤頁，刷新頁面後再點擊下載，然後將 `[EHD]` 開頭的全部日誌複製粘貼至此。

粘貼日誌時，建議在文本開頭與文本末尾加上三個反引號（```）並換行，以確保文字格式正確。

**Comment by cmcmcmcm2** [comment]
"""
E-Hentai Downloader.user.js:37 [EHD] E-Hentai Downloader is running.
E-Hentai Downloader.user.js:38 [EHD] Bugs Report > https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback
E-Hentai Downloader.user.js:39 [EHD] To report a bug, it's recommended to provide the logs started with "[EHD]", thanks. =w=
E-Hentai Downloader.user.js:12315 [EHD] UserAgent > Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
E-Hentai Downloader.user.js:12316 [EHD] Script Handler > Violentmonkey
E-Hentai Downloader.user.js:12317 [EHD] Script Handler Version > 2.12.9
E-Hentai Downloader.user.js:12318 [EHD] E-Hentai Downloader Version > 1.33.1
E-Hentai Downloader.user.js:12319 [EHD] Current URL > https://exhentai.org/g/1852279/025550d629/
E-Hentai Downloader.user.js:12320 [EHD] Is Logged In > true
E-Hentai Downloader.user.js:12281 [EHD] E-Hentai Downloader Setting > {"thread-count":5,"speed-detect":false,"delay-request":1,"number-images":false,"number-real-index":false,"number-auto-retry":false,"auto-download-cancel":true,"recheck-file-name":false,"ignore-torrent":false,"status-in-title":"never","hide-image-limits":false,"hide-estimated-cost":false,"file-descriptor":false,"force-resized":false,"never-new-url":false,"never-send-nl":false,"never-warn-large-gallery":false,"store-in-fs":false,"play-silent-music":false,"save-info":"file","save-info-list":["title","metas","uploader-comment","page-links"],"save-info-list[]":false,"replace-with-full-width":false,"force-pause":false,"save-as-cbz":false,"pass-cookies":false,"force-as-login":false}
E-Hentai Downloader.user.js:14533 [EHD] Request Resolution Setting
E-Hentai Downloader.user.js:14422 [EHD] Request Image Limits From e-hentai.org
E-Hentai E紳士中文版.user.js:3 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "blob:https://exhentai.org/0e175d77-8371-4020-8075-37b009787b9a".
(anonymous) @ E-Hentai E紳士中文版.user.js:3
Ha @ E-Hentai E紳士中文版.user.js:3
append @ E-Hentai E紳士中文版.user.js:3
(anonymous) @ E-Hentai E紳士中文版.user.js:4835
(anonymous) @ E-Hentai E紳士中文版.user.js:4921
window.VMin10r1y27kv6fg3r1 @ E-Hentai E紳士中文版.user.js:4921
b @ injected-web.js:1
set @ injected-web.js:1
(anonymous) @ E-Hentai E紳士中文版.user.js:1
m @ VM43 injected.js:1
h @ VM43 injected.js:1
(anonymous) @ VM43 injected.js:1
(anonymous) @ VM43 injected.js:1
b @ VM43 injected.js:1
(anonymous) @ VM43 injected.js:1
b @ VM43 injected.js:1
j @ VM43 injected.js:1
m.<computed>.ids.length.l.addEventListener.once @ VM43 injected.js:1
async function (async)
m.<computed>.ids.length.l.addEventListener.once @ VM43 injected.js:1
E-Hentai Downloader.user.js:14544 [EHD] Resolution Setting > {"withoutHentaiAtHome":0,"resolution":0,"timestamp":1613824616735}
E-Hentai Downloader.user.js:14464 Uncaught TypeError: Cannot read property 'split' of undefined
    at getFileSizeAndLength (E-Hentai Downloader.user.js:14464)
    at initEHDownload (E-Hentai Downloader.user.js:13810)
    at HTMLDivElement.<anonymous> (E-Hentai Downloader.user.js:14610)
getFileSizeAndLength @ E-Hentai Downloader.user.js:14464
initEHDownload @ E-Hentai Downloader.user.js:13810
(anonymous) @ E-Hentai Downloader.user.js:14610
"""

**Comment by cmcmcmcm2** [comment]
紅色警告的是最下面這部份
"""
Uncaught TypeError: Cannot read property 'split' of undefined
    at getFileSizeAndLength (E-Hentai Downloader.user.js:14464)
    at initEHDownload (E-Hentai Downloader.user.js:13810)
    at HTMLDivElement.<anonymous> (E-Hentai Downloader.user.js:14610)
getFileSizeAndLength @ E-Hentai Downloader.user.js:14464
initEHDownload @ E-Hentai Downloader.user.js:13810
(anonymous) @ E-Hentai Downloader.user.js:14610
"""

**Comment by ccloli** [comment]
> ```
> E-Hentai Downloader.user.js:14464 Uncaught TypeError: Cannot read property 'split' of undefined
>     at getFileSizeAndLength (E-Hentai Downloader.user.js:14464)
>     at initEHDownload (E-Hentai Downloader.user.js:13810)
>     at HTMLDivElement.<anonymous> (E-Hentai Downloader.user.js:14610)
> getFileSizeAndLength @ E-Hentai Downloader.user.js:14464
> ```

請確認是否安裝了諸如中文化翻譯的腳本，或其他可能會修改 EH 頁面的腳本，若有，請確保 E-Hentai Downloader 先於這些腳本運行，詳見 https://github.com/ccloli/E-Hentai-Downloader/issues/50#issuecomment-254703671 ；或在設置裏關閉扣除額度預估功能（Settings -> Basic -> Disable pre-calculating image limits cost）

**Comment by cmcmcmcm2** [comment]
確實取消中文化 暴力猴就可以了 不過油猴(也是兩者同時啟用)沒遇到這問題
所以應該是暴力猴本身的問題?

**Comment by ccloli** [comment]
應該不是，如前所述，只需要確保下載腳本先於其他腳本運行即可

**Comment by cmcmcmcm2** [comment]
我不會更改順序XD 我看我還是滾回油猴好了 ww 感謝解惑
