### ISSUE TITLE
离开页面之后下载速度骤降

### ISSUE THREAD

**Issue by ILOVEYUI** [ccloli/E-Hentai-Downloader#184]
在下载的那个漫画的页面的时候可以正常下载
但是离开页面之后下载速度会下降
测试同样时间内下载速度下降10倍（？）
一本四十页的本子大概下两分钟左右
同一本本子点击下载然后离开页面两分钟后回来只下载到第五六页
不知道是什么问题

**Comment by ccloli** [comment]
See #65 .

> ...... you can try enabling playing silent audio to prevent Chrome's optimization. To enable it , check out **Settings** -> **Advanced** -> **Play silent music during the process to avoid downloading freeze**.

**Comment by ILOVEYUI** [comment]
感谢，可以解决问题
