### ISSUE TITLE
E-Hentai-Downloader failling and filling up my image limit

### ISSUE THREAD

**Issue by nocoel** [ccloli/E-Hentai-Downloader#193]
hello,
i've been using the downloader for a while now and it's been working perfectly, and i thank you for it!!
today i tried using it on a folder that costs 2000 limits (i had 0/5000) so as i started he downloaded a couple (i have it so it downloads 3 images at a time) then failed the rest, once the 2 previous ones fished he downloaded another 2 and failed the rest of it, in the end he took 4 images out of 28. and the most weird part he maxed up my limit to 5008/5000...

i tried again by paying 10k credits to reset my limit, and on my second attempt he failed everything and maxed me again to the same value 5008/5000, keep in mind that i'm trying to download a 2000 worth of images

did it get blocked or something? or did it break for everyone

sorry for the long text!

**Comment by nocoel** [comment]
nvm this...
i tried again the next day and it worked fine, i wonder what went wrong yesterday

**Comment by ccloli** [comment]
Hi, sorry for the late reply.

I tested just now, seems that there might be a bug on Tampermonkey that the extension doesn't returns the final redirected URL when it fails to download, which costs you more limits than normal.

As the [wiki](https://github.com/ccloli/E-Hentai-Downloader/wiki/E%E2%88%92Hentai-Image-Viewing-Limits) notes, when downloading the original image, the download link is a redirect link which redirects to the image, and E-Hentai counts your viewing limits when you access that redirect link.

So if the extension works fine, it'll return the final image URL, and when the script download failed, the script will use that final image URL to retry, and your viewing limits won't be costed again. 

However the extension doesn't return the final image URL, so the script has to retry the redirect link, which takes your viewing limits again or multiple times.

**Comment by nocoel** [comment]
oh i understand, that makes sense
