### ISSUE TITLE
下載圖檔 檔案名稱問題

### ISSUE THREAD

**Issue by jer170g** [ccloli/E-Hentai-Downloader#20]
我現在下載的圖檔名稱都變成001：undefined、002：undefined等，我是哪邊設置錯誤？

**Comment by iShyboy** [comment]
Which gallery you're having this problem? All of them?

**Comment by ccloli** [comment]
bug 已確認，請等待修復，在此期間請先不要勾選 _Number Images_ 下載，很抱歉帶來了困擾。
