### ISSUE TITLE
Downloads start then never complete

### ISSUE THREAD

**Issue by boogiepop** [ccloli/E-Hentai-Downloader#200]
Downloads start then never complete, but get stuck at 0 kB/s. I have made a small clip of the issue, way easier for me than trying to explain. I hope that's ok.

https://streamable.com/xvszhy

Tampermonkey 4.13.6136 on Firefox 93.

**Comment by ccloli** [comment]
Tested on Tampermonkey 4.13.6136 with Firefox 96.0a1 and it works fine. Please consider providing the error log, by pressing F12 and switch to _Console_ tab, refresh the page and start downloading, then copy all the logs here.

**Comment by boogiepop** [comment]
`
Uncaught DOMException: Node.removeChild: The node to be removed is not a child of this node E-Hentai Downloader.user.js:14758
content: normal start event processing for 0ca54507-acdf-4396-aadb-8b451c179b39 (3 to run) content.js:117:29
content: Start ENV normally 0ca54507-acdf-4396-aadb-8b451c179b39 content.js:98:268
env: initialized (content, id:0ca54507-a..., https://exhentai.org/g/2053402/3c0b2b6af1/) eval line 2 > Function:9:10
Tampermonkey started eval line 2 > Function:70:408
env: schedule "Sadpanda torrent inline" for document-idle eval line 2 > Function:8:259
env: run "Mayriad's EH Master Script" ASAP -> document-start eval line 2 > Function:7:294
env: execute script Mayriad's EH Master Script @ the safe context now! eval line 2 > Function:64:290
env: schedule "E-Hentai Downloader" for document-idle eval line 2 > Function:8:259
content: detected DOMContentLoaded 0ca54507-acdf-4396-aadb-8b451c179b39 content.js:95:255
env: execute script Sadpanda torrent inline @ the unsafe context now! eval line 2 > Function:64:290
env: execute script E-Hentai Downloader @ the safe context now! eval line 2 > Function:64:290
[EHD] E-Hentai Downloader is running. E-Hentai Downloader.user.js:39:9
[EHD] Bugs Report > https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback E-Hentai Downloader.user.js:40:9
[EHD] To report a bug, it's recommended to provide the logs started with "[EHD]", thanks. =w= E-Hentai Downloader.user.js:41:9
[EHD] UserAgent > Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0 E-Hentai Downloader.user.js:12320:9
[EHD] Script Handler > Tampermonkey E-Hentai Downloader.user.js:12321:9
[EHD] Script Handler Version > 4.13.6136 E-Hentai Downloader.user.js:12322:9
[EHD] E-Hentai Downloader Version > 1.33.3 E-Hentai Downloader.user.js:12323:9
[EHD] Current URL > https://exhentai.org/g/2053402/3c0b2b6af1/ E-Hentai Downloader.user.js:12324:9
[EHD] Is Logged In > true E-Hentai Downloader.user.js:12325:9
[EHD] E-Hentai Downloader Setting > {"timeout":0,"speed-detect":false,"number-images":false,"number-real-index":false,"number-auto-retry":true,"auto-download-cancel":true,"file-name":"{title}","recheck-file-name":false,"ignore-torrent":true,"status-in-title":"never","hide-image-limits":false,"hide-estimated-cost":false,"file-descriptor":false,"force-resized":false,"never-new-url":false,"never-send-nl":false,"never-warn-large-gallery":true,"store-in-fs":false,"play-silent-music":true,"save-info":"none","save-info-list":["title","metas","uploader-comment","page-links"],"save-info-list[]":false,"replace-with-full-width":false,"force-pause":false,"save-as-cbz":false,"pass-cookies":false,"force-as-login":true} E-Hentai Downloader.user.js:12284:11
[EHD] Request Resolution Setting E-Hentai Downloader.user.js:14555:10
[EHD] Request Image Limits From e-hentai.org E-Hentai Downloader.user.js:14437:10
Some cookies are misusing the recommended “SameSite“ attribute 2
[EHD] Resolution Setting > {"withoutHentaiAtHome":0,"resolution":0,"timestamp":1636104919655} E-Hentai Downloader.user.js:14566:11
content: detected load 0ca54507-acdf-4396-aadb-8b451c179b39 content.js:95:401
TypeError: NetworkError when attempting to fetch resource.
    o moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:103
    n moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:103
    xhr moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:104
content.js:103:485
TypeError: NetworkError when attempting to fetch resource.
    o moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:103
    n moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:103
    xhr moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:104
content.js:103:485
TypeError: NetworkError when attempting to fetch resource.
    o moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:103
    n moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:103
    xhr moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:104
content.js:103:485
TypeError: NetworkError when attempting to fetch resource.
    o moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:103
    n moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:103
    xhr moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:104
content.js:103:485
TypeError: NetworkError when attempting to fetch resource.
    o moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:103
    n moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:103
    xhr moz-extension://374279f0-8b76-4b0c-9519-dd023188dd70/content.js:104
content.js:103:485

?

`

**Comment by ccloli** [comment]
Looks like it's similar to https://github.com/ccloli/E-Hentai-Downloader/issues/197#issuecomment-948446660, the error is thrown from Tampermonkey itself. Please also try pressing `Ctrl + Shift + J` to see if there is any logs outputed by the browser itself, and does it contains a message like `Security Error: Content at moz-extension://4d484a19-8947-472d-b940-85e506e3e999/ may not load data from blob:moz-extension://4d484a19-8947-472d-b940-85e506e3e999/21783c76-b2af-489d-85eb-778f8c52c236.`. 

Also as noted in https://github.com/ccloli/E-Hentai-Downloader/issues/197#issuecomment-948763735 , please try switching to ViolentMonkey, which is also a userscript extension, and see if it works for you.

**Comment by boogiepop** [comment]
I can confirm that switching to Violentmonkey fixed the problem.
