### ISSUE TITLE
E-Hentai Downloader无法下载

### ISSUE THREAD

**Issue by KINNAKAIHOU** [ccloli/E-Hentai-Downloader#202]
点击下载按钮无响应，而且文件名字即使设置成副标题，它也显示为空

**Comment by ccloli** [comment]
测试没有遇到问题，请在脚本运行时按下 F12 并切换至 Console / 控制台，然后将 [EHD] 开头的日志复制至此

另外如果使用了其他影响页面的脚本，如翻译脚本，请确保本脚本执行顺序在最先，详情参考 https://github.com/ccloli/E-Hentai-Downloader/issues/50#issuecomment-254703671

**Comment by KINNAKAIHOU** [comment]
[EHD] E-Hentai Downloader is running.
userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:40 [EHD] Bugs Report > https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback
userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:41 [EHD] To report a bug, it's recommended to provide the logs started with "[EHD]", thanks. =w=
userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:12320 [EHD] UserAgent > Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:12321 [EHD] Script Handler > Tampermonkey
userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:12322 [EHD] Script Handler Version > 4.14.6149
userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:12323 [EHD] E-Hentai Downloader Version > 1.33.4
userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:12324 [EHD] Current URL > https://exhentai.org/g/2085443/2c35d8f539/
userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:12325 [EHD] Is Logged In > true
userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:12284 [EHD] E-Hentai Downloader Setting > {"speed-detect":false,"number-images":true,"number-real-index":true,"number-auto-retry":true,"auto-download-cancel":true,"dir-name":"{subtitle}","file-name":"{subtitle}","recheck-file-name":true,"ignore-torrent":true,"status-in-title":"never","hide-image-limits":false,"hide-estimated-cost":false,"file-descriptor":false,"force-resized":true,"never-new-url":false,"never-send-nl":false,"never-warn-large-gallery":false,"store-in-fs":false,"play-silent-music":false,"save-info":"none","save-info-list":["title","metas","page-links"],"save-info-list[]":false,"replace-with-full-width":false,"force-pause":false,"save-as-cbz":false,"pass-cookies":false,"force-as-login":false}

我关闭了翻译插件EhSyringe，但还是无法下载

**Comment by KINNAKAIHOU** [comment]
而且点击下载会出现这个错误

userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:12418 Uncaught TypeError: str.replace(...).replace(...).replace(...).replace(...).replace(...).replace(...).replaceHTMLEntites is not a function
    at getReplacedName (userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:12418)
    at initEHDownload (userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:13799)
    at HTMLDivElement.eval (userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:14634)
getReplacedName @ userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:12418
initEHDownload @ userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:13799
eval @ userscript.html?name=E-Hentai%20Downloader.user.js&id=8456f8f1-120e-48ab-9a37-18bbce2541ae:14634

**Comment by ccloli** [comment]
已尝试过使用相同的设置下载相同的 gallery，暂时没复现问题。可否确认是否还有其他脚本或扩展正在运行？尝试禁用在 E-Hentai 上运行的其他脚本后再试试

**Comment by KINNAKAIHOU** [comment]
不行，我把chrome所有的插件都关闭了，油猴也只剩下E-Hentai Downloader，还是无法下载，并且有错
```
[EHD] E-Hentai Downloader is running.
userscript.html?name=E-Hentai%20Downloader.user.js&id=f8306c5c-21fc-4a52-b3e6-1287acb17cfd:40 
[EHD] Bugs Report > https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback
userscript.html?name=E-Hentai%20Downloader.user.js&id=f8306c5c-21fc-4a52-b3e6-1287acb17cfd:41 
[EHD] To report a bug, it's recommended to provide the logs started with "[EHD]", thanks. =w=
userscript.html?name=E-Hentai%20Downloader.user.js&id=f8306c5c-21fc-4a52-b3e6-1287acb17cfd:12320 
[EHD] UserAgent > Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
userscript.html?name=E-Hentai%20Downloader.user.js&id=f8306c5c-21fc-4a52-b3e6-1287acb17cfd:12321 
[EHD] Script Handler > Tampermonkey
userscript.html?name=E-Hentai%20Downloader.user.js&id=f8306c5c-21fc-4a52-b3e6-1287acb17cfd:12322 
[EHD] Script Handler Version > 4.14.6149
userscript.html?name=E-Hentai%20Downloader.user.js&id=f8306c5c-21fc-4a52-b3e6-1287acb17cfd:12323 
[EHD] E-Hentai Downloader Version > 1.33.4
userscript.html?name=E-Hentai%20Downloader.user.js&id=f8306c5c-21fc-4a52-b3e6-1287acb17cfd:12324 
[EHD] Current URL > https://exhentai.org/g/2085925/2aeb02f31d/
userscript.html?name=E-Hentai%20Downloader.user.js&id=f8306c5c-21fc-4a52-b3e6-1287acb17cfd:12325 
[EHD] Is Logged In > true
userscript.html?name=E-Hentai%20Downloader.user.js&id=f8306c5c-21fc-4a52-b3e6-1287acb17cfd:12284 
[EHD] E-Hentai Downloader Setting > {"speed-detect":false,"number-images":true,"number-real-index":true,"number-auto-retry":true,"auto-download-cancel":true,"dir-name":"{subtitle}","file-name":"{subtitle}","recheck-file-name":true,"ignore-torrent":true,"status-in-title":"never","hide-image-limits":false,"hide-estimated-cost":false,"file-descriptor":false,"force-resized":false,"never-new-url":false,"never-send-nl":false,"never-warn-large-gallery":true,"store-in-fs":false,"play-silent-music":false,"save-info":"none","save-info-list":["title","metas","uploader-comment","page-links"],"save-info-list[]":false,"replace-with-full-width":false,"force-pause":false,"save-as-cbz":false,"pass-cookies":false,"force-as-login":false}

userscript.html?name=E-Hentai%20Downloader.user.js&id=f8306c5c-21fc-4a52-b3e6-1287acb17cfd:12418 Uncaught (in promise) TypeError: str.replace(...).replace(...).replace(...).replace(...).replace(...).replace(...).replaceHTMLEntites is not a function
    at getReplacedName (userscript.html?name=E-Hentai%20Downloader.user.js&id=f8306c5c-21fc-4a52-b3e6-1287acb17cfd:12418)
    at toggleFilenameConfirmInput (userscript.html?name=E-Hentai%20Downloader.user.js&id=f8306c5c-21fc-4a52-b3e6-1287acb17cfd:14542)
    at eval (userscript.html?name=E-Hentai%20Downloader.user.js&id=f8306c5c-21fc-4a52-b3e6-1287acb17cfd:12293)
```

**Comment by ccloli** [comment]
怀疑是 Tampermonkey 更新了沙盒机制，对 prototype 有影响，不太确定。不过那部分实现可能是有点 hack，晚上修改下实现试试看。

/label:bug

**Comment by KINNAKAIHOU** [comment]
应该是Tampermonkey的问题了，刚才我试了一下安装Violentmonkey来运行，没有问题

**Comment by ccloli** [comment]
v1.13.5 已更新，简单修改了下实现方式，原来的实现方式也不太常规，更新后应该可以解决最近 Tampermonkey 的 sandbox 更新，可以在 Tampermonkey 上重新测试下。
