### ISSUE TITLE
download limit/timing between downloads

### ISSUE THREAD

**Issue by ss830** [ccloli/E-Hentai-Downloader#203]
~~_is there a way to limit the time between downloads, i notice that this triggers e-hentai's robot blocker for mass downloads.
is it the "delayTime = 0" variable or one of the Timeout variables?_~~ - never mind this part, it's all in the settings

also, is there a way to manually restart an aborted or failed download individually or no?

_(i'm not using it for coomer dls, but for the drawing howto's, for any family that may stumble upon this post)_

**Comment by ccloli** [comment]
Yep, the first question is already in the settings.

For the second question, I think there is no possible way to do it manually, it'll restart automatically when it fails.

**Comment by ss830** [comment]
thanks for the info.
__(it'd be much cooler if there was a restart button besides each failed/aborted file)__
