### ISSUE TITLE
暂停后无法继续下载

### ISSUE THREAD

**Issue by ousssaas11** [ccloli/E-Hentai-Downloader#205]
<img width="470" alt="屏幕截图 2022-02-05 004430" src="https://user-images.githubusercontent.com/99037945/152568523-636caf2b-b354-4282-9100-b228f0b9fd8d.png">
如图，出现黄色提示后，如果下一次是红色提示（我遇到两次，一次URL，一次超过配额。）就会出现黄色提示无法继续下载的情况，而且会一直提示downloading。而强制获取所有已下载文件会将红色报错的文件重新下载而黄色的则不会。最后获得的文件里也是一样。
浏览器：Microsoft Edge   版本 97.0.1072.76 (官方内部版本) (64 位)
脚本拓展程序：tampermonkey 版本v4.13.6138

**Comment by ccloli** [comment]
大概和以前下载数量会变为负数是相似的 bug，有些边界情况可能没有处理

**Comment by ccloli** [comment]
尝试通过断网的方式复现了下，没有遇到问题，列表后面的文件被 Network Error 标红后再中断之前的下载，仍会重新开始。

简单梳理了下逻辑，暂时没发现问题，显示黄色是表明其这次下载失败了，但是没超过重试次数限制，所以会立即重新开始。

考虑到出现问题的场景是上面的获取图片 URL 地址失败，以及超出配额，大概率是请求已经正常发出了，但由于网络问题或者是服务器问题，浏览器没有接收到数据，所以一直卡在获取图片 URL 地址或者卡在开始下载图片文件的阶段。一般来说如果不想继续等待，只需要手动中断下载即可。

如果后续再遇到类似问题，可以在出错时按下 F12，切换至 Console（控制台），将里面输出的所有日志复制粘贴到此。
