### ISSUE TITLE
“Failed （wrong mime）”怎麽解決？

### ISSUE THREAD

**Issue by wuwangqian** [ccloli/E-Hentai-Downloader#212]
自用賬號一直可以正常登錄exhentai和ehentai。插件和油猴都是目前最新版本，昨天還可以正常下載今天突然就出現了這個問題，請教如何解決

**Comment by wuwangqian** [comment]
![bandicam 2022-06-07 02-32-36-766](https://user-images.githubusercontent.com/84085540/172224012-c14ce5ad-aff7-4389-ab6c-89f78b784aef.jpg)

**Comment by spunky-sheets** [comment]
Seeing this too.  Using Greasemonkey on Firefox, but the 'failed wrong MIME' errors are only for pictures that are landscape orientation.

**Comment by ccloli** [comment]
可否提供存在問題的 gallery 地址？目前測試了一個，暫時沒有遇到該問題。是不是如樓上所說，GP 已被消耗清空？GP 剩餘數可在 [GP 交易頁](https://e-hentai.org/exchange.php?t=gp) 或者 E-Hentai 自帶的 Archive Download 中查看到

順帶下次遇到該問題時，可以按下 F12 將 控制台/Console 中的日誌全部複製出來，其中輸出了一些返回的信息方便判斷

***

Can you provide a gallery's link which has problem? I tried a gallery but it works for me. Is it just as the previous comment, that your GP has been used up? Your available GP can be seen on [GP Exchange](https://e-hentai.org/exchange.php?t=gp), or the offical [Archive Download] link right side the gallery info.

BTW next time when you have the problem, you can press F12 and switch to Console tab, and copy all the logs from it and paste them here, which includes some returned info to know what's up.

***

@Reinford0 了解，可能是他们的 GP 已经被消耗光了所以显示的错误信息。具体是不是这样还不太清楚，因为我所下载的 gallery 的 mime 确实是正确的，没有被脚本报 Wrong MIME，而且正如更新日志所说，首次触发会自动消耗 1000 的 GP。这两天正好要加一个功能，顺带把 GP 消耗也加一下试试看

**Comment by xZabuzax** [comment]
Hello, I'm having this same issue, I've never had this problem before till recently. I'm using Opera with the Tampermonkey extension.

**Comment by wuwangqian** [comment]
嘗試了一下幾乎所有的gallery都是一樣的情況，參考了https://forums.e-hentai.org/index.php?showtopic=244935，可能是我的gp被消耗的問題

**Comment by cloudhea** [comment]
same problem ，but if logout can download一样毛病，如果登出能下载
地址https://e-hentai.org/g/410601/d947334a55/
log日志

某些 Cookie 滥用推荐的“SameSite“属性 164
指向“https://adserver.juicyads.com/js/jads.js”的 <script> 加载失败。 d947334a55:20:1
指向“https://adserver.juicyads.com/js/jads.js”的 <script> 加载失败。 2 d947334a55:35:1
[EHD] Index > 2  | RealIndex > 2  | Name > 03.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 1  | RealIndex > 1  | Name > 01.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 3  | RealIndex > 3  | Name > 04.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 4  | RealIndex > 4  | Name > 05.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 3  | RealIndex > 3  | Name > 04.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 4  | RealIndex > 4  | Name > 05.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 1  | RealIndex > 1  | Name > 01.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 5  | RealIndex > 5  | Name > 06.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 2  | RealIndex > 2  | Name > 03.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 3  | RealIndex > 3  | Name > 04.jpg  | RetryCount > 2  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 1  | RealIndex > 1  | Name > 01.jpg  | RetryCount > 2  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 4  | RealIndex > 4  | Name > 05.jpg  | RetryCount > 2  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 5  | RealIndex > 5  | Name > 06.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 2  | RealIndex > 2  | Name > 03.jpg  | RetryCount > 2  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 1  | RealIndex > 1  | Name > 01.jpg  | RetryCount > 3  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 0 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 5  | RealIndex > 5  | Name > 06.jpg  | RetryCount > 2  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 1 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 3  | RealIndex > 3  | Name > 04.jpg  | RetryCount > 3  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 1 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 4  | RealIndex > 4  | Name > 05.jpg  | RetryCount > 3  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 2 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 5  | RealIndex > 5  | Name > 06.jpg  | RetryCount > 3  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 3 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 2  | RealIndex > 2  | Name > 03.jpg  | RetryCount > 3  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 4 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 8  | RealIndex > 8  | Name > 09.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 7  | RealIndex > 7  | Name > 08.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 6  | RealIndex > 6  | Name > 07.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 8  | RealIndex > 8  | Name > 09.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 7  | RealIndex > 7  | Name > 08.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 6  | RealIndex > 6  | Name > 07.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 9  | RealIndex > 9  | Name > 10.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 10  | RealIndex > 10  | Name > 11.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 8  | RealIndex > 8  | Name > 09.jpg  | RetryCount > 2  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 9  | RealIndex > 9  | Name > 10.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 6  | RealIndex > 6  | Name > 07.jpg  | RetryCount > 2  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 10  | RealIndex > 10  | Name > 11.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 7  | RealIndex > 7  | Name > 08.jpg  | RetryCount > 2  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 9  | RealIndex > 9  | Name > 10.jpg  | RetryCount > 2  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 10  | RealIndex > 10  | Name > 11.jpg  | RetryCount > 2  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 6  | RealIndex > 6  | Name > 07.jpg  | RetryCount > 3  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 5 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 8  | RealIndex > 8  | Name > 09.jpg  | RetryCount > 3  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 6 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 7  | RealIndex > 7  | Name > 08.jpg  | RetryCount > 3  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 7 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 9  | RealIndex > 9  | Name > 10.jpg  | RetryCount > 3  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 8 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 10  | RealIndex > 10  | Name > 11.jpg  | RetryCount > 3  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 9 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 12  | RealIndex > 12  | Name > 13.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 10 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 11  | RealIndex > 11  | Name > 12.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 10 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 13  | RealIndex > 13  | Name > 14.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 10 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 15  | RealIndex > 15  | Name > 16.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 10 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 14  | RealIndex > 14  | Name > 15.jpg  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 10 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 11  | RealIndex > 11  | Name > 12.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 10 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 12  | RealIndex > 12  | Name > 13.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 10 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 13  | RealIndex > 13  | Name > 14.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 10 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 15  | RealIndex > 15  | Name > 16.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 10 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 14  | RealIndex > 14  | Name > 15.jpg  | RetryCount > 1  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 10 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 12  | RealIndex > 12  | Name > 13.jpg  | RetryCount > 2  | DownloadedCount > 0  | FetchCount > 5  | FailedCount > 10 E-Hentai Downloader.user.js:12809:10
[EHD] Index > 13  | RealIndex > 13  | Name > 14.jpg  | RetryCount > 2  | DownloadedCount > 0  | FetchCount > 5  | Fa

**Comment by wuwangqian** [comment]
登出賬號后，e-hentai正常下載，exhentai幾乎所有gallery都是“wrong mime”

**Comment by wuwangqian** [comment]
可能是gp的問題。。。。
點擊[Download original 2508 x 3541 3.31 MB source]，顯示“Downloading original files during peak hours requires GP, and you do not have enough.”

**Comment by ccloli** [comment]
> byteLength === 102 || //byteLength === 102 You have reached the image limit, and do not have sufficient GP to buy a download quota.
> byteLength === 93 || //byteLength === 93 Downloading original files during peak hours requires GP, and you do not have enough.

@utidevel Huge thanks for the information, no need to gain it from myself. 😝 

To make it simplifier, will reuse these states as Exceed Limits status.

**Comment by ccloli** [comment]
v1.34 is released just now, if it's in peak hours, the script will add estimated GP cost and notify you, and pause downloading if you don't have GPs just like you don't have quota. 

Please give it a try and let me know if it works. You can check for updates from userscript extension, or redownload it from this repo's readme.

***

v1.34 已更新，添加了在 E-Hentai 指定的流量峰值期间展示 GP 消耗，并在下载前二次确认的功能，同时会在下载提示没有足够 GP 时自动暂停。

请尝试更新并确认是否解决该问题。你可以在用户脚本的扩展程序中检查更新，或者直接前往项目的主页重新下载安装。

**Comment by xZabuzax** [comment]
Version v1.34 seems to be working, it wasn't working a couple of minutes ago though, maybe it's working now because it's Peak Hours or something?

**Comment by ccloli** [comment]
> Version v1.34 seems to be working, it wasn't working a couple of minutes ago though, maybe it's working now because it's Peak Hours or something?

@xZabuzax For weekdays, Peak Hours is at 14:00-20:00 UTC, and it should be started a few hours ago (and will be ended about an hour later). The estimated GP cost will only shows during the Peak Hours, if it doesn't work just now, maybe the script isn't updated at that time, or you need to manually refresh previous pages to load the latest version.

**Comment by xZabuzax** [comment]
> > Version v1.34 seems to be working, it wasn't working a couple of minutes ago though, maybe it's working now because it's Peak Hours or something?
> 
> @xZabuzax For weekdays, Peak Hours is at 14:00-20:00 UTC, and it should be started a few hours ago (and will be ended about an hour later). The estimated GP cost will only shows during the Peak Hours, if it doesn't work just now, maybe the script isn't updated at that time, or you need to manually refresh previous pages to load the latest version.

That makes sense, oh well I'm glad it's working now, thank you for the fast update mate :)

**Comment by ccloli** [comment]
v1.34.1 released just now, which fixed the warning is keep showing when it's not in peak hours (mentioned in https://github.com/ccloli/E-Hentai-Downloader/commit/aa3886a5090a38b00e2d245e5a2062ea47ca6efd#r75586742 ).

Also it applies E-Hentai's new policy, so it's fine if you don't see estimated GP cost during peak hours:

> 2022-06-07
> 
> A couple of minor tweaks to the "Download source image" changes, since it dropped the utilization by a lot more than we needed it to:
> 
> - It no longer applies to galleries posted in the last 7 days.
> 
> - It no longer applies for donators.

Though it's a bit weird for me, since I'm still being counted by viewing limits instead of GPs when downloading old galleries, and it's definitely in peak hours now, or even not counting viewing limits when browsing normally. I think it's a bug of E-Hentai's current implementation, so the script still follows the new rules in case it's being fixed in the future.

**Comment by Snuupies** [comment]
happy new years.

i suppose it should work now? currently having the same issue. 
Seems that it just refuses to download the original image until you log out
