### ISSUE TITLE
压缩包损坏问题

### ISSUE THREAD

**Issue by 424778940z** [ccloli/E-Hentai-Downloader#216]
如题 以前遇到过几次重新下就好了
但/g/1951010/d9a48bec3c/似乎怎么下都会损坏 我先后下载了四次 都是损坏
就以往损坏时候研究了一下压缩包文件 数据其实在的 只是尾部好像被掐掉了一块

010里看一个标准zip应该有
struct ZIPFILERECORD record
struct ZIPDIRENTRY dirEntry
struct ZIPENDLOCATOR endLocator

但这个脚本生成的只有(包括好的)
ZIPFILERECORD record

貌似这个zip不是很标准? 但问题似乎不是缺少了这两个东西?
没有深入研究, 工作时间不太好开ex摸鱼2333

**Comment by ccloli** [comment]
后续看一下，可以先提供下运行环境，例如使用的浏览器、使用的用户脚本扩展以及脚本的设置。

简单的话可以打开任意一个 gallery，按下 F12 切换至 Console，不需要开始下载，将已经输出的日志复制粘贴过来就行。

初步怀疑可能是用了 file system 但是写入块丢失了？或者是系统盘剩余空间不足导致 blob storage 满了？可能需要看看具体的脚本配置才能排查

**Comment by ccloli** [comment]
> 但/g/1951010/d9a48bec3c/似乎怎么下都会损坏 我先后下载了四次 都是损坏

> Estimated Limits Cost: 31 + 6941 GP

下班太晚，gallery 太老，现在下载要 GP，下次再试好了 🤣 

> `"file-descriptor":true`

这个配置项有点可疑，一会我用其他 gallery 试试看

**Comment by ccloli** [comment]
> 有问题的zip, pk头很多都是0000

其实这是符合预期的，那个设置项对应 JSZip 的这一个配置项：

> `streamFiles` option
> In a zip file, the size and the crc32 of the content are placed before the actual content: to write it we must process the whole file. When this option is `false` (the default) the processed file is held in memory. It takes more memory but generates a zip file which should be read by every program. When this options is `true`, we stream the file and use data descriptors at the end of the entry. This option uses less memory but some program might not support data descriptors (and won’t accept the generated zip file).

也就是说，填 0 的字段只是作为占位符，对应的数据位于 file record 的尾部以 zip spanning marker 出现，也就是下图中黄色标记的部分：

![Screenshot_20220628-100057_Chrome](https://user-images.githubusercontent.com/8115912/176076596-5c524d62-3346-494c-86b2-7947c9dda113.jpg)

具体这部分的数据在 PKZIP 的 [官方文档](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) 里也有提到

![SmartSelect_20220628-101208_Termux](https://user-images.githubusercontent.com/8115912/176076611-8c509404-83ea-44a8-a610-92f03d167f5c.jpg)


所以如果排除可能的文件损坏的情形，该文件格式是符合预期的

**Comment by 424778940z** [comment]
hummm 那可能还是stream没有被完整存下来导致无法解析?
总之关掉这两个之后就好了 用普通zip好像也没什么问题

**Comment by ccloli** [comment]
周末试了下这个 gallery，开启 _Stream files and create Zip with file descriptors_ 和 File System，下载的文件使用 WinRAR 测试是没有问题的，也可以正常解压，不过 7-Zip 和某个早期版本的 WinZip 确实没法识别，暂且认为是 `streamFiles` 这个选项与不少软件存在兼容性问题好了。

![image](https://user-images.githubusercontent.com/8115912/176996517-d8cce753-8332-4b76-b467-887bfcacbe30.png)
