### ISSUE TITLE
Archive too large for 8MB archive

### ISSUE THREAD

**Issue by typhoon71** [ccloli/E-Hentai-Downloader#22]
This happens with http://exhentai.org/g/66369/8d6f6cb405/
The archive downloads fine, I just get the "archive is too large" dialog for no reason.

**Comment by iShyboy** [comment]
True, that's happening in the last version, and its not only from this gallery or another 8mb archive.
as you can see in
![warn](http://i.imgur.com/dWuPCcO.png)

**Comment by ccloli** [comment]
Fixed, sorry for my careless.

**Comment by typhoon71** [comment]
Well done, it works as it should now.
Thanks.
