### ISSUE TITLE
请问可否提供使用服务器的文件创建&修改时间这一选项

### ISSUE THREAD

**Issue by ikali** [ccloli/E-Hentai-Downloader#223]
虽然此功能不具备任何现实意义，但如果可简单实现的话，请考虑一下。

**Comment by ccloli** [comment]
暂不考虑该功能，一是该功能确实没有实际意义，二是服务器返回的 `Date` 响应头与当前时间是一致的，而不是文件上传的时间，错序下载会导致按照时间排序文件时文件顺序错乱，导致该功能更没有实际意义了。
