### ISSUE TITLE
[REQUEST] Post process: WebP convert. 

### ISSUE THREAD

**Issue by momoe** [ccloli/E-Hentai-Downloader#225]
Since media is getting exceptionally large uploads on EH I request there be a further option to take all the downloaded media and convert it to the WebP compression before ZIP packaging. It will significantly reduce the file sizes for clients.

https://developers.google.com/speed/webp/docs/compression

**Comment by ccloli** [comment]
Doing this over browser may significantly slow down your browser and takes more RAM. If you need a smaller package and doesn't care about original image quality, enable _Settings -> Advanced -> Force download resized image_ should help you.

**Comment by momoe** [comment]
Fair enough, for now I have XnConvert, which allows me to convert the original quality size to WebP while maintaining the original dimensions with negligible quality loss. So far it hasn't taxed more than 130MB ram requirements. but it is a manual batch process each time.
