### ISSUE TITLE
语言问题

### ISSUE THREAD

**Issue by qianzhou123** [ccloli/E-Hentai-Downloader#229]
现在的这个js程序仅有英语，我希望他有汉化
特别是下载后的图库信息和设置界面
![image](https://user-images.githubusercontent.com/111413182/204074173-345c1ba4-dfa0-45c9-934d-acbc8bb43b33.png)
![image](https://user-images.githubusercontent.com/111413182/204074180-55a410a3-2a9f-4926-82f6-c9009ccbeb72.png)
![image](https://user-images.githubusercontent.com/111413182/204074188-8c19824a-2a2b-4cf2-b120-ffb611ecf879.png)
![image](https://user-images.githubusercontent.com/111413182/204074216-2f19628c-ba48-4bfd-a8fd-f8f4e240b87b.png)
我这是用网页翻译实现的但不稳定

**Comment by ccloli** [comment]
由于脚本本身开发时未考虑多语言，文本耦合于代码中，因此暂不考虑支持
