### ISSUE TITLE
建议限制Retrying下载的时间限制

### ISSUE THREAD

**Issue by CLE** [ccloli/E-Hentai-Downloader#23]
一个图集都下完99%了，就几个图片无法下载，卡在重试中，比下载时间还长，简直浪费时间。
建议添加一个时间限制，可以忽略卡住的图片。

**Comment by ccloli** [comment]
显示重试时已经在重新下载了，如果等待时间过长可以考虑在设置中减少超时等待时间以及重试次数。

另外，强制停止下载已经在计划中了（或许我该加个 todo list），不过最近没太多时间弄。

**Comment by ccloli** [comment]
在 1.19.9 中添加了强制终止下载指定图片的功能，可以强制终止下载速度慢的图片（下载失败计数也会增加，达到设定值后将不会再下载）。
