### ISSUE TITLE
請問沒有中文的README.md嗎？ 

### ISSUE THREAD

**Issue by hsyscq** [ccloli/E-Hentai-Downloader#245]
特別是關於警告和彈出的消息框的内存内存限制
決定下載上限的還是瀏覽器嗎
我現在使用的是edge114  RAM是32GB那麽上限是2G？

**Comment by ccloli** [comment]
是，理論上最大限制為 2GB，但不推薦下載大於 500MB 的 gallery

優先推薦使用 torrent 或者官方下載方式，如果必須需要腳本手動下載，建議使用 gallery-dl

**Comment by hsyscq** [comment]
> 

 好的 謝謝
