### ISSUE TITLE
Exclusion in "pages range" download doesn't work

### ISSUE THREAD

**Issue by Triramama** [ccloli/E-Hentai-Downloader#248]
Please tell me if I'm missing something. I sometimes need to download a gallery without a certain page or two, but when I input inside the "pages range" field, for example, "-1" what I expect the script to do is download all the pages except for the first one, however what it does, completely counterintuitively, is ignoring the minus prefix and downloading only the page 1 instead.
Can this somehow be fixed?

**Comment by ccloli** [comment]
Nope, there's no exclude mode. The prefix and suffix `-` means start from the first page or to the last page. Hover on the input should give you some hints.
![image](https://github.com/ccloli/E-Hentai-Downloader/assets/8115912/675ed6ba-5cb8-410e-81f2-4fd3d4c58f29)

**Comment by Triramama** [comment]
Alright, I hope you add someday though

**Comment by ccloli** [comment]
v1.35 is released, now you can prefix a page or page range with `!` to exclude them. 

You can combined ranges by order, like `1-10,!3-8,5` will gives you page 1, 2, 5, 9 and 10.
