### ISSUE TITLE
能不能在日志中单独输出下载不了的文件数字

### ISSUE THREAD

**Issue by jackpanz** [ccloli/E-Hentai-Downloader#249]
比如下错误文件有
#10: HS2_2022_08_12_23_45_34_594.jpg |   | Failed! (Network Error)
#11: HS2_2022_08_13_00_50_45_560.png | 100% | Succeed!
#12: HS2_2022_08_13_00_50_53_205.png | 100% | Succeed!
#13: HS2_2022_08_13_00_52_13_094.png | 100% | Succeed!
#14: HS2_2022_08_13_00_53_01_853.png | 100% | Succeed!
#15: HS2_2022_08_13_00_53_06_354.png | 100% | Succeed!
#16: HS2_2022_08_13_00_55_00_122.jpg |   | Failed! (Network Error)
#17: HS2_2022_08_13_00_55_34_906.png | 100% | Succeed!
#18: HS2_2022_08_13_00_56_34_006.png | 100% | Succeed!
#19: HS2_2022_08_13_00_57_18_392.png | 100% | Succeed!
#20: HS2_2022_08_13_01_03_49_901.jpg |   | Failed! (Network Error)

单独输出
10,16,20

下载错误文件比较多，下次想单独下载错误的文件。

**Comment by ccloli** [comment]
应该可以，下个版本加一下，Soon™️

**Comment by ccloli** [comment]
v1.35 已发布，当取消重试时会在窗口内展示失败的页码
