### ISSUE TITLE
Can't download original image after site update 

### ISSUE THREAD

**Issue by fururebyworks** [ccloli/E-Hentai-Downloader#259]
Is it just me? Resize image is downloaded after clicking Download Archive. Force download resize image is uncheck in advanced.

**Comment by ccloli** [comment]
Without any further information like screenshot, gallery url or log in console, I'd say "Yep, you, only you, just you, you're the chosen one". 🤣

Check if the zip file matches gallery's file size first, then see which page goes wrong and whether that page has the "download original image" link. To get a copy of runtime log, press F12 and switch to Console, start download, then copy all the logs started with [EHD] then paste it here.

**Comment by suzumiyang** [comment]
Me too. 103m on gallery, 3m zip.

**Comment by suzumiyang** [comment]
here is all my log
[EHD] E-Hentai Downloader is running.
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:39 [EHD] Bugs Report > https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:40 [EHD] To report a bug, it's recommended to provide the logs started with "[EHD]", thanks. =w=
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12322 [EHD] UserAgent > Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12323 [EHD] Script Handler > Tampermonkey
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12324 [EHD] Script Handler Version > 4.19.0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12325 [EHD] E-Hentai Downloader Version > 1.34.10
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12326 [EHD] Current URL > https://exhentai.org/g/2722860/13e3010d0f/
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12327 [EHD] Is Logged In > true
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12286 [EHD] E-Hentai Downloader Setting > {"thread-count":5,"timeout":0,"speed-detect":false,"retry-count":6,"delay-request":0,"number-images":true,"number-separator":"_","number-real-index":true,"number-auto-retry":true,"auto-download-cancel":true,"dir-name":"/","file-name":"{subtitle}","recheck-file-name":false,"ignore-torrent":true,"status-in-title":"always","hide-image-limits":false,"hide-estimated-cost":false,"file-descriptor":false,"force-resized":false,"never-new-url":false,"never-send-nl":false,"never-warn-peak-hours":false,"never-warn-large-gallery":true,"store-in-fs":true,"play-silent-music":true,"save-info":"file","save-info-list":["title","metas","uploader-comment","page-links"],"save-info-list[]":false,"replace-with-full-width":true,"force-pause":false,"save-as-cbz":false,"pass-cookies":false,"force-as-login":false}
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:14680 [EHD] Request Resolution Setting
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:14542 [EHD] Request Image Limits From e-hentai.org
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12122 [EHD] File System is opened! Name > https_exhentai.org_0:Temporary
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:14692 [EHD] Resolution Setting > {"withoutHentaiAtHome":0,"resolution":1,"originalImages":0,"timestamp":1698756665512}
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:14570 [EHD] Image Limits > {"timestamp":1698756665621,"cur":"0","total":"50000","donatorPower":0}
13e3010d0f/:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at xhr.onreadystatechange (userscript.html?name=X2Convert-Button.user.js&id=88c8c382-d872-440b-aa0c-2bb62a901c8d:353:591)
ip.x2convert.com/checkcookie.ashx:1 
        
        
       Failed to load resource: net::ERR_CERT_DATE_INVALID
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:14786 [EHD] Is Peak Hours > false  | Is Recent Gallery > true  | Is Ancient Gallery > false  | Is Donator > false
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:13914 [EHD] Required File System Space > 541807248
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:13921 [EHD] Free TEMPORARY File System Space > 152938948755
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12066 [EHD] File System is opened! Name > https_exhentai.org_0:Temporary
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12112 [EHD] Request removing all files in File System.
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12100 [EHD] File FileEntry is removed.
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 3  | RealIndex > 3  | Name > 112892399_p0.jpg  | RetryCount > 0  | DownloadedCount > 1  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 5  | RealIndex > 5  | Name > 112130220_p0.jpg  | RetryCount > 0  | DownloadedCount > 2  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 4  | RealIndex > 4  | Name > 112816681_p0.jpg  | RetryCount > 0  | DownloadedCount > 3  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 6  | RealIndex > 6  | Name > 112190196_p0.jpg  | RetryCount > 0  | DownloadedCount > 4  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 2  | RealIndex > 2  | Name > 112954180_p0.jpg  | RetryCount > 0  | DownloadedCount > 5  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 1  | RealIndex > 1  | Name > 113013678_p0.jpg  | RetryCount > 0  | DownloadedCount > 6  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 7  | RealIndex > 7  | Name > F68dJDabQAAAvA2.jpg  | RetryCount > 0  | DownloadedCount > 7  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 8  | RealIndex > 8  | Name > F6sxqaraIAAjDRz.jpg  | RetryCount > 0  | DownloadedCount > 8  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 10  | RealIndex > 10  | Name > 111858771_p0.jpg  | RetryCount > 0  | DownloadedCount > 9  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 9  | RealIndex > 9  | Name > 111911654_p0.jpg  | RetryCount > 0  | DownloadedCount > 10  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 11  | RealIndex > 11  | Name > 111800891_p0.jpg  | RetryCount > 0  | DownloadedCount > 11  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 12  | RealIndex > 12  | Name > 111741472_p0.jpg  | RetryCount > 0  | DownloadedCount > 12  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 14  | RealIndex > 14  | Name > 111690744_p1.jpg  | RetryCount > 0  | DownloadedCount > 13  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 13  | RealIndex > 13  | Name > 111690744_p0.jpg  | RetryCount > 0  | DownloadedCount > 14  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 15  | RealIndex > 15  | Name > 111639281_p0.jpg  | RetryCount > 0  | DownloadedCount > 15  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 17  | RealIndex > 17  | Name > 111530315_p0.jpg  | RetryCount > 0  | DownloadedCount > 16  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 16  | RealIndex > 16  | Name > 111583869_p0.jpg  | RetryCount > 0  | DownloadedCount > 17  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 20  | RealIndex > 20  | Name > 111460727_p0.jpg  | RetryCount > 0  | DownloadedCount > 18  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 18  | RealIndex > 18  | Name > 111470851_p0.jpg  | RetryCount > 0  | DownloadedCount > 19  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 22  | RealIndex > 22  | Name > 111460727_p2.jpg  | RetryCount > 0  | DownloadedCount > 20  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 21  | RealIndex > 21  | Name > 111460727_p1.jpg  | RetryCount > 0  | DownloadedCount > 21  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 19  | RealIndex > 19  | Name > 111470851_p1.jpg  | RetryCount > 0  | DownloadedCount > 22  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 24  | RealIndex > 24  | Name > 111267853_p1.jpg  | RetryCount > 0  | DownloadedCount > 23  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 23  | RealIndex > 23  | Name > 111267853_p0.jpg  | RetryCount > 0  | DownloadedCount > 24  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 25  | RealIndex > 25  | Name > 111211497_p0.jpg  | RetryCount > 0  | DownloadedCount > 25  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 27  | RealIndex > 27  | Name > 111068666_p0.jpg  | RetryCount > 0  | DownloadedCount > 26  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 26  | RealIndex > 26  | Name > 111123823_p0.jpg  | RetryCount > 0  | DownloadedCount > 27  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 28  | RealIndex > 28  | Name > 111068611_p0.jpg  | RetryCount > 0  | DownloadedCount > 28  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 29  | RealIndex > 29  | Name > 110858757_p0.jpg  | RetryCount > 0  | DownloadedCount > 29  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 32  | RealIndex > 32  | Name > 110795855_p1.jpg  | RetryCount > 0  | DownloadedCount > 30  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 31  | RealIndex > 31  | Name > 110795855_p0.jpg  | RetryCount > 0  | DownloadedCount > 31  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 30  | RealIndex > 30  | Name > 110858757_p1.jpg  | RetryCount > 0  | DownloadedCount > 32  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 33  | RealIndex > 33  | Name > 110678668_p0.jpg  | RetryCount > 0  | DownloadedCount > 33  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 34  | RealIndex > 34  | Name > 110678668_p1.jpg  | RetryCount > 0  | DownloadedCount > 34  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 37  | RealIndex > 37  | Name > 109122453_p0.jpg  | RetryCount > 0  | DownloadedCount > 35  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 35  | RealIndex > 35  | Name > 110364031_p0.jpg  | RetryCount > 0  | DownloadedCount > 36  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 36  | RealIndex > 36  | Name > 110247716_p0.jpg  | RetryCount > 0  | DownloadedCount > 37  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 38  | RealIndex > 38  | Name > 108986012_p0.jpg  | RetryCount > 0  | DownloadedCount > 38  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 39  | RealIndex > 39  | Name > 108584072_p0.jpg  | RetryCount > 0  | DownloadedCount > 39  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 40  | RealIndex > 40  | Name > 108461210_p0.jpg  | RetryCount > 0  | DownloadedCount > 40  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 42  | RealIndex > 42  | Name > 108461161_p1.jpg  | RetryCount > 0  | DownloadedCount > 41  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 41  | RealIndex > 41  | Name > 108461161_p0.jpg  | RetryCount > 0  | DownloadedCount > 42  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 43  | RealIndex > 43  | Name > 108461161_p2.jpg  | RetryCount > 0  | DownloadedCount > 43  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 45  | RealIndex > 45  | Name > 107989378_p0.jpg  | RetryCount > 0  | DownloadedCount > 44  | FetchCount > 5  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 44  | RealIndex > 44  | Name > 108461161_p3.jpg  | RetryCount > 0  | DownloadedCount > 45  | FetchCount > 4  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 48  | RealIndex > 48  | Name > 105068400_p0.jpg  | RetryCount > 0  | DownloadedCount > 46  | FetchCount > 3  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 47  | RealIndex > 47  | Name > 105333804_p0.jpg  | RetryCount > 0  | DownloadedCount > 47  | FetchCount > 2  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12516 [EHD] Index > 46  | RealIndex > 46  | Name > 106565132_p0.jpg  | RetryCount > 0  | DownloadedCount > 48  | FetchCount > 1  | FailedCount > 0
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:14542 [EHD] Request Image Limits From e-hentai.org
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12808 [EHD] File [Pixiv ｜ Twitter] 殘夜 ZANYA (90875712) is removed.
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:12081 [EHD] File URL > filesystem:https://exhentai.org/temporary/2722860.zip
userscript.html?name=E-Hentai-Downloader.user.js&id=c9d1b0dc-6d6a-49ba-8c49-bf76fd0b2f92:14570 [EHD] Image Limits >

**Comment by goooooodperson** [comment]
Me too,My record is similar to the above. I'd say it happened about six hours ago.

**Comment by ccloli** [comment]
> six hours ago

That makes sense, since I just tested the function yesterday. Should have a look at it whe I arrived at home.

**Comment by ccloli** [comment]
Looks like the original image link format has been changed from `https://exhentai.org/fullimg.php?gid=2722913&page=15&key=ofk0lkwa43p` to `https://e-hentai.org/fullimg/2722913/15/ofk0lkwa43p/112653370_p0.jpg`. 

Although the site update happened a few days ago didn't break the script, because the script is matched by url regex pattern, today EH changes the url format, so for now the original image download is not available because the script cannot find the old pattern.

**Comment by goooooodperson** [comment]
> Looks like the original image link format has been changed from `https://e-hentai.org/fullimg.php?gid=2722913&page=15&key=ofk0lkwa43p` to `https://e-hentai.org/fullimg/2722913/15/ofk0lkwa43p/112653370_p0.jpg`.
> 
> Although the site update happened a few days ago didn't break the script, because the script is matched by url regex pattern, today EH changes the url format, so for now the original image download is not available because the script cannot find the old pattern.

Thank you, my hero! 
I change the (\S+?\/fullimg\.php\?\S+?) to (\S+?\/fullimg\/\S+?) in regex and "fullimg.php" to "fullimg/" in indexOf function. It seems to be working fine again.

**Comment by ccloli** [comment]
v1.35 is released, sorry it's a bit late, since there are some changes I made in local and haven't pushed to remote.

These changes was going to be released in a new y version, but didn't fully finish yet. so I was resolving conflicts and addressing some new issues, then forget it just yolo. Hope it doesn't have too many bugs. 🤣

**Comment by 70338** [comment]
e-h update today(2023/10/31) change something.
The original image URL has changed to other websites, and it seems to be floating. Moreover, those URLs are unstable, and some images are difficult to load.
Due to the change in the website policy, I am not sure if obtaining the original image requires a higher level. (I have bought bronze star aready,wish I dont need to upgrade to sliver.)
Thank you for developing and fixing it.

**Comment by ccloli** [comment]
> Moreover, those URLs are unstable, and some images are difficult to load.

Because original images is also delivered by Hentai@Home now, see EH update log.

> \- H@H High-Capacity Ranges are now live. This change lets us efficiently take advantage of surplus H@H capacity for original images with some limitations.
> 
> Specifically, the system will now use H@H for original images smaller than 10 MiB in galleries that were posted in the last year, assuming that you haven't changed the H@H setting under "Image Load Settings" to "Default port clients only" or "No". Otherwise, it will still use the regular image servers.
> 
> This change applies for regular browsing when "Prefer original images" is selected and the file would normally be resampled at 2400x, when using the "Download Original" button, and when using the H@H Downloader.

v1.35 somehow addresses the problem by appending `nl` parameter, for details, see previous issue #256. 

***

> The original image URL has changed to other websites, and it seems to be floating.

The update log has been updated, too. It's to fix a bug on Firefox.

> \- We now do an URL rewrite for fullimg requests to fix an issue specific to Firefox where files were sometimes being saved as "fullimg.php"

**Comment by 70338** [comment]
It works now! Thank you!

**Comment by Triramama** [comment]
After this update, when I exceed my viewing quota download doesn't stop automatically and gives me the warning, instead download starts consuming my gp, lost a couple thousand on a gallery that's not even 12 month old already, would appreciate if you could look into it.

**Comment by ccloli** [comment]
@Triramama Sorry to hear that, maybe the site updates also changes something else. Since it's not related to this issue, for further tracking purpose and keep tidy, I'm going open a new issue.
