### ISSUE TITLE
点击Download Archive无法下载，疑似和EhSyringe脚本冲突

### ISSUE THREAD

**Issue by wyjtm** [ccloli/E-Hentai-Downloader#260]
https://sleazyfork.org/zh-CN/scripts/407833-ehsyringe

表现为装上EhSyringe脚本后点击Download Archive无法下载，点击下载没有任何反应，关掉EhSyringe脚本的翻译界面、翻译时间戳两个功能后测试发现能下载了，目前还在继续测试中

环境是
Google Chrome 版本 118.0.5993.118（正式版本） （64 位）
E-Hentai Downloader 1.35
EhSyringe 2.12.0

Microsoft Edge 版本 118.0.2088.76 (正式版本) (64 位)
E-Hentai Downloader 1.35
EhSyringe 2.12.0

上面两个环境用篡改猴 黑色红色都测试了，都出现同样问题

请确认下是这边的脚本问题还是EhSyringe脚本的问题

**Comment by ccloli** [comment]
See #257 & https://github.com/ccloli/E-Hentai-Downloader/issues/50#issuecomment-254060816

**Comment by OpportunityLiu** [comment]
关于本地化的内容都在这边讨论吧 EhTagTranslation/EhSyringe#1221

**Comment by ccloli** [comment]
忘了下载时也会获取节点来拿到总页数了，v1.35.1 做了下处理。现在针对节点不存在的情况，页码会自动从另一个地方获取，不过预估消耗可能依然无法修复，但至少应该不会阻塞下载了

~~顺便改了些文案调整了顺序，希望 EhSyringe 的作者不要打我~~
