### ISSUE TITLE
下拉时会挡住评论区和画面

### ISSUE THREAD

**Issue by Makima55555** [ccloli/E-Hentai-Downloader#262]
如题，以前好像不会这样
![image](https://github.com/ccloli/E-Hentai-Downloader/assets/143767670/18dfd471-531b-4220-9de8-c56b5309da94)

**Comment by ccloli** [comment]
可先在 Settings 里将 Pin download actions box at the top of the page 暂时关闭

该功能本来是打算配合 #246 完成时一起上线的，不过由于昨天网站更新紧急修复，被一起推上去了，下个 bugfix 版本会先移除掉这个功能
