### ISSUE TITLE
After this update, when I exceed my viewing quota download doesn't stop automatically and gives me the warning, instead download starts consuming my gp, lost a couple thousand on a gallery that's not even 12 month old already, would appreciate if you could look into it.

### ISSUE THREAD

**Issue by ccloli** [ccloli/E-Hentai-Downloader#264]
After this update, when I exceed my viewing quota download doesn't stop automatically and gives me the warning, instead download starts consuming my gp, lost a couple thousand on a gallery that's not even 12 month old already, would appreciate if you could look into it.

_Originally posted by @Triramama in https://github.com/ccloli/E-Hentai-Downloader/issues/259#issuecomment-1790329872_

**Comment by ccloli** [comment]
Close as probably intended, messed up with something else.

**Comment by Triramama** [comment]
Thanks, I would've personally made the title more concise.
I think after I exceed the quota, it gets reset at the cost of gp, either that or downloading is just switched to gp purchasing method, It's not a big problem, by no means, If I keep track of my view limits.

**Comment by ccloli** [comment]
@Triramama My bad, sorry for I messed it up. Since I realized that it's actually not a bug (I thought it keeps trying when the site returns 509), so I make it short. 

EH changes this for a long time, you can check it in sites update. In short, when you used up your image limits, it'll consume GP instead. The script cannot detect it from server returns directly for now, so at least for now the behavior is intended.

For details, please check https://github.com/ccloli/E-Hentai-Downloader/issues/247 .

**Comment by ccloli** [comment]
Was going to removed the issue, but since you replied here, I'm going to keep it here. 😂

At least the cost of continue browsing and reset limits are the same.

**Comment by ccloli** [comment]
v1.35.1 is released, now it'll warn you when you've used up your limits, or your limits + estimated cost will exceed your all quota.
