### ISSUE TITLE
jpg file when downloading png file

### ISSUE THREAD

**Issue by fururebyworks** [ccloli/E-Hentai-Downloader#265]
hi, is anyone experience this problem? getting .jpg format when downloading .png format image file. File name, size, hash check are ok, Just notice all the .png format image I've download these past few days are in .jpg format. If manual download from site the file will be in png.

**Comment by ccloli** [comment]
Probably related to sites update, EH now returns the original file inline instead of showing a save as window, so the image server didn't return original file name in HTTP header now.

**Comment by ccloli** [comment]
Should be fixed in v1.35.2 which is released just now.

**Comment by fururebyworks** [comment]
> Should be fixed in v1.35.2 which is released just now.

its working. Thank you very much for the quick fix.
