### ISSUE TITLE
儅提示該畫廊在經過上傳后已經經過了太長時間建議不要下載原始圖檔時，我該如何修改設定以下載壓縮圖檔？

### ISSUE THREAD

**Issue by NyoronGero** [ccloli/E-Hentai-Downloader#272]

**Comment by ccloli** [comment]
選擇確認即可，該提示僅是詢問是否需要繼續下載而已

**Comment by NyoronGero** [comment]
> 選擇確認即可，該提示僅是詢問是否需要繼續下載而已

但是繼續的話只能下載原始圖檔？會損失大量GP？我是可以接受2400x的

**Comment by ccloli** [comment]
不好意思沒留意後半句話，如果不需要的話，可以在 Settings 里切換至 Advanced，並勾上 _ Force download resized image (never download original image) _ 並保存，保存後再執行下載即可

如果需要下載 2400x 而非默認的 1280x，還需要在 EH 的 My Settings 中將 Image Size Settings 設置為 2400x

目前還無法在彈出警告時直接切換至下載壓縮圖片

**Comment by NyoronGero** [comment]
> 不好意思沒留意後半句話，如果不需要的話，可以在 Settings 里切換至 Advanced，並勾上 _Force download resized image (never download original image)_ 並保存，保存後再執行下載即可
> 
> 如果需要下載 2400x 而非默認的 1280x，還需要在 EH 的 My Settings 中將 Image Size Settings 設置為 2400x
> 
> 目前還無法在彈出警告時直接切換至下載壓縮圖片，因此需要做上述的手動操作

感謝！
