### ISSUE TITLE
64G RAM,下载4.3G的gallery，下载成功，但是生成zip时一直卡在最后几张png

### ISSUE THREAD

**Issue by Rex1987** [ccloli/E-Hentai-Downloader#273]
![image](https://github.com/ccloli/E-Hentai-Downloader/assets/29326825/f6f5c8b4-832b-49af-ba02-402179ed1aa2)
想知道能不能直接去哪里拿到这些文件，或者有什么解决方案

**Comment by Rex1987** [comment]
chrome 119.0.6045.160
script 1.35.2

**Comment by Rex1987** [comment]
console的报错信息：
userscript.html?name=E-Hentai-Downloader.user.js&id=464148c7-79b3-4fe8-8950-5c8df098b7fc:12675 Uncaught (in promise) ReferenceError: abData is not defined
    at errorHandler (userscript.html?name=E-Hentai-Downloader.user.js&id=464148c7-79b3-4fe8-8950-5c8df098b7fc:12675:10)
errorHandler @ userscript.html?name=E-Hentai-Downloader.user.js&id=464148c7-79b3-4fe8-8950-5c8df098b7fc:12675
![image](https://github.com/ccloli/E-Hentai-Downloader/assets/29326825/5cc27383-86bb-4e63-98b2-9a0374332112)

**Comment by ccloli** [comment]
看起来代码内部有些问题，导致抛出的错误不是实际错误。不过多半能猜到原因，这个错误是 zip 库无法成功生成 zip 文件导致的，原因有可能是：

1. 浏览器的单进程有最大内存限制（32 位进程一般是 4GB，64 位进程理论上更大，但难保浏览器自己有没有限制），导致内存分配失败或 out of memory
2. 浏览器 blob storage 可用空间不足，这个值一般是 2GB
3. 标准 ZIP 文件最大只支持 4GB，而 web 前端的 zip 库 JSZip 只支持标准 ZIP 格式，不支持 ZIP64，因此在生成 zip 文件时出现错误

由于浏览器的限制，失败的文件无法获取。建议过大的文件使用 torrent 下载，或使用官方的打包下载，或使用其他如 gallery-dl 等工具下载
