### ISSUE TITLE
GP Limit Exceeded Bug

### ISSUE THREAD

**Issue by xdfighter** [ccloli/E-Hentai-Downloader#277]
I updated the script to the newest version v1.35.2 and suddently I get GP Limit Exceeded error/warning whenever downloading old archives/galleries even though I hadn't downloaded anything the last days. Only after downgrading to v1.34.10 did it work again.

**Comment by ccloli** [comment]
Tested just now and didn't see any issue, the code about checking whether the gallery is ancient or is in peak hours is untouched.

Make sure you're not using a shared IP with others, for non-donator, your image limits is based on your IP, so maybe it's because another user is using your current IP and he used up all the limits.

If you mean the warning about your image limits may used out, then maybe you're really going to used up your image limits after you download the gallery. If that's the case, you can turn off the notification if you take it.

If you're going to download original images, then using the old verisons is not recommended, since the url rule is changed and old versions can't find it.

If you're sure it's a bug, please consider providing your runtime log, by pressing F12  on gallery page, switch to Console, start downloading, then copy all the logs started with `[EHD]` to here. If only some of the galleries have the bug, please post their gallery id here.

**Comment by xdfighter** [comment]
[EHD] E-Hentai Downloader is running. E-Hentai-Downloader.user.js:40:9
[EHD] Bugs Report > https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback E-Hentai-Downloader.user.js:41:9
[EHD] To report a bug, it's recommended to provide the logs started with "[EHD]", thanks. =w= E-Hentai-Downloader.user.js:42:9
[EHD] UserAgent > Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0 E-Hentai-Downloader.user.js:12334:9
[EHD] Script Handler > Tampermonkey E-Hentai-Downloader.user.js:12335:9
[EHD] Script Handler Version > 5.0.1 E-Hentai-Downloader.user.js:12336:9
[EHD] E-Hentai Downloader Version > 1.35.2 E-Hentai-Downloader.user.js:12337:9
[EHD] Current URL > https://exhentai.org/g/1222783/584b43818f/ E-Hentai-Downloader.user.js:12338:9
[EHD] Is Logged In > true E-Hentai-Downloader.user.js:12339:9
[EHD] E-Hentai Downloader Setting > undefined --> {"save-info-list":["title","metas","uploader-comment","page-links"],"auto-download-cancel":true,"actions-sticky":true} E-Hentai-Downloader.user.js:12294:11
[EHD] Request Resolution Setting E-Hentai-Downloader.user.js:14776:10
[EHD] Request Image Limits From e-hentai.org E-Hentai-Downloader.user.js:14633:10
[EHD] Pre-calculate estimated cost > {"cost":"27 + 283 GP","normalCost":182,"leastCost":27,"perCost":1,"gp":283,"isUsingOriginal":true,"isUsingGP":true} E-Hentai-Downloader.user.js:14853:10
[EHD] Resolution Setting > {"withoutHentaiAtHome":0,"resolution":0,"originalImages":0,"mpvAvailable":false,"timestamp":1705364997328} E-Hentai-Downloader.user.js:14789:11
[EHD] Pre-calculate estimated cost > {"cost":"27 + 283 GP","normalCost":182,"leastCost":27,"perCost":1,"gp":283,"isUsingOriginal":true,"isUsingGP":true} E-Hentai-Downloader.user.js:14853:10
[EHD] Image Limits > {"timestamp":1705364997384,"cur":"0","total":"5000","donatorPower":0} E-Hentai-Downloader.user.js:14661:12
[EHD] Is Peak Hours > false  | Is Recent Gallery > false  | Is Ancient Gallery > true  | Is Donator > false E-Hentai-Downloader.user.js:14919:10
[EHD] Pre-calculate estimated cost > {"cost":"27 + 283 GP","normalCost":182,"leastCost":27,"perCost":1,"gp":283,"isUsingOriginal":true,"isUsingGP":true} E-Hentai-Downloader.user.js:14853:10
[EHD] Index > 1  | RealIndex > 1  | Name > 01.jpg  | RetryCount > 0  | DownloadedCount > 1  | FetchCount > 5  | FailedCount > 0 E-Hentai-Downloader.user.js:12533:10
[EHD] #4: Exceed Image Viewing Limits / 509 Bandwidth Exceeded E-Hentai-Downloader.user.js:13254:14
[EHD] #4: RealIndex > 4  | ReadyState > 4  | Status > 200  | StatusText > 
Request URL > https://exhentai.org/fullimg/1222783/4/3unzcjla5io/04.png 
Final URL > https://exhentai.org/fullimg/1222783/4/3unzcjla5io/04.png 
ResposeHeaders >alt-svc: h3=":443"; ma=86400

cache-control: max-age=14400

cf-cache-status: MISS

cf-ray: 84623c3da88a1911-FRA

content-encoding: br

content-type: text/html; charset=UTF-8

date: Tue, 16 Jan 2024 00:27:54 GMT

last-modified: Tue, 16 Jan 2024 00:27:54 GMT

nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}

report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=4Zy6U21nrRsGXtvTFAMZau6RsJFlX1o13eEltbirNmqOx7aZKaN4%2ByX16extqTTZGDgv5OU9ltCEnq6qUd8fsEKpOvhOeVPRYNqbp7pMrvnyiQgxL4rfbWNMkH%2F5MdeQ0Eqa9rszaX%2BTZ0Y%3D"}],"group":"cf-nel","max_age":604800}

server: cloudflare

strict-transport-security: max-age=31536000; preload;

vary: Accept-Encoding

via: 1.1 varnish-v4

x-firefox-spdy: h2

x-varnish: 280942474

E-Hentai-Downloader.user.js:13255:14
[EHD] #5: Exceed Image Viewing Limits / 509 Bandwidth Exceeded E-Hentai-Downloader.user.js:13254:14
[EHD] #5: RealIndex > 5  | ReadyState > 4  | Status > 200  | StatusText > 
Request URL > https://exhentai.org/fullimg/1222783/5/79omumfa5io/05.png 
Final URL > https://exhentai.org/fullimg/1222783/5/79omumfa5io/05.png 
ResposeHeaders >alt-svc: h3=":443"; ma=86400

cache-control: max-age=14400

cf-cache-status: MISS

cf-ray: 84623c3da88b1911-FRA

content-encoding: br

content-type: text/html; charset=UTF-8

date: Tue, 16 Jan 2024 00:27:54 GMT

last-modified: Tue, 16 Jan 2024 00:27:54 GMT

nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}

report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=1xCxJPofTqlhoBMK7KPLi0haJioTMwBhcjEtGVCFp6XkyGaHCydw1MJjXBxvVaobNw5NACdfcCC9m4wafkb%2BN%2B%2BQh7fJIHmsNlghaZ9HozEedfOqnHrLJY4cI1GjfDUlUMR9aHASTOAhUXo%3D"}],"group":"cf-nel","max_age":604800}

server: cloudflare

strict-transport-security: max-age=31536000; preload;

vary: Accept-Encoding

via: 1.1 varnish-v4

x-firefox-spdy: h2

x-varnish: 279116849

E-Hentai-Downloader.user.js:13255:14
[EHD] Index > 3  | RealIndex > 3  | Name > 03.png  | RetryCount > 0  | DownloadedCount > 2  | FetchCount > 3  | FailedCount > 2 E-Hentai-Downloader.user.js:12533:10
[EHD] Index > 2  | RealIndex > 2  | Name > 02.png  | RetryCount > 0  | DownloadedCount > 3  | FetchCount > 2  | FailedCount > 2 E-Hentai-Downloader.user.js:12533:10
[EHD] #6: Exceed Image Viewing Limits / 509 Bandwidth Exceeded E-Hentai-Downloader.user.js:13254:14
[EHD] #6: RealIndex > 6  | ReadyState > 4  | Status > 200  | StatusText > 
Request URL > https://exhentai.org/fullimg/1222783/6/rgkcvoqa5io/06.png 
Final URL > https://exhentai.org/fullimg/1222783/6/rgkcvoqa5io/06.png 
ResposeHeaders >alt-svc: h3=":443"; ma=86400

cache-control: max-age=14400

cf-cache-status: MISS

cf-ray: 84623f81ef1a0a59-AMS

content-encoding: br

content-type: text/html; charset=UTF-8

date: Tue, 16 Jan 2024 00:30:07 GMT

last-modified: Tue, 16 Jan 2024 00:30:07 GMT

nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}

report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=%2Fm%2BinKNAnKV0Gx95WRWOOtyK50iwwmWCPDcNF%2Ftr3%2BSs0h%2Fc9iT24xyzPjzvC7N4MoofUDImRVNTIn8%2FIav%2Bulq5avdrO31wKU%2FxNGuIa1padV81sMrCGQhI5IYiGjrNj1jIo6IVNbmSwMw%3D"}],"group":"cf-nel","max_age":604800}

server: cloudflare

strict-transport-security: max-age=31536000; preload;

vary: Accept-Encoding

via: 1.1 varnish-v4

x-firefox-http3: h3

x-varnish: 283786150

E-Hentai-Downloader.user.js:13255:14

**Comment by xdfighter** [comment]
So, tried downloading the archive again with newest version, after 3 successful downloads - more than last time - it stops with "Failed! (Exceed Limits/GPs)" failure. Even tho' my limit is 0 at the start of the download and the gp cost don't exceed my max-limit 5000. Kinda strange, it's only for some galleries if they are older.

Thanks for help.

**Comment by ccloli** [comment]
> [EHD] https://github.com/ccloli/E-Hentai-Downloader/issues/4: Exceed Image Viewing Limits / 509 Bandwidth Exceeded

The error is returned from server, I think it's because you have already used up all your GPs and credits. The old version works is only because it can only downloads resampled images due to a site update.

Downloading 1 year old galleries (and 90+ days galleries  during peak hours)  in original quality requires GP, and if you don't have enough GP, EH will exchange it automatically based on the high rate of recent transaction (around 300 credits to 1k GP)

You can navigate to https://e-hentai.org/exchange.php?t=gp to see how many GPs and credits left.

**Comment by xdfighter** [comment]
Ok, I think I understand now. I have 71 Credits but no GP and original images require GP, which I can exchange for Credits.
I was confused because it said "Exceed Image Viewing Limits" and my limit is on 0.

So I just have to disable original image download for older galleries.
Thanks alot.
