### ISSUE TITLE
关于检测脚本更新

### ISSUE THREAD

**Issue by Mapaler** [ccloli/E-Hentai-Downloader#28]
[Pixiv++](https://openuserjs.org/scripts/TimidScript/[TS]_Pixiv++)看起来就是个超强大的脚本，还自带更新检测功能。之前说到的把库放在@requier里，你可以每次升级你的版本的时候检测这些库是否有更新了。
![image 1](https://cloud.githubusercontent.com/assets/6565860/14694869/43c6a03a-079f-11e6-9a76-cfa05b48c49d.jpg)

**Comment by ccloli** [comment]
如果您是指库的自动更新，如你所见，JSZip 3.0 的 API 与 JSZip 2.x 的 API 有些许的不同。如果在不改动源码的情况下直接使用新版本会让脚本无法使用。

如果您是指脚本的自动更新，GreaseMonkey 和 Tampermonkey 等都有自己的检查更新机制，所以再提供版本更新提醒并没有什么意义。

另外 GreasyFork 对 require 的资源有严格的限定，只能使用白名单内的资源，而这些资源不能保证能及时更新。

**Comment by Mapaler** [comment]
肯定不会老版本也更新新版本的啦……
你的脚本建一个version的本地储存，检测到比当前脚本小说明脚本已经更新了，于是启动更新检查机制。获得当前库的版本和需要版本进行比对，发现不满足需求就提示更新。
当然如果只能白名单的话那就没什么意义了。

**Comment by ccloli** [comment]
并不是很能理解您的意思。

如果你的意思是检测库的版本号发现需要更新了，就让用户更新脚本的话，我觉得并没有什么意义。GreaseMonkey 与 Tampermonkey 会自动访问脚本的更新地址获取更新，所以我觉得多此一举没有什么必要。单纯检测库的版本是否能在当前版本运行，不如直接让用户更新脚本。

而且同样的，由于新版本可能会存在一些问题，所以会有用户希望使用旧版本（GreasyFork 会保存每一个版本供用户回退），那么如果出现 require 的库不能兼容的问题会有种强迫用户使用新版本的感觉。

另外无论是将库 require 进来还是直接将库附加在脚本上，我觉得对用户的使用来说没有太多差别，而且在经历过 require 的脚本源被墙之后，我认为后者会比前者更能保证稳定性。
