### ISSUE TITLE
Safari下载完成后不能生成Zip文件

### ISSUE THREAD

**Issue by Kk0ngOnGitHub** [ccloli/E-Hentai-Downloader#281]
抱歉我今天刚刚开始使用e-hantai
我知道我不能访问原始文件，因为我没有足够的GP（我还不清楚这是什么）
所以在我勾选不下载原始文件后可以成功下载。

### **但不能生成Zip文件，会卡死在 “Generating Zip file...” 进度条完全不动**
未下载完成时，点击上方强制获取图像按钮，得到的Zip解压后只能得到txt文件
（在解压后得到的一个名称为一串数字的文件夹内）
下载完成后就会卡死在生成Zip文件的步骤，进度条完全没有任何进展
我有看到类似的issue报告，但没有找到解决办法。

抱歉我不太懂编程相关知识，我已经尽可能把环境和问题描述清楚
如果您需要更多信息（日志）请直接告诉我，我会尽力找到。

如果macOS上的其他浏览器（Chrome或Firefox）可以正常下载，也请您告诉我，感谢
但我还是更想使用原生Safari浏览器进行下载，以上

M1Pro  Safari 17.2.1  macOS 14.2.1
Tempermonkey 4.17.6162  E-Hantai Downloader 1.35.2

<img width="548" alt="Screenshot 2024-02-22 at 00 25 40" src="https://github.com/ccloli/E-Hentai-Downloader/assets/140964582/9f4c80d6-de7b-4a53-8f79-b715058b5955">

**Comment by ccloli** [comment]
手上没有 macOS 设备，所以不太方便测试，可以尝试参考 https://support.apple.com/zh-cn/guide/safari/sfri20948/mac  开启开发者模式，然后在开发者工具内切换到 Console / 控制台，然后开始下载，将输出的 `[EHD]` 开头的日志粘贴到此。

不过感觉这个报错不像是脚本的问题，更像是 Tampermonkey 的跨域数据获取存在问题，所以从目前的推测看感觉不好解决。理论上你可以使用 Chrome 或 Firefox，然后安装 Tampermonkey 或 Violentmonkey 再试试，应该会比 Safari 的问题少一些。

**Comment by Kk0ngOnGitHub** [comment]
请问是哪个？
<img width="1624" alt="Screenshot 2024-02-25 at 00 35 18" src="https://github.com/ccloli/E-Hentai-Downloader/assets/140964582/024b6f2b-4568-4a6e-9e56-21aaf2083e06">

**Comment by ccloli** [comment]
> ReferenceError: Can't find variable: abData

看了下，这个错误确实是脚本的问题，给未定义的变量赋值了。一般不会走到这个位置，后面会处理下。

![image](https://github.com/ccloli/E-Hentai-Downloader/assets/8115912/421576e2-b996-4465-8c69-8854b8e96a36)


不过问题是，这个错误其实是从错误捕获语句里抛出来的，而捕获到的错误是在生成 zip 时从 JSZip 库里抛出来的。换句话说，引起错误的根本原因还是在 Safari 上无法正常生成 zip 文件。所以修复这个错误并不能解决你的问题，这应该是浏览器与 Tampermonkey 的兼容性问题。

如果你想尝试提供更多错误信息的话，可以修改脚本的源码，删除第 12674 行的 `abData = undefined;` 这一行代码。不过这只是让错误信息暴露出来而已，我个人觉得既然这个错误出现在上游的第三方库中，应该也是无法解决的。最好的方式还是更换浏览器，例如换用 Firefox 或 Chrome 配合 Tampermonkey 或 ViolentMonkey 使用。

**Comment by Kk0ngOnGitHub** [comment]
这一条吗？
<img width="1624" alt="Screenshot 2024-02-25 at 01 06 19" src="https://github.com/ccloli/E-Hentai-Downloader/assets/140964582/b20ae15b-8dd0-48c0-b5d2-4f4c4c21a50b">
好的，我会尝试下Chrome和Firefox，谢谢您

**Comment by ccloli** [comment]
是的，你可以在 Tampermonkey 里将脚本的这一行代码删除，此时应该会显示实际的错误信息，不过我觉得不会对解决问题有太大帮助

**Comment by Kk0ngOnGitHub** [comment]
我已经下载了Firefox，希望这里一切正常，感谢您的帮助
<img width="1512" alt="Screenshot 2024-02-25 at 01 19 11" src="https://github.com/ccloli/E-Hentai-Downloader/assets/140964582/cb83c348-2ea4-48e3-8fbd-22f54f8cd657">
（我就不修改了）

**Comment by Kk0ngOnGitHub** [comment]
Firefox上没有问题了，下载很快，感谢开发
