### ISSUE TITLE
中间的下载按钮消失

### ISSUE THREAD

**Issue by noti0na1** [ccloli/E-Hentai-Downloader#29]
这两天突然发现页面中间的下载框不见了。。。
E-Hentai Downloader 1.21.3
Chrome 版本 52.0.2723.2 dev-m (64-bit)

**Comment by ccloli** [comment]
在以下平台测试没有发现问题，清除脚本数据后也一切正常。
```
Tampermonkey BETA v4.1.5222 + Chrome 50.0.2661.94 
GreaseMonkey 3.8 + Firefox 45.0.2
Tampermonkey v4.0.5054 + Firefox Nightly 48.0a1
```
能提供更多的信息吗？比如出现问题的页面，按下 F12 -> Console 的报错信息之类的？

**Comment by noti0na1** [comment]
<img width="960" alt="default" src="https://cloud.githubusercontent.com/assets/8036790/15129739/9bc41a08-1611-11e6-97ad-7f97643e2aaf.PNG">

Tampermonkey 4.0.25

**Comment by noti0na1** [comment]
嗯，我换成Tampermonkey Bete 4.1.5224后，虽然还是报错，但可以用了。
还有就是，下载时CPU占用略高，进度条偶尔会卡住然后页面崩溃。

**Comment by ccloli** [comment]
那个报错是来自 FileSaver.js 的，不过很奇怪，`document.createElementNS` 应该没问题。我这里已有的环境不能复现，很抱歉暂时不能解决。

CPU 占用率高是 Tampermonkey 的锅，Tampermonkey 在接收 `responseType: 'arraybuffer'` 的数据时还是当作字符串（`String`）来处理的，在使用返回的数据时再转为 `ArrayBuffer` 对象，所以在转换的时候会导致当前标签页卡顿。如果你有用过 Firefox 的 GreaseMonkey 或者 Opera 的 Violentmonkey 的话是没有这个问题的。现在的版本已经将返回的数据缓存了，所以卡顿现象已经有一些改善了，之前的版本会卡顿更长的时间。

这个问题我在项目的 Readme 里提到过，也给 Tampermonkey 提交过这个问题（ https://github.com/Tampermonkey/tampermonkey/issues/279 ） ，不过现在还没有回复，只能先暂时这样了。

**Comment by noti0na1** [comment]
感谢回复，我现在用测试版也没什么问题了。
恩，确实感觉没以前卡。。。
