### ISSUE TITLE
最近开始突然每次下载都必有几个失败的，设置调整没有用

### ISSUE THREAD

**Issue by AchtHS** [ccloli/E-Hentai-Downloader#293]
设置改成了每个图重复下多次以及下载前停顿一会儿都没用，下载每个图资源都是这样，十分奇怪。而且重试的时候都必然在这几个图上再次超时。
提示的是Timed Out。是不是官方针对这个脚本做的调整？麻烦试验下。
我用的是最新版的edge浏览器，之前从来没有这种问题，只是最近一个月左右吧有这种现象。
版本 127.0.2651.86 (正式版本) (64 位)
我换谷歌浏览器也是一样。
（EX的）/g/2326427/3aed890b88/ 以这个为例，都是#35和#44超时。麻烦看下

**Comment by AchtHS** [comment]
设置了下，现在可以在最后重新自动下载了。但是这个现象确实奇怪，就是最近才出现的。

**Comment by ccloli** [comment]
测试无问题，大概率是与分配的 H@H 节点网络连接不稳定，一般失败后重新下载触发从源站下载可以解决
