### ISSUE TITLE
stuck fetching images

### ISSUE THREAD

**Issue by balonballot** [ccloli/E-Hentai-Downloader#3]
I don't know why but I just noticed today that the script just stuck on fetching images with no progress at all. 
Fetching Image 1: page1.png ...
Fetching Image 2: page2.png ...
Fetching Image 3: page3.png ...
Fetching Image 4: page4.png ...
Fetching Image 5: page5.png ... 

then nothing. I don't know what could be the problem. How to check?

**Comment by ccloli** [comment]
Someone also told me that, but I'm not sure what's wrong with it. 
If possible, please press F12 on E-Hentai Gallery and switch to Console tab, and then click "Download Archive". 
If it showed some warning messages from E-Hentai-Downloader.user.js (in Chrome it may from a script named "VM****"), copy all the logs and paste them here.
If no warning when it stuck, please also copy all the logs to here.
Thanks.

**Comment by balonballot** [comment]
i'm not sure where to look but all looked normal to me. Was this right?

Unknown property 'user-select'.  Declaration dropped. x.css:195:88
[EHD] E-Hentai Downloader is running. E-Hentai_Downloader.user.js:23:1
[EHD] Bugs Report > "https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback" E-Hentai_Downloader.user.js:24:1
[EHD] To report a bug, showing all the "[EHD]" logs is wonderful. =w= E-Hentai_Downloader.user.js:25:1
[EHD] UserAgent > Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 E-Hentai_Downloader.user.js:9472:1
[EHD] Script Handler > GreaseMonkey E-Hentai_Downloader.user.js:9473:1
[EHD] GreaseMonkey / Tampermonkey Version > 3.3 E-Hentai_Downloader.user.js:9474:1
[EHD] E-Hentai Downloader Version > 1.12.1 E-Hentai_Downloader.user.js:9475:1
[EHD] E-Hentai Downloader Setting > {} E-Hentai_Downloader.user.js:9476:1
[EHD] Current URL > "http://exhentai.org/g/842814/7c4b44c597/" E-Hentai_Downloader.user.js:9477:1
[EHD] Is Logged In > true E-Hentai_Downloader.user.js:9478:1
[EHD] Index > 1  | DownloadedCount > 1  | FetchCount > 5 E-Hentai_Downloader.user.js:9658:3
[EHD] Index > 2  | DownloadedCount > 2  | FetchCount > 4 E-Hentai_Downloader.user.js:9658:3
[EHD] Index > 3  | DownloadedCount > 3  | FetchCount > 3 E-Hentai_Downloader.user.js:9658:3
[EHD] Index > 5  | DownloadedCount > 4  | FetchCount > 2 E-Hentai_Downloader.user.js:9658:3
[EHD] Index > 4  | DownloadedCount > 5  | FetchCount > 1 E-Hentai_Downloader.user.js:9658:3

**Comment by ccloli** [comment]
Thanks for your feedback. This bug occurs on updating dialog box, and I'm not sure where it happened. But I rewrited the way to show downloading information a few hours ago, so this bug may fixed by chance. The new version will be pushed soon, so please be patient and wait for the release.

**Comment by ccloli** [comment]
New version has been pushed, please check is the bug still exist or not, thanks.

**Comment by balonballot** [comment]
thank you so much! it worked flawlessly. Thank you also for adding the progress bar. It's so much better and helpful in seeing if the download stuck or anything. Since I realized that sometimes some pages can't be downloaded do to the server connection, probably.

**Comment by ccloli** [comment]
E-Hentai is a P2P site, so network may not stable. Anyway, enjoy it. :cat:
