### ISSUE TITLE
Can the script number images after their position in the gallery

### ISSUE THREAD

**Issue by Triramama** [ccloli/E-Hentai-Downloader#302]
It would make more sense than starting from 1.
They would still be in order AND filename would communicate which pages the pictures are.
I needed to download a large gallery and had to split it into parts like part 1, 1-100 pics; part 2, 101-200 pics, etc, in that gallery all images are ordered not alphabetically, so if i download them without numbering they would be misplaced and if i wanted to combine the aforementioned parts of that gallery  which I downloaded with option "number images" i would screw up because they all numbered from 1 instead of being numbered with their position on the website.  
Hope you can pick up what I'm putting down Broccoli, cheers!

**Comment by ccloli** [comment]
Probably you can try enabling Settings -> Basic -> _Number images with original page number if pages range is set_ , which will use the original page number.

**Comment by Triramama** [comment]
that was such an option? well forgive for being retarded
