### ISSUE TITLE
the default file name can be changed to the original title (Japanese)

### ISSUE THREAD

**Issue by bearcloney** [ccloli/E-Hentai-Downloader#308]
I would like to add an option to change the default file name of the downloaded file to the original title (Japanese).

path name can default to the English title (not important)

I hope you can consider it, thank you

**Comment by ccloli** [comment]
In script settings, you can set file name to `{subtitle}`, and path name to `{title}`.

**Comment by bearcloney** [comment]
> In script settings, you can set file name to `{subtitle}`, and path name to `{title}`.

Thanks
