### ISSUE TITLE
Downloading problem

### ISSUE THREAD

**Issue by stevenxqs** [ccloli/E-Hentai-Downloader#31]
不知道为啥每次同时下载的数张图中总会出现几个0kb/s，且retry时还是下载失败，火狐和chrome都是这个问题Orz

**Comment by ccloli** [comment]
最近有遇到这个问题，本来以为是 Tampermonkey 或者 Chrome 的锅，不过现在从您的反馈看起来并不是，而且从我后来的测试看来下载无速度应该是遇到了服务器的并发限制。目前错误的情况不是特别明朗，上一个版本就是想修复你遇到的这个问题，但是看来并没有起多大作用，打算有空的话和旧版本比对下找出错误的原因。

现在个人推测可能与速度没有更新时自动显示 0KB/s 并开启了速度检测有关，因为刚刚在测试新增加的功能时发现下载完成并保存 Zip 文件后还会触发多次下载（Downloaded Count 也变为负数），触发原因显示是“Speed Too Low”，不过我现在还暂时无法复现。目前状况暂时存疑，如果您有比较有用的情报也请告诉我，谢谢。

如果暂时不能忍受 bug 的话可以先尝试回退版本，理论上在添加该功能前的 [1.20](https://github.com/ccloli/E-Hentai-Downloader/tree/ed231d57f97360fffa59d12df9e4c727c095866c) 版本应该是正常的。

***

For Non-Chinese User:

Here is an report says that when downloading some images at the same time, some of them are no speed, and retry them don't work effectively. Thought I tried to fixed it in previous version, it seems that it doesn't work, too. It would probably be a bug in new version which includes speed detect function (and it may also lead to download Zip file repeatedly).

However, I'm not sure what's going on with it, if you have any news, please feedback here. And if you are a bit mad with it, try rolling back to old version which without speed detect, likes [1.20](https://github.com/ccloli/E-Hentai-Downloader/tree/ed231d57f97360fffa59d12df9e4c727c095866c).

Sorry for any annoyance.

**Comment by stevenxqs** [comment]
多谢您的答复，经过我仔细的检查，关于我个人的问题应该是出在本机系统区域设置上（尤其是非UNICODE编码程序的）。因为突然发现其他压缩包中出现了乱码的情况，后经反复调试终于恢复了正常，downloader也可以正常使用了。很抱歉因为个人的原因给您造成麻烦，并再一次感谢您的付出！
----------------------------------------------------------------------------------------------------------------------------------
此外个人在使用的过程中有这样的一个感受：总是不太确定具体的内存（每张图的大小是未知的）限制导致整体下载完成后才能得知Out_Of_Memory，不知道能否实现在内存越界的位置保存之前下载成功的任务呢？——只是个人的小疑问，现在基本采取谨慎的分段下载政策

**Comment by ccloli** [comment]
不是很明白系统的区域设置与这个 bug 的关系，不过如果你指的是压缩包乱码的话，JSZip 存储文件名、文本、注释等都是以 UTF-8 的形式存储的，如果解压缩程序不支持的话可能会有些问题（比如大部分解压缩程序都不支持 UTF-8 编码的压缩文件注释，非英文字符会乱码）。

关于内存不足的问题可以参考这个 wiki 页面 https://github.com/ccloli/E-Hentai-Downloader/wiki/Can't-make-Zip-file-successfully 以及所有标记了 `out of memory` 这个 tag 的 issue。这个大多数情况下是用户设备的内存可用量不足导致的，Google Chrome 自身倒是能比较好地处理这个问题，Firefox 就是会直接抛出错误了。其实很早以前就考虑实现自动分割文件的功能了（现在也在 plan list 中），不过目前优先级不是很大，自己也感觉有些无从下手，所以先暂时搁置了。

**Comment by stevenxqs** [comment]
十分感谢！

**Comment by ccloli** [comment]
This bug should probably related to https://github.com/Tampermonkey/tampermonkey/issues/298

**Comment by po456asd** [comment]
i thought i have that problem alone. lol
how i can rollback to 1.20?

**Comment by ccloli** [comment]
@po456asd If you are using Tampermonkey, I think roll back to earlier version won't work because it's a bug caused by Tampermonkey (https://github.com/ccloli/E-Hentai-Downloader/issues/31#issuecomment-222729180). However, if you are using other extensions like GreaseMonkey and ViolentMonkey and also have this problem, please let me know if you have any details.

**Comment by ccloli** [comment]
This bug has been fixed since Tampermonkey marked the related issue as fixed.
