### ISSUE TITLE
No longer works, stuck on "Fetching Gallery Pages URL (1/2) ..."

### ISSUE THREAD

**Issue by 424778940z** [ccloli/E-Hentai-Downloader#311]
As title suggests, all downloads stuck on "Fetching Gallery Pages URL (1/2) ...".
Using Chrome 130.0.6723.59
Tested both under Tampermonkey and Violentmonkey

Error in console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at xhr.onload (E-Hentai Downloader.user.js:13836:58)
```

**Comment by Twilicious** [comment]
Seems they changed some stuff for thumbnail and image loading and broke basically all my scripts.
Here's the changelog: https://forums.e-hentai.org/index.php?showtopic=244935
Here's a sample of the code that was supposedly changed. https://forums.e-hentai.org/index.php?s=&showtopic=199743&view=findpost&p=6559928

**Comment by Spenserty** [comment]
Hopefully the Script gets updated

**Comment by Hydrapony** [comment]
搜索这一行：

**Comment by 70338** [comment]
> 搜索这一行：
> 
> `var pagesURL = responseText.split('<div id="gdt">')[1]`
> 
> 改成：
> 
> `var pagesURL = responseText.split('<div id="gdt"')[1]`
> 
> 就行了

試過了仍然有問題，有些圖片網址沒能正確解析下載

**Comment by 70338** [comment]
> ```
> 将           var pagesURL = responseText.split('<div id="gdt">')[1]
> 修改为    var pagesURL = xhr.responseText.split('<div id="gdt" class="gt200">')[1]
> ```

還是有Response Error的狀況

**Comment by Hydrapony** [comment]
> > ```
> > 将           var pagesURL = responseText.split('<div id="gdt">')[1]
> > 修改为    var pagesURL = xhr.responseText.split('<div id="gdt" class="gt200">')[1]
> > ```
> 
> 還是有Response Error的狀況

Response Error的时候其实已经下载完了，pause然后下载当前已成功的图片，就是完整的文件。具体等作者修吧。

**Comment by 70338** [comment]
> > > ```
> > > 将           var pagesURL = responseText.split('<div id="gdt">')[1]
> > > 修改为    var pagesURL = xhr.responseText.split('<div id="gdt" class="gt200">')[1]
> > > ```
> > 
> > 
> > 還是有Response Error的狀況
> 
> Response Error的时候其实已经下载完了，pause然后下载当前已成功的图片，就是完整的文件。具体等作者修吧。

確實檔案都在，感謝兩位

**Comment by ccloli** [comment]
Should be fixed in v1.35.4, lmk if it works for you.

**Comment by Galerd** [comment]
> Should be fixed in v1.35.4, lmk if it works for you.

Worked for me, thank you

**Comment by 70338** [comment]
Thank you sir!

**Comment by Asinin3** [comment]
Works on the dnsev eze branch too. Thanks

**Comment by fururebyworks** [comment]
its working, Thank you very much for the quick update.
