### ISSUE TITLE
Dowloader box no longer appears

### ISSUE THREAD

**Issue by TrueMurakumo** [ccloli/E-Hentai-Downloader#312]
So I'm using Chrome version 130.0.6723.70 (Official Build) (arm64), Tampermonkey 5.3.1, and the E-Dowloader script version 1.35.4.

Today whenever I visit a page to download an archive as a zip file the download box is nowhere to be seen so I can't download anything as a zip file. I checked if I have the script enabled in the Tampermonkey extension and it is enabled, plus I also have it enabled in the pinned extensions. Tampermonkey also has permission to access all pages in Chrome.

Initially I tried refreshing the page and it still didn't appear, then I tried several different pages on the site and still got nothing. Next I tried restarting my browser then tried restarting my laptop and still got nothing.

Once I saw that refreshing and restarting wasn't yielding any results I have tried uninstalling and reinstalling the script and it didn't work, then tried uninstalling and reinstalling Tampermonkey and it didn't work, heck I even tried uninstalling and reinstalling google chrome and that didn't work.

The only userscript extension I use is Tampermonkey as I have had no need to use any other userscript extention at all and haven't had any problems using this script in the past, and I've been using it for years with no problems before.

I honestly don't know why this is happening as it was working fine yesterday but today the download box just isn't there at all and me trying to disable and reenable everything hasn't yielded any results.

**Comment by my2thpick** [comment]
Same here. No box is show. Before it was still there.

**Comment by ccloli** [comment]
Tested just now and it works fine on EH (with and without login) and EX (including the onion site). Please provide runtime log for investigation, by pressing F12 and switching to Console tab, then copy everything started with `[EHD]` then paste them here.

**Comment by TrueMurakumo** [comment]
I tried the f12 and switching to console tab first to get the log, but didn't see anything with [EHD] in the log so in frustration I just uninstalled and then reinstalled both tampermonkey and the e-hentai downloader script and then it just appeared again!

I don't know why uninstalled both of them worked today compared to yesterday, but hey I'm glad that the issue was somehow resolved!

**Comment by my2thpick** [comment]
> Tested just now and it works fine on EH (with and without login) and EX (including the onion site). Please provide runtime log for investigation, by pressing F12 and switching to Console tab, then copy everything started with `[EHD]` then paste them here.

Thank you for support. It's working today out of thin air, don't know why.

**Comment by ccloli** [comment]
https://forums.e-hentai.org/index.php?showtopic=280292

https://forums.e-hentai.org/index.php?showtopic=280294

I saw some posts on EH forums, some other scripts are broken, too, and it's before the site updates. So I'm assuming it's a bug related to Chrome's Manifest V3 extension policy and Tampermonkey themselves. I'm using Tampermonkey BETA and do see some weird behavior before, but later it fixed itself somehow, probably all of them are related to V3 shit.
