### ISSUE TITLE
对于图库中较大的图片（>5MB）会连续报失败！(Network Error)并无限重复重试

### ISSUE THREAD

**Issue by yuban01652** [ccloli/E-Hentai-Downloader#314]
浏览器 chrome 130.0.6723.92
脚本版本 1.35.4
脚本管理器 tampermonkey 5.3.1

当下载图库中存在文件较大的图片时（测试下来一般为大于5MB时）下载脚本会报 失败！(Network Error)，并不断重试
如刚找的下列图库
/g/3118797/261ef4702f/

报错信息：
[EHD] #1: Network Error
userscript.html?name=E-Hentai-Downloader.user.js&id=07fb8c56-a19f-46d3-9c9d-fd6b25adbe31:13557 [EHD] #1: RealIndex > 1  | ReadyState > 4  | Status > 0  | StatusText > 
Request URL > https://exhentai.org/fullimg/3118797/1/oe0jts4ab2m/_01.jpg 
Final URL > https://exhentai.org/fullimg/3118797/1/oe0jts4ab2m/_01.jpg 
ResposeHeaders >
userscript.html?name=E-Hentai-Downloader.user.js&id=07fb8c56-a19f-46d3-9c9d-fd6b25adbe31:12889 [EHD] Index > 1  | RealIndex > 1  | Name > _01.webp  | RetryCount > 0  | DownloadedCount > 0  | FetchCount > 1  | FailedCount > 0

已测试在浏览器点开图片原始链接能够正常查看图片
注：只会在图片很大时报错，对同一图库的其他小图片能正常下载，最后会在几个大图片无限循环。感觉上像是图片太大哪里超时了，让脚本以为网络有问题

**Comment by ccloli** [comment]
可能和 https://github.com/ccloli/E-Hentai-Downloader/issues/187#issuecomment-1113166051 有关，建议检查 Chrome 缓存所在的硬盘剩余空间是否充足。若问题与上述原因无关，则可能是 Chrome 或 Tampermonkey 关于 Manifest V3 的 bug，可以尝试换用 ViolentMonkey 试试看。

**Comment by yuban01652** [comment]
感谢大佬，将硬盘整理后正常工作了
