### ISSUE TITLE
下载和设置按钮都消失了

### ISSUE THREAD

**Issue by AchtHS** [ccloli/E-Hentai-Downloader#316]
重装了几次，而且用不同浏览器都试了，插件开着但是页面里没有下载和设置按钮了

**Comment by AchtHS** [comment]
> 已测试并确认工作正常，暂无法复现该问题。请确认用户脚本扩展程序已启用脚本，对于 Chrome 可能需要开启扩展程序的开发者模式，具体参见 https://www.tampermonkey.net/faq.php#Q209
> 
> 若以上操作执行后仍无效，请按下 F12 切换到 Console / 控制台标签，然后将日志复制粘贴至此

感谢，我试了几次又有了，我也没法复现了。。

**Comment by shd635** [comment]
感谢，我也是这个问题，终于解决了
