### ISSUE TITLE
[Request] Always show download status on tab title.

### ISSUE THREAD

**Issue by iShyboy** [ccloli/E-Hentai-Downloader#33]
- [x] Add a checkbox to always show the download status on tab title.
- [X] Change status text.

Can you please add a checkbox to always show the download status on tab title?
And a input box to customize the status title (It takes to much space in tab title).
![changed](http://i.imgur.com/YiMwZwH.png)
I could do this manually but it would always change back when the script get updated.

**Comment by ccloli** [comment]
Will have a try. However here are some serious bugs that make me mad, so I want to fix them firstly. BTW the final exams are coming, so I probably don't have so much time in these month. That means it may take more time than before. Sorry for that.

**Comment by iShyboy** [comment]
No harm. I'll be changing the script in my side while you implement this.

**Comment by iShyboy** [comment]
Half work done, I've already done the change on my side, and the box is checked on the script. Thanks for the work.

**Comment by ccloli** [comment]
I thought setting custom status text is a little useless, so I just removed the useless prefix `EHD: `. Now it shows like `[↓ 12/25]` and `[√]`. Is that okay?

**Comment by iShyboy** [comment]
More than enough. '↓' for 'download' its as good as '√' for 'complete'.
I'll close this for now.
