### ISSUE TITLE
遇上下载错误无法结束下载

### ISSUE THREAD

**Issue by noti0na1** [ccloli/E-Hentai-Downloader#34]
在下载大量图片时（200+），会遇上部分图片下载失败。我记得以前的版本会问是否重下，然而我现在遇到的是下载失败后仍被归为下载中，纵使那个进度条右边显示已失败。

Chrome：52.0.2739.0 dev-m (64-bit)
Tampermonkey：v4.1.5240
E-Hentai Downloader：1.21.5
电脑开了SS

<img width="407" alt="default" src="https://cloud.githubusercontent.com/assets/8036790/15490134/a4311b28-2133-11e6-94cb-1fda488b3a5e.PNG">
<img width="929" alt="1" src="https://cloud.githubusercontent.com/assets/8036790/15490136/a65592f8-2133-11e6-9c7b-b2f22bf324ea.PNG">
<img width="932" alt="2" src="https://cloud.githubusercontent.com/assets/8036790/15490137/a7d9aefc-2133-11e6-9d16-3e839e1b0d18.PNG">

**Comment by ccloli** [comment]
黄色的表示的是下载失败并正在尝试重新下载，不过不能使用 `abort()` 方法这个地方有点奇怪，估计是逻辑错误，有时间我排查下。
我觉得现在应该顺便加个强制下载已完成文件的功能，要不然遇到 bug 卡死后就前功尽弃了 = =

**Comment by noti0na1** [comment]
哭，我就是。下了好几遍都是卡在一两个图片上了(;_;

**Comment by ccloli** [comment]
新版本已推送，这个 bug 临时解决了下，不过触发原因还暂时没有找到 = =

另外增加了强制保存已下载图片的功能，如果下载时出现报错导致下载无法继续进行的话，将鼠标移至进度框内，会显示一个强制下载文件的链接（或者 F12 在控制台输入 `getzip()` 也行）
![qq 20160527180849](https://cloud.githubusercontent.com/assets/8115912/15605058/1feb6bb0-2436-11e6-95cf-7b024bd411b3.png)

**Comment by ccloli** [comment]
此 bug 可能与 Tampermonkey 的新版本有关，已提交 issue。

This bug should probably related to https://github.com/Tampermonkey/tampermonkey/issues/297
