### ISSUE TITLE
Any way to download using this script even if image limit is reached?

### ISSUE THREAD

**Issue by YukiSakuma** [ccloli/E-Hentai-Downloader#35]
So I'm like at 37000+  towards a limit of 5000 and it needs credits of 76k to reset and I don't know when will ever go back to below the limit,
I have like 8k credits right now. I am using this script especially when there are no torrents available.
So yeah my fault I downloaded large gallery files in a single day but some of them didn't even complete the download because of the image limit.

**Comment by iShyboy** [comment]
No can do, you can go to hentaiverse, fight for some time, earn some credits and change into GP to reset your limit.

**Comment by YukiSakuma** [comment]
It upped to 79k credits that is needed to reset WTF?

**Comment by iShyboy** [comment]
![gp](http://i.imgur.com/FuQ9hMV.png)
It show in GP, 1kg and 1kc it's vastly different. But if it was 79k credits I think that it is impossible.

**Comment by YukiSakuma** [comment]
Here is mine 
![image](https://cloud.githubusercontent.com/assets/16185735/15588843/7371c44c-23c2-11e6-9a08-3f22936cddf7.png)

**Comment by iShyboy** [comment]
Wow, that sound weird, you should get some 80kgp and try reset this, if no you can seek help in the forum. Credit to reset limit is weird.

**Comment by YukiSakuma** [comment]
Sorry but I don't even use the GP exchange and I barely use hentaiverse (lv. 15). So I don't know what kgp is ...

**Comment by iShyboy** [comment]
![gpexchange](http://i.imgur.com/fY9iDDf.png)
See how much gp you have, take some credits and seek 80kg+ and try reset the limit, 79kc to reset browsing limit sound like nosense.

**Comment by YukiSakuma** [comment]
here
![image](https://cloud.githubusercontent.com/assets/16185735/15589053/a76b3886-23c3-11e6-9d54-a250034bb4ef.png)

**Comment by iShyboy** [comment]
Good, make an offer of 78kgp and the price you want to buy the kgp the higher the price you want to buy, the faster its done.

**Comment by YukiSakuma** [comment]
I input 78kgp at 200 Credits but is says Insufficient credits I have like 8k credits.

**Comment by iShyboy** [comment]
Right, 8000/215=37,20 kgp.
you can only buy this much.

**Comment by YukiSakuma** [comment]
I managed to bid for 80kGP at 110 credits but I don't know if it will succeed but how would I know?

**Comment by iShyboy** [comment]
It won't work, its business, like stock.

One KGP is 213~215 credits, how could someone sell one kgp at 110 credits?

**Comment by YukiSakuma** [comment]
Even if it I managed to buy I wouldn't be able to reset because as you said one kGP=213-215 credits, 79542 credits would need 370-375kGP

**Comment by YukiSakuma** [comment]
I bought 40kGP at 215 credits in an instant

**Comment by iShyboy** [comment]
Nope, you can wait for the cost to reset lessen. Since its 3 per minute.

**Comment by YukiSakuma** [comment]
That'll be like waiting for 17 days assuming kgp=215C to be able to use my kGP to reset.

**Comment by iShyboy** [comment]
Nope look, by the image,
39771 browsing points
79542 gps(i think) needed.
79542/39771 = 2
each point is 2 gps, sooo.
79542 - 40000 (gp you have)= 39542 (gp you would need to wait for).
39542/2= 19771 (browsing points you must wait before using those 40kgp to reset your limit).
19771/180 (browsing points freed per hour)=109,84hours
109,84/24=4,58 days. You need to wait ~5 days before reseting your limit, or ear some credits in the meantime and buy more gp.

**Comment by YukiSakuma** [comment]
Wait so 1kGP=1000GP In terms of image limits? So that's why my calculation is far off.
T

**Comment by iShyboy** [comment]
1k= 1000 ever since... ever? You must have thought that kgp was a thing in itself. But yes, is not that bad. You can earn some more credits and exchange in gp, the more the sooner you can reset.

**Comment by YukiSakuma** [comment]
I thought kGP is based on the price per kGP on the GP exchange

**Comment by ccloli** [comment]
Sorry to hear that ;-( I think it shouldn't take so many image viewing limits, since I tried detecting it and forced to stop downloading if it reaches the limit. However I don't have a test because I never reached the limit (I'm also not a strong user of E-Hentai), sorry again for that.

If you don't have so much GP or credits, a quick but not a safety way is to use proxy, since E-Hentai records your limits normally based on your IP, so if you changed your IP, it should work again (also if your IP is dynamically -- means that if you connected to the network again, you'll get a new IP -- tried disconnect and connect to the network again).

**Comment by dodying** [comment]
What's your E-Hentai username?
I think I can give you 80K Credits as a present by MoogleMail.

**Comment by iShyboy** [comment]
It's normal for it to be sized in credits? The most of points that I get past my limit was 2k or 12k in total, and it was only a few tens of thousands gp. Never credits.

**Comment by ccloli** [comment]
@iShyboy It seems that if you don't have so much GP, it'll use credits automatically. 

e.g. I have only 2k GP.
![qq 20160527102513](https://cloud.githubusercontent.com/assets/8115912/15595937/cb9e43b0-23f5-11e6-8cb9-0771092ea37b.png)

If my image limit is not so big, it uses GP by default.
![qq 20160527102604](https://cloud.githubusercontent.com/assets/8115912/15595961/07218e4c-23f6-11e6-81a1-51e52ec94144.png)

But when I can't afford it with GP, it'll use credits.
![qq 20160527102735](https://cloud.githubusercontent.com/assets/8115912/15595981/3a2c2e46-23f6-11e6-9e56-f4bd49a0103b.png)

BTW, changing IP is works for me, if I use proxy to access E-Hentai, my image limit is reset to zero.
![qq 20160527103312](https://cloud.githubusercontent.com/assets/8115912/15596035/93b02936-23f6-11e6-9ba3-e9288ac31ede.png)

**Comment by iShyboy** [comment]
Expensive!! hey, I'll stay tuned to always let at least a few thousands gp. Since I only have 4k credits :D my limit isn't a bother too, is near impossible to go over it only downloading some doujins/mangas. Still since I don't have a way to change my Ip, only by something like hotspot or adguard vpnshit I'll pay more atention.
And it's true, @ccloli since sometime ago (when the script made the request for image link on demand) I didn't have any problems with the browsing limit, however, before that, I had.

**Comment by ccloli** [comment]
@iShyboy Hmm......It sounds strange. I should review or even refactor my code, since there are so many bugs reported recently. Unfortunately I'm really busy these days so I don't have so much free time to work on it :disappointed:
