### ISSUE TITLE
[Request] Auto retry option

### ISSUE THREAD

**Issue by iShyboy** [ccloli/E-Hentai-Downloader#38]
It's possible to do one auto-retry checkbox to let the script get new links and try to download the failed images without further question? If you have control of your download limit and how many tabs you are downloading it's not a problem, even more so if you know what you're doing since it's not default anyway.

**Comment by ccloli** [comment]
Released in 1.21.10, you can enable it on Settings -> Retry automatically when images download failed.

**Comment by iShyboy** [comment]
Good, thanks for the fast work.
