### ISSUE TITLE
Few Suggestions

### ISSUE THREAD

**Issue by JingJang** [ccloli/E-Hentai-Downloader#4]
Would you consider the following:

1) Add the numbering option beside or under the "Download Archive" option. Most galleries are numbered but there are a few that aren't. So in most cases you need a quick way to switch between numbering and not numbering. 

2) Usually the first comment is "Uploader Comment" which contains useful information about the gallery. Would you consider including it in the info. I already added it in the [example](https://github.com/JingJang/E-Hentai-Downloader/blob/ec84734908f4962d2335f615a84144276b04edb8/e-hentai-downloader.user.js) at line 11256. Would you also consider making the info file into an html to allow formatting of output including the comment. 

3) Rename the info file to always be at the top. Right now it is at the bottom if you enable numbering, and if its a large archive you do not spot it unless you scroll down to the bottom. 

Thank you

**Comment by ccloli** [comment]
1) Thanks for your suggestion, I'll think about it.

2) Uploader comment has been added (from 1.12).

3) I think this file may no use in most time (in fact most programs don't provide any information about the archive), and this file is used for debug at first, so I'm sorry that this feature will not be added.

By the way, you can sort files by last modified time, and they will be sorted by page number.

**Comment by ccloli** [comment]
Now you can move the mouse over "Download Archive", and the checkbox of enabling number images temporarily will be showed.
