### ISSUE TITLE
Always offer to continue download after hitting image limit.

### ISSUE THREAD

**Issue by knismaps** [ccloli/E-Hentai-Downloader#40]
If you hit your image limit, a popup from the script asks if you want to spend credits to reset it.  If you hit OK, there's a continue button on the status window.  If you hit cancel, will not have a continue button (and will then ask if you want to save the ZIP).

I tested by telling it I would reset, then just waiting a few hours, then hitting continue.  The download did continue and the ZIP was fine.

Is there a reason to not always offer to continue?

**Comment by ccloli** [comment]
I thought that most users will reset their image limits then continue, or get their downloaded images right now. So how about just change the notification like this?

> If you want to reset your image limits now, or wait for a few minutes until you have enough free limits, then continue, choose YES. Or if you want to cancal download and get your downloaded images, choose NO.

**Comment by knismaps** [comment]
Any way that lets me continue is fine.  I tried suggesting what I thought might be the smallest change.

Personally, I'd like it to work like this:
Have an option to show the notification/popup when you hit your image limit.  The popup would just have an "OK" button, clicking it would only close the popup and not do anything else.
When the limit is hit, put two buttons in the box with the download status, "continue" and "cancel."  If you click cancel, it asks if you want to save.  Or maybe three buttons: continue, cancel, save and cancel.

**Comment by ccloli** [comment]
Hmm, I'll consider about it.

**Comment by ccloli** [comment]
![qq 20160727192624](https://cloud.githubusercontent.com/assets/8115912/17173887/10a8554e-5430-11e6-8d7f-8cc90e91b3c4.png)
Now there are three buttons on progress box when image limits exceeded. The first one is _Reset Limits_, you can click the button to reset your limits on new tab; The second one is _Continue Download_, after reset or waited for a few minutes, you can recover your download progress; The last one is _Cancel Download_, click if you want to stop downloading and / or get your images.
