### ISSUE TITLE
exhentai.org 已经启用了 https, 请更改匹配规则

### ISSUE THREAD

**Issue by notastudio** [ccloli/E-Hentai-Downloader#42]
现在是`// @match        http://exhentai.org/g/*`,无法正常使用.

**Comment by ccloli** [comment]
请确认是否为最新版本，如果没错的话 1.22.1 已经修复了

**Comment by ccloli** [comment]
Probably duplicate with #41 .

**Comment by notastudio** [comment]
更新之后可以用了,谢谢
