### ISSUE TITLE
Classification according to EH

### ISSUE THREAD

**Issue by iShyboy** [ccloli/E-Hentai-Downloader#43]
Since it's easier to do this by the script I'm writing this issue.

Could you add an sign as a classification, according to EH, since the script can't sort the downloaded files by folders it would be waaaaaaaaaaaay easier to do this on my side if the first files of the archive were the classification something like this:

{DO}[Mariana Kaikou Kikaku (Mikami Hokuto)] Uchi, Nandemo Shimasu kara (Guilty Gear XX) [Digital]
{AR}[Ecolonun (Numeko)] Mahou Shoujo Reina
{MA}[Takara Akihito] Koiiro Girls Soutennenshoku [Digital]
{MI}[Brandon Santiago] Erma (Ongoing)
{NO}[Sung San-Young] The Gamer Ch. 72-136 (English) (Ongoing)
{WE}[Area] Between Friends (Ongoing)
{CO}[AmieChan] Rainbow Dash
{GA}[Noesis] Free Friends 2 [Decensored]
{IM}「bluefield」 - Artist

Then, after the downloads, it would be easier to sort them, and only then, run a script to erase those initials. The webpage should have the things needed.
_________
![:(](https://vgy.me/1jYOtk.png)

Sorting ~1000 folders is hard.

**Comment by ccloli** [comment]
If you just want to add the category tag, just simply modify Settings -> Zip file name with specific tag `{tag}`. For example, if you want to set your Zip file name like this picture, you can use `{{tag}} {title}`.
![qq 20160811123644](https://cloud.githubusercontent.com/assets/8115912/17578789/4f57976e-5fc0-11e6-9d6b-531a1be4361c.png)
