### ISSUE TITLE
没有读取失败自动请求新源的功能吗？

### ISSUE THREAD

**Issue by momosu** [ccloli/E-Hentai-Downloader#48]
还是我没有找到？就是页底那个Click here if the image fails loading，失败了自动换源下载的功能有吗

**Comment by ccloli** [comment]
在多次尝试失败后（默认为 3 次）会自动获取新的下载地址（除非设置了下载失败时从不获取新地址），如果觉得等待三次过长可以将鼠标移至下载状态中对应文件的右侧强制终止下载。
