### ISSUE TITLE
Page refreshing problem

### ISSUE THREAD

**Issue by stevenxqs** [ccloli/E-Hentai-Downloader#50]
The popup while refreshing the downloading page seems to be effectiveness.

------------------------------------------------------------------------------
ccloli你好
10月9日更新的版本在下载时对页面的更新操作后不再弹出提示窗口，而直接跳转到新页面，之前的下载需要从头开始TvT

**Comment by ccloli** [comment]
您好，能提供浏览器的相关信息么？我在 Chrome 53.0.2785.116 和 Firefox 49.0.1 下均没有问题，在刷新时都有提示。以及请确认下当前页面是不是有其他的脚本在运行，导致脚本对 onunload 事件的绑定被覆盖？
![qq 20161016155707](https://cloud.githubusercontent.com/assets/8115912/19416076/a2546726-93b9-11e6-96ec-d98cd8e4a83e.png)

**Comment by stevenxqs** [comment]
您好，
浏览器为Firefox 49.0.1。又经过测试，在下载途中再次点击"Download Archive"会出现“E-Hentai Downloader is working now, are you sure to stop downloading and start a new [download?”的提示，但点击小图或关闭/刷新下载页还是无提示。通过对油猴脚本的禁用发现应该是叫“Ex绅士界面汉化”脚本的问题，但其中并无onunload事件（之前一直在用也没有出现问题）。我有时手滑会把下载页关掉，不知道需不需要自己再加个所有网页关闭页面事件的提示。另外不知道问题脚本有没有用orz
[汉化.txt](https://github.com/ccloli/E-Hentai-Downloader/files/531977/default.txt)
十分感谢！

**Comment by ccloli** [comment]
您好，很抱歉回复晚了，在 Firefox 49.0.1 上同时使用 Tampermonkey 与 GreaseMonkey 测试均未复现该问题。能否再提供一份已安装的脚本列表呢？
![qq 20161019110147](https://cloud.githubusercontent.com/assets/8115912/19504294/b9eb2c24-95eb-11e6-86e7-744e66e8ca97.png)

**Comment by ccloli** [comment]
您好，刚刚再次确认了下，这样的问题是只在「Ex绅士界面汉化」脚本运行在「E-Hentai Downloader」之前才会出现的。检查了下在 Tampermonkey 下的错误输出，估计是由于「Ex绅士界面汉化」将页面的文字进行了修改，导致「E-Hentai Downloader」无法获取到页面中的指定内容而出现错误，从而导致后续的事件绑定操作被中断而无法执行。
![qq 20161019113333](https://cloud.githubusercontent.com/assets/8115912/19504891/950fefac-95f0-11e6-9a3a-2d883c64a5cf.png)

目前的解决方法是在扩展中将「E-Hentai Downloader」的运行顺序调整在「Ex绅士界面汉化」之前即可。
- GreaseMonkey 可以在「管理用户脚本」界面中在右上角选择按照执行顺序排序，然后在「E-Hentai Downloader」上右键，选择「稍早执行」或者「最早执行」直到其在「Ex绅士界面汉化」脚本之前即可。
![qq 20161019114258](https://cloud.githubusercontent.com/assets/8115912/19505016/88857f3a-95f1-11e6-8ebe-92c00a284d3d.png)
- Tampermonkey 可以在「仪表盘」界面中点击左上方的「#」以按执行顺序排序，然后鼠标点击「E-Hentai Downloader」右侧的排序图标，然后移动鼠标指针到「Ex绅士界面汉化」脚本之前即可。
![qq 20161019114640](https://cloud.githubusercontent.com/assets/8115912/19505061/e7b6ff7e-95f1-11e6-9e7c-83f60b1badbc.png)

或者您可以在设置里将上一版本新增的自动估算 Image Limits 消耗功能关闭，其位置在 _Settings -> Basic -> Disable pre-calculating image limits cost_，勾选后保存刷新即可。
