### ISSUE TITLE
[Feat. Requst] add tags to info.txt

### ISSUE THREAD

**Issue by Momoe** [ccloli/E-Hentai-Downloader#51]
This is a feature request to add all the tags applied to a comic being downloaded to the "info.txt" so this metadata can be used for later use.

**Comment by ccloli** [comment]
I'll consider about it. But before that, maybe I need to add a new setting page to let users select what they want like #46 .

**Comment by ccloli** [comment]
Hi, this feature has been released in 1.24, with customizing gallery info. It is not enabled by default. Go to Settings -> Advanced, you can see some checkboxes below where you choose how to save gallery info, and simply enabled _Tags_ and save.
![qq 20161101111557](https://cloud.githubusercontent.com/assets/8115912/19878529/9ace7218-a024-11e6-965c-f704cf894bcf.png)
