### ISSUE TITLE
關於chrome Violent monkey 下使用file system的問題

### ISSUE THREAD

**Issue by s894424422** [ccloli/E-Hentai-Downloader#52]
其實幾個版本前就有這問題了

用Violent monkey開啟file system的話，檔案會載不下來

會一直卡在　Slicing and storing Zip file...

不太想用Tampermonkey，真的非常lag

**Comment by ccloli** [comment]
似乎是 Violentmonkey 的安全限制過於嚴格了，現在已經修正了，不過目前發現了其他的 bug 並且在修正中，所以可能需要稍等一會才會更新。
