### ISSUE TITLE
Calculating extra data...

### ISSUE THREAD

**Issue by xibaibai9527** [ccloli/E-Hentai-Downloader#53]
请问，下载完了一个比较大的文件，然后到了下面就不动了
Generating Zip file...
Calculating extra data...
浏览器卡卡的，等了好久没反应
但是下载小本子没问题

--------
when I finished downloading a large book, it doesn't work.
But small book is ok.

Generating Zip file...
Calculating extra data...

File Size:	130.1 MB
Length:	200 pages

Firefox

**Comment by ccloli** [comment]
非常抱歉回复晚了，当时好像是刚起床看到邮件提醒后忘了（X

如果是在用 Firefox 的话有可能是因为内存不足，有时间的话我测试一下。可以考虑设置 Pages Range 一段段下载，这个脚本对于内存比较小的用户（<= 4GB）可能会比较吃力，所以可以考虑分成多个小段下载。

**Comment by xibaibai9527** [comment]
谢谢，的确内存比较小……原来分页下载是这个用处。
谢谢。
