### ISSUE TITLE
一个很严重的bug，serious

### ISSUE THREAD

**Issue by xibaibai9527** [ccloli/E-Hentai-Downloader#54]
症状是：批量下载一大堆zip，用winrar解压“单独解压到每个文件夹”，然后文件夹损坏，不能改名，不能删除。
但是图片可以用windows自带的软件浏览，也可以移动。就是文件夹不行。

前几天，这个bug出现一次，我以为是我的硬盘坏了。下载了360强力删除，删不掉，必须和上一级目录一起删除才能清除掉。

然后今天，先下载了一个zip，我发现设置重置了，下载回来的是英文包，并且里面有乱码子目录。
于是第二个本子，更改了设置：
Set folder name as：/
Set Zip file name as：{subtitle} 
Retry automatically when images download failed
Force download resized image (never download original image) **

勾选了这四项。
下载回来一大批本子后，问题出现了：
第一个本子没问题。后面的本子，全部再次文件夹无法删除/改名。

有bug的zip文件找不到了，手快解压后就删除了……再下回来一个，是没问题的……
我估计就是文件夹名字那里有问题。
请重视这个bug。

**Comment by ccloli** [comment]
能否提供下出现错误的地址，这个可以在历史记录中找到。如果不幸进行了删除操作，能否从下载记录里找一下文件的名字？

**Comment by xibaibai9527** [comment]
![00](https://cloud.githubusercontent.com/assets/19858971/20511085/1e8c9c6a-b0b0-11e6-8045-3f8a8ebbe2ad.png)
奇怪，FF的下载记录里竟然没有
不过这几个文件夹我还没删（删不掉，懒得安装360）

**Comment by ccloli** [comment]
我尝试使用了你的设置并下载了相同的 gallery，在 Windows 8.1 Professional x64 下 使用 WinRAR 5.21 64 位版本进行解压，没有复现该问题。依照你的描述来看，请确认是否为文件夹路径过长导致 Windows 无法打开子文件夹下的文件。

**Comment by xibaibai9527** [comment]
我也下了，但是这次没问题。可能是什么随机bug？
下次再遇到这个bug，我会把出问题的zip一起传上来。

**Comment by xibaibai9527** [comment]
找出来了，原来必须是下载多个zip，然后右键--解压每个文件到单独的文件夹……这样bug就会出现，你试试看

**Comment by xibaibai9527** [comment]
问题解决了，我把winrar从5.21升级到5.31就没问题了。
而且原来生成的不能删除的文件夹，在5.31下也可以删除掉。
具体bug的成因仍未能找到，或许是早期winrar的bug所致，也可能是脚本文件名。
至少我又可以快乐的撸了~
