### ISSUE TITLE
无法分页下载，以及无法从FileSystem得到文件

### ISSUE THREAD

**Issue by xbcdr** [ccloli/E-Hentai-Downloader#55]
某个[资源](https://exhentai.org/g/854787/b8d3a860b4/)，700+MB，1700+images in 44pages
浏览器是Google Chrome ver.54.0

直接下载的话，卡死在"Calculating extra data"，可能内存限制。
然后我尝试开启File System，所有数据都往里写，不记录额外的info。
结果还是卡死在老地方。
更蛋疼的是"User Data\Default\File System"下根本没有数据，而"Cache"文件夹下的文件也不完全。

尝试分页下载的话……
谁能告诉我Pages Range是怎么用的orz
输入分页范围，回车，没反应，单/双击"Pages Range"，没反应，点"Download Archive"，还是下载一整册。
(╯°口°)╯(┴—┴

**Comment by xbcdr** [comment]
> 输入分页范围，回车，没反应，单/双击"Pages Range"，没反应，点"Download Archive"，还是下载一整册。

似乎是浏览器的锅，重启浏览器之后就能正常用了……谜。
File System还是用不了，不过作者已经说了Blob Storage的问题就用Pages Range解决，所以这个issue还是关掉比较好？
orz

**Comment by xbcdr** [comment]
为了让这个issue不是纯酱油，我还是提交两个Bug吧……

有时浏览器卡顿一下，下载控制就会出错。
比如限制5个文件同时下载，但会出现同时七八个文件正在下载的情况，但downloading数量还是5。
呃如果pause并且abort任务的话，downloading可以是负的……

另外，如果文件在pending的时候pause，那么这个文件就永远卡住了，而且还是计入downloading数量的。

**Comment by ccloli** [comment]
非常抱歉，这个月在忙着期末考试，这几天也没网，所以没有及时回复 issue，在这里表示抱歉。

1. Calculating extra data 的话估计是内存不足的锅……毕竟这脚本只能写进内存里，Pages Range 不能用的锅我有时间看看吧；
2. 浏览器卡顿是 Tampermonkey 的锅，而且看起来作者并不打算修复的样子；
3. 下载计数出错以及状态不正确的问题……额，好像两个月前我试着改过……不过后来一直没测试，这次版本更新我会注意下的，感谢反馈。
