### ISSUE TITLE
doesn't work with EX Better Thumbnails

### ISSUE THREAD

**Issue by maskkulin** [ccloli/E-Hentai-Downloader#56]
Can you please make your script compatible with this?
https://sleazyfork.org/de/scripts/12281-ex-better-thumbnails

**Comment by ccloli** [comment]
Seems that EX Better Thumbnails removed/modified some elements that how E-Hentai Downloader detects how many pages need to download, and it may change some logics how E-Hentai Downloader works to compatible with it, so for latest releases I don't have any plan to work on it. Sorry about that.

**Comment by ccloli** [comment]
Fixed in 1.25.
