### ISSUE TITLE
script not running

### ISSUE THREAD

**Issue by mech0902** [ccloli/E-Hentai-Downloader#58]
i did notice that page e-hentai has update something.so i try to download some manga from the web but the script didn't run and "download archive" button didn't show too. i don't know because of that update or it happen only just me. so please check. Thank you.

**Comment by iShyboy** [comment]
Right, G.E- it's somehow not working and now it's just E-Hentai. I did my workout with just "Find and Replace". Find: g.e- replace for e- and that's all. But the best is an update. Now I have to get my redirectors working.

**Comment by ccloli** [comment]
It seems that `g.e-hentai.org` has been moved to `e-hentai.org` and it also supports HTTPS. I'll updated it ASAP.

**Comment by iShyboy** [comment]
It was hard for me figure it out. Just that another script that I use didn't redirect g.e- fjords to exh so I go to now that it moved. I'll be waiting for the update. Thanks.

**Comment by ccloli** [comment]
I was prepared for my final exam this month and also have no internet to check it these days. I also use an extension to redirect all the request from `g.e-hentai.org` to `r.e-hentai.org`, so I didn't notice it goes wrong. Thanks for all your feedbacks :-)

**Comment by jhorgechaus** [comment]
Hi, Solution.- go to editor script, settings and adds this:
```
// @include      http://e-hentai.org/g/*
// @include      https://e-hentai.org/g/*
```
no more :dancing_men:
