### ISSUE TITLE
如何下载原大小图片？

### ISSUE THREAD

**Issue by waerbo** [ccloli/E-Hentai-Downloader#60]
如何下载原大小图片？

不介意我用中文吧@w@

**Comment by ccloli** [comment]
对于已登录用户，脚本默认下载原始图片。

**Comment by waerbo** [comment]
怎么才算是登陆呢？！https://XXXXXXXXXX/home.php我是已经在概述界面了的也就是登陆了的= =

**Comment by ccloli** [comment]
既然能打开那个页面那就已经是登录了（

**Comment by waerbo** [comment]
可是下载了之后的压缩包和页面的容量对不上

**Comment by waerbo** [comment]
请问有没有联系方式？！QQ？

**Comment by ccloli** [comment]
如果确认没有设置 Pages Range、没有开启压缩功能、压缩文件内没有缺页、文件大小差异很大的话，请将 gallery 的地址发给我看看

**Comment by ccloli** [comment]
直接回复就行了，不需要 QQ 之类的

**Comment by waerbo** [comment]
![qq 20170213000945](https://cloud.githubusercontent.com/assets/25716110/22863780/590ed378-f181-11e6-8d38-af022aabb922.png)

**Comment by waerbo** [comment]
![qq 20170213001208](https://cloud.githubusercontent.com/assets/25716110/22863787/69084070-f181-11e6-9649-9d6e33d1981c.png)
![qq 20170213001222](https://cloud.githubusercontent.com/assets/25716110/22863789/6b899bd2-f181-11e6-901c-4325a61718c5.png)

**Comment by waerbo** [comment]
![qq 20170213001535](https://cloud.githubusercontent.com/assets/25716110/22863798/90f38dec-f181-11e6-9c20-33816941d712.png)

**Comment by ccloli** [comment]
不不不，是脚本的设置，不是 EH 的设置
![](https://cloud.githubusercontent.com/assets/8115912/10636596/56c9073c-7833-11e5-9161-c2c9f1a288a7.png)
点击任意 Gallery 中的这个框中右边的 Settings；当然，估计你应该没有对这里面进行任何修改，那么它默认下载的确实是原始文件。
如果确认没有开启下载略小的文件这一功能的话，请确认下下载的图片中是否有文件损坏或者是警告图片的情况。

**Comment by waerbo** [comment]
![qq 20170213002439](https://cloud.githubusercontent.com/assets/25716110/22863891/d9fca4b4-f182-11e6-81bf-fd40aaec17bd.png)
![qq 20170213002446](https://cloud.githubusercontent.com/assets/25716110/22863893/dc98b3b6-f182-11e6-9f7a-e3681eb81c37.png)

**Comment by waerbo** [comment]
还有…他会计数…不是说不会计数么…… = =
怎么不计数来着…

PS..姐已崩溃= =

**Comment by ccloli** [comment]
项目的 README 已经说明了脚本的原理，下载时自然会消除阅览限制的点数（image limits）。

所以设置里并没有开启强制下载较小图片的功能，所以下载的确实是原始图片。请确认下下载的图片中是否有缺少文件、文件损坏或者是警告图片的情况，谢谢。

**Comment by waerbo** [comment]
不知道怎么下载不会消耗点数
另外想问问那个页面是要开着才会原图下载么？刚才没关那个home.php下载一个本子是原图容量能对上，下完之后发现消耗点数…
之前没有开这个页面是对不上的

sorry咯…毕竟第一次用这个…之前有一个下下载器能够充值点数来着…

**Comment by ccloli** [comment]
1. 下载不消耗点数请尽量使用 EH 自带的下载 torrent 功能（如果有的话），或者花费 credits 直接打包下载，省时省心；
2. 只要保持 gallery 的页面开启即可，容量对不上的话_请确认下下载的图片中是否有缺少文件、文件损坏或者是警告图片的情况_；
3. 充值点数多半是花费你的 credits 或者 GPs 来重置而已，或者是用了其他的奇怪的方法。Image limits 的消耗请参阅 https://github.com/ccloli/E-Hentai-Downloader/wiki/E%E2%88%92Hentai-Image-Viewing-Limits-(Chinese)
