### ISSUE TITLE
FAILED! (NETWORK ERROR)

### ISSUE THREAD

**Issue by spellcatcher** [ccloli/E-Hentai-Downloader#61]
when downloading the gallery some image get failed! (network error), this problem just happen when downloading the gallery while logged in.
thx n sorry for my bad english

**Comment by ccloli** [comment]
I usually get this error, too. But that means you are really in a poor network or your connection to the server is not stable. As for me, when I use a proxy server, it works perfectly without any warnings or errors.

Here is an archive that I downloaded just now, the last two pictures always get errors like `Network Error` and `Timed Out`, but when I used proxy, they are finished just in a seconds.
![image](https://cloud.githubusercontent.com/assets/8115912/23075433/64d85824-f577-11e6-92c0-e19d92fc2c2a.png)

You can try open any gallery and view it online, probably you can see some images broken when you are reading. Also you can also try download the original image at the bottom of the page, it may in a very low speed or even failed. That means you really don't have a stable connection with server.

**Comment by spellcatcher** [comment]
i get it thank you sir
