### ISSUE TITLE
As of Greasemonkey 3.11 (updated Apr 25 2017), downloading box not showing

### ISSUE THREAD

**Issue by nisbahmumtaz** [ccloli/E-Hentai-Downloader#64]
Been working fine for a long while now. Now it's not.

Firefox also updated to v53, if that's of any relevance.

Not sure if it's just my issue either. Maybe ex-Hentai changed some stuff in their site?

Hopefully someone others can testify as well.

**Comment by ravenlord1** [comment]
Just tried it and i works fine for me, FF v53.0 and Grease Monkey 3.11.  Also works with latest Tampermonkey.  Maybe you can try that.

**Comment by ccloli** [comment]
Hi, it works fine on my Firefox 53.0 & GreaseMonkey 3.11, please check is there another script that makes E-Hentai Download not working. Also you can press F12 and select `Console` tab, then paste the log here if it shows something is wrong.

![image](https://cloud.githubusercontent.com/assets/8115912/25734675/05c436f2-3198-11e7-93ac-d65bc18176d1.png)

**Comment by nisbahmumtaz** [comment]
LMAO I'm a fucking retard

For some reason, I had Greasemonkey disabled. I've never done that in the years I've installed this shit and transferred to a new system. Must have slipped a click to disable it at some point.

Problem is solved, I guess.
