### ISSUE TITLE
Downloading too slow or freeze when page is in background (not focusing)

### ISSUE THREAD

**Issue by ccloli** [ccloli/E-Hentai-Downloader#65]
As reported in GreaseFork feedback [#21024](https://greasyfork.org/forum/discussion/21024/x), here is a problem that makes your download speed too slow or even freeze when you keep the downloading tabs in background, or say, you are not looking at it.
![image](https://cloud.githubusercontent.com/assets/8115912/25771722/e677de1c-328b-11e7-959c-bd4d3761b8f8.png)

Thought not tested on Firefox and other browsers, Chrome will optimize background tabs performance to reduce resource usage. An obvious example is `setTimeout()` in JavaScript, Chrome will increase the delay time if it works in background. That's say, if we use `setTimeout(fn, 1000)`, `fn` will be run after 1 second (1000ms) in usual. But if it's in background, it will be run after about 2 seconds.

So here is the problem, I'm not sure other browser and extension, but on Chrome with Tampermonkey, the download progress will be too slow when the downloading page is in background. `setTimeout()` doesn't be used so many in E-Hentai Downloader and most of them are not in core functions. I also tested with [Violentmonkey](https://violentmonkey.github.io/), it works fine, without any visible delay or freezing which makes me surprised. 

So at this time, I think it maybe a bug of Tampermonkey, seems that when it transfers response data to ArrayBuffer it uses `setTimeout()` to performance, but I'm not sure. 

Anyway, it probably not a bug of E-Hentai Downloader, and I'm just note it here to notice you. If you have this problem, and the content you're downloading is not too NSFW, keep it in foreground; or drag the tab out of the browser window as a new window, then use other windows to cover it; or just leave it here, it'll be completed someday...... (x

**Comment by NBOOK** [comment]
确实 tampermonkey 和 tampermonkey beta 都有这个问题，但在我电脑上 Violentmonkey 看不到单个图片的下载速度和进度，请问这是 bug 么。

**Comment by ccloli** [comment]
@NBOOK Violentmonkey 的 `onprogress` 事件对象没有 `lengthComputable` 和 `loaded` 属性，可能是 Violentmonkey 自身实现不完整，所以无法显示下载速度与进度

***

Violentmonkey doesn't supports download speed and progress, because its `onprogress` event object doesn't have `lengthComputable` & `loaded` attributes.

**Comment by simon300000** [comment]
tampermonkey Safari 似乎没有出现

**Comment by ccloli** [comment]
@simon300000 似乎只有 Google Chrome 对此进行了优化，因为 Firefox 下的 Tampermonkey 是正常的。你可以自己测试下下面的代码，粘贴它到浏览器控制台或者新建用户脚本均可，然后测试将焦点落在浏览器内或浏览器外，或者切换至其它标签页，稍等一下再切换回来：
***
Seems only Google Chrome optimized it, because Tampermokey on Firefox works correctly. You can try the code below to TIY, paste it into console or create a new userscript, then try click into the browser or outside the browser, or switch to another tab then return here later: 

```js
let timer = null;
let time = Date.now();
const delay = 1000;

let hidden, visibilityChange; 
if (typeof document.hidden !== "undefined") { // Opera 12.10 and Firefox 18 and later support 
    hidden = "hidden";
    visibilityChange = "visibilitychange";
} else if (typeof document.msHidden !== "undefined") {
    hidden = "msHidden";
    visibilityChange = "msvisibilitychange";
} else if (typeof document.webkitHidden !== "undefined") {
    hidden = "webkitHidden";
    visibilityChange = "webkitvisibilitychange";
}

const timerFn = () => {
    const curTime = Date.now();
    timer = setTimeout(timerFn, delay);

	let d = curTime - time - delay;
    if (d > 0) {
        d = `+${d}`
    }
    console.log(`Expected time: ${delay}ms | Elapsed time: ${curTime - time}ms (${d}ms)`);
    time = curTime;
}

const visibilityChangeHandler = (event) => {
    console.info(`The visibility of tab has been changed to ${document.visibilityState}!`);
}

const focusHandler = (event) => {
    console.info(`The tab has been focused!`);
}

const blurHandler = (event) => {
    console.info(`The tab has been blurred!`);
}

const revokeTest = () => {
    clearTimeout(timer);
    document.removeEventListener(visibilityChange, visibilityChangeHandler);
    window.removeEventListener('focus', focusHandler);
    window.removeEventListener('blur', blurHandler);
}

const initTest = () => {
    timer = setTimeout(timerFn, delay);
    document.addEventListener(visibilityChange, visibilityChangeHandler);
    window.addEventListener('focus', focusHandler);
    window.addEventListener('blur', blurHandler);
}

initTest();
// if you want to stop testing, exclude `revokeTest()`
// revokeTest();
```

*** 

这是我使用 Chrome 和 Firefox 的测试结果：
***
This is my test results of Chrome and Firefox: 

`Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36`
![image](https://user-images.githubusercontent.com/8115912/28952439-bae89b6a-7903-11e7-8591-d226f73f2600.png)
`Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0`
![image](https://user-images.githubusercontent.com/8115912/28952531-5bfa4b16-7904-11e7-8d38-4951193f95ab.png)

**Comment by simon300000** [comment]
Safari 的优化有些不一样，似乎有考虑是否显示

如果我切换到其他tab，它会诡异的慢下来，如果把它放在别的地方或者新建一个窗口干什么，因为这个tab理论上还属于能被用户看到的，所以工作会正常

切换到同一窗口别的tab
<img width="396" alt="2017-08-04 12 34 07" src="https://user-images.githubusercontent.com/12656264/28954593-ee13d996-7912-11e7-9896-c731925e47f9.png">


切换到别的窗口但是tab不变
<img width="344" alt="2017-08-04 12 34 30" src="https://user-images.githubusercontent.com/12656264/28954585-e0017f98-7912-11e7-9615-ee35fa68f8b9.png">

**Comment by simon300000** [comment]
要不弄个小js播无声音乐，估计能绕过（笑

**Comment by simon300000** [comment]
@ccloli 
音乐似乎是有用的：
Music Seems to work:

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3052.0 Safari/537.36

The picture does not upload for some reason...

let timer = null;
let time = Date.now();
const delay = 1000;

let hidden, visibilityChange, audioCtx, oscillator, gainNode;
if (typeof document.hidden !== "undefined") { // Opera 12.10 and Firefox 18 and later support 
    hidden = "hidden";
    visibilityChange = "visibilitychange";
} else if (typeof document.msHidden !== "undefined") {
    hidden = "msHidden";
    visibilityChange = "msvisibilitychange";
} else if (typeof document.webkitHidden !== "undefined") {
    hidden = "webkitHidden";
    visibilityChange = "webkitvisibilitychange";
}

const timerFn = () => {
    const curTime = Date.now();
    timer = setTimeout(timerFn, delay);

    let d = curTime - time - delay;
    if (d > 0) {
        d = `+${d}`
    }
    console.log(`Expected time: ${delay}ms | Elapsed time: ${curTime - time}ms (${d}ms)`);
    time = curTime;
}

const visibilityChangeHandler = () => {
    console.info(`The visibility of tab has been changed to ${document.visibilityState}!`);
}

const focusHandler = () => {
    console.info(`The tab has been focused!`);
}

const blurHandler = () => {
    console.info(`The tab has been blurred!`);
}

const revokeTest = () => {
    oscillator.stop()
    clearTimeout(timer);
    document.removeEventListener(visibilityChange, visibilityChangeHandler);
    window.removeEventListener('focus', focusHandler);
    window.removeEventListener('blur', blurHandler);
}

const initTest = () => {
    audioCtx = new(window.AudioContext || window.webkitAudioContext)()
    oscillator = audioCtx.createOscillator()
    gainNode = audioCtx.createGain()
    oscillator.connect(gainNode)
    gainNode.connect(audioCtx.destination)
    oscillator.frequency.value = 1
    gainNode.gain.value = 0.001
    oscillator.start()
    timer = setTimeout(timerFn, delay);
    document.addEventListener(visibilityChange, visibilityChangeHandler);
    window.addEventListener('focus', focusHandler);
    window.addEventListener('blur', blurHandler);
}

initTest();
// if you want to stop testing, exclude `revokeTest()`
// revokeTest();
```

```
let audioCtx = new(window.AudioContext || window.webkitAudioContext)()
let oscillator = audioCtx.createOscillator()
let gainNode = audioCtx.createGain()
oscillator.connect(gainNode)
gainNode.connect(audioCtx.destination)
oscillator.frequency.value = 1 //low frequency can not hear
gainNode.gain.value = 0.001 //low volume can not hear
oscillator.start() //start music
```

`oscillator.stop() //stop`

**Comment by simon300000** [comment]
I can not make it work in Tampermonkey
thing like window.AudioContext will become undefined
need help now, never used Tampermonkey
@ccloli

**Comment by ccloli** [comment]
Hmm, interesting, looks like the Safari is also optimized, but you said it works fine in Safari, maybe Tampermonkey has been updated, will check it these days.

The empty audio also looks good to me, however it'll display an icon on the tab showing this tab is playing music. Also as mentioned, in E-Hentai Downloader itself, it doesn't use `setTimeout()` when garbing images, so I think the delay maybe is in Tampermonkey, as ViolentMonkey doesn't have this problem.

Userscript with `GM_` API is in a sandbox, to use the method in the page, try replacing `window` with `unsafeWindow`.

***

看起来 Safari 同样对 `setTimeout` 进行了优化，但是您说 Safari 下并没有这个问题，难道 Tampermonkey 更新了……？最近我看看是不是这样

空音频看起来效果不错，但是它会使得浏览器在标签顶部显示一个正在播放音频的标识。而且如前所说，E-Hentai Downloader 并没有在获取图片的相关代码内使用 `setTimeout`，所以这有可能是 Tampermonkey 的问题，因为 ViolentMonkey 并没有这样的问题

使用了 `GM_` API 的用户脚本是在一个沙盒内的，要访问沙盒外的方法和数据可以试试把 `window` 替换成 `unsafeWindow`

**Comment by simon300000** [comment]
I'll try unsafeWindow later
About the icon, if I set the volume to 0.0001 or lower there will be no icon on Chromium, but I don't sure if it will still work, I'll try it later

**Comment by simon300000** [comment]
#71 Tried to put the music code on, but need test since I don't get this problem

**Comment by ccloli** [comment]
@simon300000 and I did something to fix this problem these days. You can see our discussions in #72. 

In short, @simon300000 uses a trick that plays silent music in the tab, so that Chrome will not optimize the tab, so it won't freeze. However we found that it has a hardware or API limit that you cannot download too much galleries at the same time, because your device doesn't have so many audio context to do that. Anyway it has limits, it really fix the problem. You can check it in PR #72.

Then I found that `setTimeout` in a Web Worker won't being optimized, so I tried it and it‘s just like what I said. But it doesn't fix the problem, thought has replaced the sandbox `setTimeout`, so maybe it's something else that has been optimized. You can check it in branch `web-worker-timer`.

**Comment by simon300000** [comment]
Sorry I'm busy past few days so I did reply anything
the wired this I found in my browser, I did not have chrome installed so I used Chromium, 59.0.3052.0, 64 bit, I don't seems have the hardware limit? Maybe it will not limit at developer edition
<img width="1680" alt="2017-08-08 10 39 27" src="https://user-images.githubusercontent.com/12656264/29077372-8a9e25f8-7c8a-11e7-936c-8031f5ffb9aa.png">

just let you know

**Comment by ccloli** [comment]
Have a test about `GM_xmlhttpRequest`, so maybe the lag is in `GM_xmlhttpRequest` itself (or maybe it caches `setTimeout` or something else).

Here is a test about continuous requesting `https://www.baidu.com`. When the tab is visiable, the download speed is about 500KB/s, ~10 requests/s, and the delay is acceptable.
![image](https://user-images.githubusercontent.com/8115912/29078933-5e04160c-7c8e-11e7-9cbc-cac998f98d8d.png)

But if it's invisible, the download speed is down to 30KB/s, ~1 request/s, delay is happened between `GM_xhr` called and `GM_xhr` starts to receive data.
![image](https://user-images.githubusercontent.com/8115912/29079057-b98377de-7c8e-11e7-80b6-8ef2fca5d571.png)

Seems that hooking functions is meaningless, because the functions are cached in Tampermonkey, so the only way is to prevent Chrome optimize.

Test script (modified, may have bugs but not important): 
```js
// ==UserScript==
// @name         GM_xhr delay test
// @version      0.1
// @description  test
// @connect      www.baidu.com
// @match        *
// @grant        GM_xmlhttpRequest
// @noframes
// ==/UserScript==

var reqIndex = 1;
var startIndex = 0;
var log = '';
var stopReq = false;

var t = Date.now();

function startXHR() {
	var nt;
	GM_xmlhttpRequest({
		method: 'GET',
		url: 'https://www.baidu.com',
		responseType: 'arraybuffer',
		timeout: 300000,
		onprogress: function(res) {
			if (startIndex < reqIndex) {
				nt = new Date();
				log += (`[TEST] @${nt} [=2=] Load started (+${nt - t}ms)`);
				t = nt;
				reqIndex = startIndex;
			}
			else if (res.lengthComputable && res.loaded === res.total) {
				nt = new Date();
				log += (`[TEST] @${nt} [ ? ] Load finished (+${nt - t}ms)`);
				t = nt;
			}
		},
		onload: function(res) {
			nt = new Date();
			log += (`[TEST] @${nt} [ 3 ] Onload called (+${nt - t}ms)`);
			t = nt;

			var response = res.response;
			var byteLength = response.byteLength;
			var responseHeaders = res.responseHeaders;
			nt = new Date();
			log += (`[TEST] @${nt} [ 4 ] Response is parsed (+${nt - t}ms)`);
			t = nt;

			reqIndex++;
			if (!stopReq) {
				startXHR();
			}
		}
	});
	nt = new Date();
	log += (`[TEST] @${nt} [-1-] Request started (+${nt - t}ms)`);
	t = nt;
}

startXHR();

window.printLog = function(){
	stopReq = true;
	document.body.textContent = log;
};
// run `printLog()` in console to stop testing
```

**Comment by simon300000** [comment]
So if the music code is in, it would be help?
```javascript
let audioCtx = new(window.AudioContext || window.webkitAudioContext)()
let oscillator = audioCtx.createOscillator()
let gainNode = audioCtx.createGain()
oscillator.connect(gainNode)
gainNode.connect(audioCtx.destination)
oscillator.frequency.value = 1 //low frequency can not hear
gainNode.gain.value = 0.001 //low volume can not hear
oscillator.start() //start music
```

Sorry I don't have VPN and I'm at China so is kind hard for me to get the Tampermonkey in my chromium, I try to find direct link of the file.

**Comment by ccloli** [comment]
![image](https://user-images.githubusercontent.com/8115912/29082861-81d131cc-7c99-11e7-8ba5-184bafc340a0.png)
Still happens when running on 6 tabs. However once it can be run at about 8 `about:blank` tabs... Not sure what's the limit come from.

***

Try https://chrome-extension-downloader.com/ and input `gcalenpjmijncebpfijmoaglllgpjagf`

**Comment by ccloli** [comment]
Found the reference that Chrome starts to optimize in v57: https://developers.google.com/web/updates/2017/03/background_tabs .

> ### Budget-based background timer throttling
> 
> Shipping in Chrome 57, budget-based timer throttling is a further extension of the timer alignment mechanism, placing an additional limit on background timer CPU usage. It operates as follows:
> 
> - Each background tab has a time budget (in seconds) for running timers in the background.
> - A page is subjected to time budget limitations after 10 seconds in the background.
> - A timer task is allowed to run only when the time budget is non-negative.
> - After a timer has executed, its run time is subtracted from the budget.
> - The budget continuously regenerates with time (currently set to a rate of 0.01 seconds per second). Note that this budget regeneration rate can be tweaked as Chrome collects more data about throttling behavior.
> 
> There are a number of automatic exemptions from this throttling:
> 
> - Applications playing audio are considered foreground and aren’t throttled.
> - Applications with real-time connections (WebSockets and WebRTC), to avoid closing these connections by timeout. The run-timers-once-a-second rule is still applied in these cases.
> 
> Note that this his mechanism uses wall time, not CPU time. It’s a good approximation of CPU time and penalises blocking the main thread for a long time.

From this article, some ways to prevent the optimizing is playing media and use WebSocket or WebRTC (however I failed with WebSocket, and connects to an untrusted site is not safe for users). 

Also here is another way, user can try disabling it in `chrome://flags/#expensive-background-timer-throttling`, or launch Chrome with `--disable-background-timer-throttling` option.
> #### Throttle expensive background timers <sub>Mac, Windows, Linux, Chrome OS, Android<sub>  
> Enables intervention to limit CPU usage of background timers to 1%.

***

Thought `AudioContext()` has limits, maybe we can try play a real audio file, but not generate it with `AudioContext`. I tried creating a sane audio that only has 1Hz audio (thought sample rate of MP3 can only be set to `8000` in minimum), just like what @simon300000 did.

```sh
ffmpeg -f lavfi -i "sine=r=8000:frequency=1:duration=1" -c:a libmp3lame -b:a 8k -f mp3 sine.mp3
```

Then play it in a loop, leave it in background, and the output log of the test code looks pretty good.
![image](https://user-images.githubusercontent.com/8115912/29106380-5624d6fa-7d07-11e7-9ae2-5d5de21669f5.png)

Also try playing another music in other tabs, no warning and error.
![image](https://user-images.githubusercontent.com/8115912/29106323-0697e712-7d07-11e7-8199-23d57c50b3a2.png)

**Comment by ccloli** [comment]
[v1.27](https://github.com/ccloli/E-Hentai-Downloader/tree/v1.27) was released just now, you can try enabling playing silent audio to prevent Chrome's optimization. To enable it , check out _Settings -> Advanced -> Play silent music during the process to avoid downloading freeze_.
