### ISSUE TITLE
用gae代理下载后，图片多了后缀名

### ISSUE THREAD

**Issue by xibaibai9527** [ccloli/E-Hentai-Downloader#67]
如果图片第一次下载失败，后面再重新下载，图片就会变更文件名。
![00](https://cloud.githubusercontent.com/assets/19858971/26284847/ffc3f2e2-3e76-11e7-959a-79f303030e67.png)

前后都多了一个破折号，导致某些识图软件不能快速识图

我以为这是很常见的问题，直到有一天，我把代理从gae换成了ss，发现就没这种问题了。
看来是因为gae会自动切换ip导致的？

还有一个问题，如果图片下载时显示“pending”点了pause，就卡死了，不会继续，也不能手动取消。

再一个问题，假如1.jpg下载不动了，手动点击停止这张图，滚动条会直接跳到最下面。
但是，很多时候你想重新下载这张图，得点击两次以上。所以你得手动滚回1.jpg的地方。
能不能别让滚动条在点击之后跳到最下面？

谢谢看我抱怨这么多，祝大家都愉快爆射

**Comment by ccloli** [comment]
已尝试在 1.26.3 中修复，请尝试更新并确认 bug 是否仍存在，谢谢。

**Comment by xibaibai9527** [comment]
破折号的问题依旧存在

**Comment by ccloli** [comment]
找到原因了，GoAgent 之类的代理软件在转发请求时对 HTTP 头进行了修改，有一个修改就是将响应头中的 `filename` 加上了引号

这是正常的响应头：
![image](https://cloud.githubusercontent.com/assets/8115912/26450233/f1852a7e-4188-11e7-8e07-f4d960ca7768.png)

这是经过 GoAgent 后的响应头：
![image](https://cloud.githubusercontent.com/assets/8115912/26450259/17252446-4189-11e7-8cbf-ffa85df80cbe.png)

可以发现 `Content-Disposition` 下的子项 `filename` 多出了一个引号，导致脚本对引号进行了转义

**Comment by ccloli** [comment]
已尝试修复，请更新至 1.26.4 再次确认，谢谢

**Comment by xibaibai9527** [comment]
自动更新一提示就去看了，已经完美解决问题。3Q
