### ISSUE TITLE
希望能记录下载失败的网站

### ISSUE THREAD

**Issue by dodying** [ccloli/E-Hentai-Downloader#68]
表里站都开了HTTPS，现在可以不用代理就上了。
直连速度也挺快的，就是有些图片的网站被墙了，然后需要重复试好几次才能下载成功。
如果能记录这些网站，并加入代理，就能更快的下完一本本子了😘

**Comment by ccloli** [comment]
其实可以在第一次下载结束，提示部分文件下载失败的时候，切换浏览器的代理设置，然后再点击重试，这样失败的图片可以走代理（如果不想尝试从 EH 服务器下载，可以进一步在设置里勾选 _Never send `nl`_ 之类的）
另外下载完成后默认的 `info.txt` 会包含所有图片对应的页面的 URL，这样可以方便对比将缺漏的图片加上来

**Comment by dodying** [comment]
额，我的意思是想发现这些被墙的网站后，将它们加入自动代理的列表
以后再下载这个域名就不用再这样失败，nl，失败，nl
另外对我来说，下载完不解压，要用的时候直接用Hoveyview打开，除非剧情完全对不上，不然发现不了缺页的

**Comment by ccloli** [comment]
由于这个功能可能并非大多数人所需要，以及页面内确实没什么地方能放下，将其输出在日志中如何？这样在浏览器中按下 `F12` 就能查看输出日志，大概类似于这样，可以在 `Request URL` 中找到（至于是不是拿到最终的 URL 就只能看情况了）：
```
[EHD] #33: Network Error
[EHD] #33: RealIndex > 33  | ReadyState > 4  | Status > 0  | StatusText > 
Request URL > https://e-hentai.org/fullimg.php?gid=1066903&page=33&key=3h300mz8wkx 
ResposeHeaders >
[EHD] Index > 33  | RealIndex > 33  | Name > CE_1372_0033.jpg  | RetryCount > 0  | DownloadedCount > 12  | FetchCount > 10  | FailedCount > 12
```

**Comment by dodying** [comment]
嗯嗯，输出到控制台就行。

**Comment by dodying** [comment]
你的示例里是 `开始下载时输出日志` 吗
希望是 `onerror` 或 `速度太小被中断` ，才输出
最好可以用 `console.error` 方便筛选

**Comment by ccloli** [comment]
错误日志仅在下载失败时出现，并会在最后一条日志中使用 `console.error`
![image](https://cloud.githubusercontent.com/assets/8115912/26446145/791c4102-4175-11e7-912f-cc657e0eb38c.png)

**Comment by dodying** [comment]
嗯，我的意思就是想在下载失败的时候，显示这个网站
比如这样
![default](https://cloud.githubusercontent.com/assets/13816909/26448791/9b0f7818-4181-11e7-90f7-f2c00077cb23.png)

**Comment by ccloli** [comment]
已添加，请尝试更新至 1.26.4

**Comment by dodying** [comment]
感谢大大
