### ISSUE TITLE
Insufficient funds

### ISSUE THREAD

**Issue by bloodsucker3011** [ccloli/E-Hentai-Downloader#69]
like a title said, after i click on archive download i get "Insufficient funds" error and don't let me download it.
thank you for app, before it work

![insufficient funds](https://cloud.githubusercontent.com/assets/28969855/26476929/28b9e206-41ec-11e7-8714-f506b20e636d.png)

**Comment by ccloli** [comment]
The link you clicked is provided by E-Hentai offically, not by this script. Please click the link which is in the box of _E-Hentai Downloader_, just in the middle of gallery information and gallery thumbnails.

**Comment by bloodsucker3011** [comment]
ah thank you
