### ISSUE TITLE
Not Showing

### ISSUE THREAD

**Issue by iShyboy** [ccloli/E-Hentai-Downloader#7]
In the latest version is showing nothing here.

![xx](http://i.imgur.com/k760HV1.png)

**Comment by ccloli** [comment]
Fixed. By the way, most of large archives (eg. the archive of your screenshot) have torrents, and you can download it with torrent.

**Comment by iShyboy** [comment]
I know, but torrent for my connection is not that good, and the speed become low so i download with the script. Thx for the fix.

**Comment by ccloli** [comment]
For failed downloading, see issue #6 for details.
