### ISSUE TITLE
[BUG] Incompatible with “EX绅士界面汉化” & / "EX绅士标签汉化"

### ISSUE THREAD

**Issue by BreakShadow0504** [ccloli/E-Hentai-Downloader#75]
FULL Log here
[EHD] E-Hentai Downloader is running.
VM944:35 [EHD] Bugs Report > https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback
VM944:36 [EHD] To report a bug, showing all the "[EHD]" logs is wonderful. =w=
VM944:11978 [EHD] UserAgent > Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36
VM944:11979 [EHD] Script Handler > Tampermonkey
VM944:11980 [EHD] Script Handler Version > 4.3.6
VM944:11981 [EHD] E-Hentai Downloader Version > 1.26.6
VM944:11982 [EHD] E-Hentai Downloader Setting > {"number-auto-retry":true,"status-in-title":"never","file-descriptor":true,"save-info":"file","save-info-list":["title","metas","tags","uploader-comment","page-links"],"replace-with-full-width":true}
VM944:11983 [EHD] Current URL > https://exhentai.org/g/1085686/d722bf6937/#
VM944:11984 [EHD] Is Logged In > true
VM944:13567 [EHD] Request Image Limits From e-hentai.org
VM944:13607 Uncaught TypeError: Cannot read property 'split' of undefined
    at getFileSizeAndLength (eval at E_c (:3:221), <anonymous>:13607:47)
    at initEHDownload (eval at E_c (:3:221), <anonymous>:13092:32)
    at HTMLDivElement.eval (eval at E_c (:3:221), <anonymous>:13707:2)

Will happen no matter how I click the Download Archive button.
Using latest Chrome 64Bit & Tampermonkey
And after my friend performed a diagnose, he found out that the script rely on "File Size:", the EXACT string on the webpage.
Is this fixable? Thanks.

**Comment by ccloli** [comment]
See https://github.com/ccloli/E-Hentai-Downloader/issues/50#issuecomment-254060816 . Move E-Hentai Downloader to the place that before any other scripts, to make sure it'll run before any other scripts change the page.
