### ISSUE TITLE
Completely Broken?

### ISSUE THREAD

**Issue by Dannyn714** [ccloli/E-Hentai-Downloader#76]
I'm not sure but the script doesn't seem to be working at all anymore.
![image](https://user-images.githubusercontent.com/30919257/29201462-6effd44c-7e2c-11e7-95a9-26391fa634ef.png)

Maybe this will help?

**Comment by ccloli** [comment]
Hi, if you are a new user, the code in `master` branch (also GreasyFork) is now in developing, and it's being build by a mistake, please reinstall it here: https://github.com/ccloli/E-Hentai-Downloader/blob/v1.26.6/e-hentai-downloader.user.js (click the `Raw` button). 

If you still have the problem, please press `F12` in any gallery tab and switch to `Console`, reload the page, then copy and paste the logs that started with `[EHD]`.

**Comment by Dannyn714** [comment]
Realized that TamperMonkey needed me to give it permission. Thanks for the help. Love this script and you.
