### ISSUE TITLE
not working anymiore

### ISSUE THREAD

**Issue by kanink007** [ccloli/E-Hentai-Downloader#79]
i used this script for a long time and it always worked until now.
today i used it again, but it spent all my GP and it said I hit the  daily GP limit.

**Comment by ccloli** [comment]
See [wiki/E−Hentai Image Viewing Limits](https://github.com/ccloli/E-Hentai-Downloader/wiki/E%E2%88%92Hentai-Image-Viewing-Limits).

If you think it's a bug, please provide more information, also try pressing F12 -> Console and copying all the logs that started with `[EHD]`

**Comment by kanink007** [comment]
okay let me describe it like this.. (i will check the log later then)..
before.. 4 or 5 months ago maybe? i tested ehentai downloader script the last time. and back then, it worked like this: a randomly number of points was generated. something like... 0/47000
everytime i refreshed the page, the number changed randomly.. for example from 0/47.000 into 0/17.000
and when i started to download the images, my points never were used. (i think it was script version 1.26 i used back then).

but now my limit is always 0/5.000 it doesnt randomly change  anymore when i refresh and when i start to download, the script spends my real points. 

- did something change during these 4 months?

**Comment by ccloli** [comment]
The image limits is refreshed from https://e-hentai.org/home.php which is provided by E-Hentai, have a look to make sure it's correct. The default limit is 5000, and you can upgrade it by donating to E-Hentai, get Hath and spend them here https://e-hentai.org/hathperks.php . If you paid Hath to increase your limits but it's invalid now, try asking for help in E-Hentai forum. But if you didn't pay for it, it shouldn't be randomly, so maybe it's probably a bug of E-Hentai system and it's fixed now. 

- To get E-Hentai updates, see https://e-hentai.org/news.php

**Comment by kanink007** [comment]
so your script was never meant to avoid spending points? i thought it was exactly made for that and it worked before.

so when i use ehentai downloader script, im still bound to the 5.000 points limit now?

**Comment by ccloli** [comment]
Yes, it's for not spending your GPs or credits to get the archive, and it will cost your 5000 limits now.

**Comment by kanink007** [comment]
and... what are GP exactly good for? where can i see how much i have?

is there a possibility to still install scrtip version 1.26 to test it again, if it works like before?

**Comment by TheMopKingDom** [comment]
This limits is lock for your IP address, if you want to reset it for faster , chang your ip with vpn or some how you can do.

**Comment by kanink007** [comment]
i see.. so a router reconnect to refresh dynamic ip adresses also works?

**Comment by ccloli** [comment]
You can see your GPs and credits here https://e-hentai.org/exchange.php?t=gp , and spending GPs and credits can download archives directly.

Refreshing your dynamic IP is possible, because it's calculated based on your IP.
