### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by cmcmcmcm2** [ccloli/E-Hentai-Downloader#83]
always"Retrying" and "Response Error"
LIKE THIS PAGE:"https://exhentai.org/g/1123028/829aabc071/"

**Comment by psc2350** [comment]
It works fine for me. Try a different ip if possible. Could be related to your internet connection.

**Comment by cmcmcmcm2** [comment]
yeah, thx. I told my friend to test if it's normal at that time. Probably it's our ISP's problem. Anyway it's fixed.
