### ISSUE TITLE
Compatibilty with Firefox 57 (Quantum)

### ISSUE THREAD

**Issue by Victh** [ccloli/E-Hentai-Downloader#85]
The add-on seems to stop working completely after I updated to 57/quantum. Any idea? No error message whatsoever on the console.

**Comment by yingziwu** [comment]
E-Hentai-Downloader stop working too.

|Name 	|Firefox|
|------------|-----------|
|Version 	|57.0|
|User Agent 	|Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0|
|OS 	|Linux 4.13.12-1-ARCH|

Console:
```
[EHD] E-Hentai Downloader is running.
E-Hentai%20Downloader:388:1
[EHD] Bugs Report > https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback
E-Hentai%20Downloader:389:1
[EHD] To report a bug, it's recommended to provide the logs started with "[EHD]", thanks. =w=
E-Hentai%20Downloader:390:1
Script error:  
ReferenceError: GM_getValue is not defined
Stack trace:
userScript@user-script:http%3A//ext.ccloli.com/E-Hentai%20Downloader:12103:5
scopeWrapper@user-script:http%3A//ext.ccloli.com/E-Hentai%20Downloader:14364:9
@user-script:http%3A//ext.ccloli.com/E-Hentai%20Downloader:361:17
E-Hentai%20Downloader:14366:23
```

**Comment by ccloli** [comment]
Greasemonkey 4.x changes its API, at this time the script is not compatible with Greasemonkey 4.x, please consider downgrade to 3.x (if you didn't upgrade Firefox to 57) or switch to Tampermonkey for this time.

**Comment by yingziwu** [comment]
@ccloli 
Thank you a lot.
Do you have the plan to fix this bug ?

**Comment by ccloli** [comment]
Maybe it needs a few days, as the API changed how it works, the setting data responses asynchronously.

**Comment by Victh** [comment]
I changed to tampermonkey and it's working great. No need to downgrade from Firefox 57. I will test it a bit more before closing the issue. Thanks!

**Comment by ccloli** [comment]
Tried to work on it, however here are still some unexpected bugs on GreaseMonkey 4.x, like  greasemonkey/greasemonkey#2647, greasemonkey/greasemonkey#2712 and so on. Tried to fix them from my side or ignore them if they are not critical, however it failed when creating the zip file, this time I'm not sure what's up. Maybe the work should be delay until sometime GreaseMonkey is stable.

**Comment by ccloli** [comment]
Checked the latest Greasemonkey 4.1beta3, it looks like the sandbox of Greasemonkey still have the bug, but this time it shows the message, thought useless: `Error: Permission denied to access object`, thrown at `zip.generateAsync()`, without any more information.

**Comment by ccloli** [comment]
Got it, the hotfix for Tampermonkey for Safari (db77313b34786950f916ec25409eaa2921f562fd) breaks the script on Greasemonkey 4.x. The new version that supports GM4.x will be published soon.
