### ISSUE TITLE
"Broken" Cannot load the script on Firefox and Google chrome

### ISSUE THREAD

**Issue by Webatone** [ccloli/E-Hentai-Downloader#87]
Hello, So A was using this script for a time, and now its broken, the script cannot load

Firefox: 57.0.2
OS: Windows 8.1
Violentmonkey: 2.8.21
E-Hentai Downloader: 1.27.1

Here the console log :
[exhentai.org-1512706185305.log](https://github.com/ccloli/E-Hentai-Downloader/files/1541356/exhentai.org-1512706185305.log)

`content-script.bundle.js:333
 loading pref showConsoleLogs before prefs were initialised, you will not get the correct result
getPref @ content-script.bundle.js:333
(anonymous) @ content-script.bundle.js:481
a @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:521
a @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:593
a @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:621
a @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1346
a @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1662
a @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:2097
a @ content-script.bundle.js:1
u @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:2106
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:2100
content.js:2461 cur fame:d9c14bfef6dd551dd0c40a381b08cc22
?p=8:1 Mixed Content: The page at 'https://exhentai.org/g/1152356/74185f6f0f/?p=8' was loaded over HTTPS, but requested an insecure image 'http://st.exhentai.net/img/mr.gif'. This content should also be served over HTTPS.
VM392:35 [EHD] E-Hentai Downloader is running.
VM392:36 [EHD] Bugs Report > https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback
VM392:37 [EHD] To report a bug, it's recommended to provide the logs started with "[EHD]", thanks. =w=
VM388:3 Error running script: E-Hentai Downloader
TypeError: Cannot read property 'scriptHandler' of undefined
Cannot read property 'scriptHandler' of undefined
l @ VM388:3
(anonymous) @ VM388:3
value @ VM388:3
(anonymous) @ VM392:1
(anonymous) @ VM392:1
e @ injected.js:1
b.d @ injected.js:1
Inject @ injected.js:1
e @ injected.js:1
(anonymous) @ injected.js:1
o @ VM388:3
(anonymous) @ VM388:3
t @ VM388:3
a @ VM388:3
LoadScripts.c.a.load @ VM388:3
Promise resolved (async)
(anonymous) @ VM388:3
mr.gif:1 GET http://st.exhentai.net/img/mr.gif 404 (Not Found)
Image (async)
(anonymous) @ jquery.min.js:5
access @ jquery.min.js:4
html @ jquery.min.js:5
(anonymous) @ logout.js:8
c @ jquery.min.js:4
fireWith @ jquery.min.js:4
ready @ jquery.min.js:4
q @ jquery.min.js:4
content.js:2471 GetIFrameMode d9c14bfef6dd551dd0c40a381b08cc22
`

**Comment by ccloli** [comment]
Fixed in v1.27.2.
