### ISSUE TITLE
Firefox57.0.2 X64正式版+Violentmonkey v2.8.22无法运行脚本

### ISSUE THREAD

**Issue by yesron** [ccloli/E-Hentai-Downloader#88]
Windows 10 ver.1709

Violentmonkey显示脚本已经打开，但页面没有任何变化
控制台输出：
![default](https://user-images.githubusercontent.com/18094567/33802113-c6c9d9e2-ddaa-11e7-8559-4d3fb5030f8c.png)

另测试在Tampermonkey v4.5.5648下可以正常运行，Greasemonkey 4.0下基本功能正常，但下载进度条不会显示下载速度和进度，只会一下子跳到100%

**Comment by ccloli** [comment]
Duplicate with #87. Fixed in v1.27.2.
