### ISSUE TITLE
Save file in .cbz extension

### ISSUE THREAD

**Issue by mikelei8291** [ccloli/E-Hentai-Downloader#89]
.cbz is the file extension for [Comic book archive](https://en.wikipedia.org/wiki/Comic_book_archive), which can be recognized by comic reader software and opened by them directly.

It's actually a zip file, the only difference is the name of the extension, but by renaming to .cbz, it is more beneficial for people who use comic readers.

Is it possible to provide an option to save the file in .cbz? Thanks.

**Comment by ccloli** [comment]
Added in v1.28 and tested with CDisplay, seems that it works fine. If you have any question, feel free to ask.

**Comment by ccloli** [comment]
You can enable it at `Settings -> Advanced -> Save as CBZ (Comic book archive) file`, and to keep the order of images correct, use it with numbering image feature is recommended.

**Comment by mikelei8291** [comment]
OMG, such a quick update, thanks!
