### ISSUE TITLE
Showing on Bottom?

### ISSUE THREAD

**Issue by iShyboy** [ccloli/E-Hentai-Downloader#9]
I'm using the last version of the script in the last version of Chromium and the scritp keep showing in the bottom of the page after the comments. In firefox it show as usual.
![3MPcdz7](http://i.imgur.com/3MPcdz7.png)

I even tried copy&paste the firefox script on chromium and still after the comments.

**Comment by ccloli** [comment]
This bug cannot be reproduce, please show me an example URL.

**Comment by iShyboy** [comment]
![3MPcdz7](http://vgy.me/Xn6OYc.png)

any url of exhentai its like that, i'm using the latest version of chromium 64 bits on windows. With the latest version of the script, with a fresh install, you could try a portable version of portableappz and try again. On my chrome portable (not latest version) still works fine.

**Comment by ccloli** [comment]
Try replacing Line `10928` 
```js
document.body.insertBefore(ehDownloadBox, document.getElementById('asm');
```
by this:
```js
document.body.insertBefore(ehDownloadBox, document.getElementById('asm') || document.querySelector('.gm').nextElementSibling);
```
If it works, the bug is probably caused by using any scripts or extensions like AdBlock.

**Comment by iShyboy** [comment]
Worked fine, thanks, it was not from anything like adblock or others scripts, it was from the perk of ads-be gone.
