### ISSUE TITLE
與 Multi-Page Viewer 衝突 (Supports Multi-Page Viewer)

### ISSUE THREAD

**Issue by ShangTaiSi** [ccloli/E-Hentai-Downloader#91]
Multi-Page Viewer 是用 Hath 換的其中一個東西，沒關掉時就會一直重試
![image](https://user-images.githubusercontent.com/35423954/34916417-f11c022c-f972-11e7-946f-7bae4fb8611d.png)

**Comment by ccloli** [comment]
能否試試看訪問 https://exhentai.org/s/7b87643838/530350-1 這個頁面是普通的瀏覽頁面還是付費的 Multi-Page Viewer 呢？

如果是普通的瀏覽頁面的話，能否幫忙訪問 https://exhentai.org/g/530350/8b3c7e4a21/ ，然後右鍵選擇查看網頁源碼，然後把源碼複製粘貼到這呢？粘貼的文本前後最好加上 \`\`\`，就像下面這樣：

    ```
    [將源碼粘貼到這]
    ```

腳本只能解析通常頁面，對於付費的 MPV 目前是沒有支援的（數據的格式也有很大的不同），所以只能試著看看能否跳轉到普通的頁面了

如果最後還是跳轉到付費的 MPV 的話，那麼只能在下載的時候先關閉 MPV 功能了

**Comment by ccloli** [comment]
Hi, 大致看了下源碼，似乎源碼中沒有直接暴露每個頁面的 key，所以無法直接從 gallery 的頁面獲取到頁面的地址。不過看了下 MPV 的源碼，MPV 的頁面里似乎暴露了各個頁面的 key，所以應該還是有辦法的，這幾天我試試看能不能從 MPV 解析。

**Comment by ccloli** [comment]
新發佈的 v1.29 尝试對 Multi-Page Viewer 進行了支援，能否幫忙確認下現在是否可以在啟用 MPV 的情況下進行下載，謝謝。

**Comment by ShangTaiSi** [comment]
有成功，可以下載

**Comment by ccloli** [comment]
OK，那我把 issue 關了，有什麼其他問題的話可以再開新帖詢問，辛苦了
