### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by Noam-Ruka** [ccloli/E-Hentai-Downloader#95]
下载文件频繁出现0KB/S downloading的情况，并且多数情况下点force about重新下载后还是会0KB/S，之前没有出现过。

**Comment by ccloli** [comment]
这是与节点连接性不佳导致的，是网络问题。EH 的节点是由志愿者搭建的，而原始的服务器也在荷兰，所以网络速度和质量视与连接的节点的网络线路有关
