### ISSUE TITLE
和那个标签脚本EhTagSyringe一起运行，就没法显示预计GP消耗了

### ISSUE THREAD

**Issue by sunyink** [ccloli/E-Hentai-Downloader#97]
就是e站那个标签Tampermonkey脚本，单开测试了下。
发现同开时，没法显示若下载当前本子将消耗多少GP信息。不太不方便，不知能不能好。

消失的原文本就是这个：“ | Estimated Limits Cost: *"

**Comment by sunyink** [comment]
刚还发现，点下载按钮后下载窗也不弹出来，可能有冲突了。

**Comment by ccloli** [comment]
See https://github.com/ccloli/E-Hentai-Downloader/issues/50#issuecomment-254703671

**Comment by sunyink** [comment]
嗯 我按照顺序的思路又测试了下还是不行。把Downloader跳到#1了问题依旧。把EhTagSyringe停掉一刷新又正常了。

**Comment by sunyink** [comment]
[exhentai.org-1521947398299.log](https://github.com/ccloli/E-Hentai-Downloader/files/1844986/exhentai.org-1521947398299.log)
不知这个能否帮上忙，测试页面的Console，有1红叉“Failed to load resource: net::ERR_CONNECTION_CLOSED”

**Comment by ccloli** [comment]
之前测试的时候 EhTagSyringe 有些 bug 所以没有正常运行，调整了一下代码后现在能复现。EhTagSyringe 设置在 `document-start` 运行，使得调整脚本顺序没什么意义（虽然我也不觉得 `document-start` 有什么意义）。看起来你正在使用 Tampermonkey，可以尝试在 TM 的脚本设置中让其在 `document-end` 运行，目前来看是没什么问题的。在 TM 中点击脚本，选择上面的「设置」标签，然后将「运行时期」改成 `document-end` 即可。如果没有看到这个选项，可以在 TM 的设置里将「配置模式」改为「高级」。

![image](https://user-images.githubusercontent.com/8115912/37871704-418044f4-3027-11e8-97cb-e40b5b06ddd6.png)

**Comment by sunyink** [comment]
嗯！行啦，操作后我终于可以双持这两把利器了~~so nice~
感谢你能腾出时间，Tx~
